# 💳 Extração dos dados abertos — Cartão de Pagamento do Governo Federal (CPGF)

Este notebook foi preparado para **baixar, organizar, conferir e consolidar os arquivos mensais do Cartão de Pagamento do Governo Federal (CPGF)** disponibilizados pelo Portal da Transparência.

A lógica preserva o seguinte padrão de extração: o arquivo `.zip` é baixado **somente para o armazenamento temporário do Google Colab**, o `.csv` mensal é extraído diretamente para o Google Drive e, ao final da extração, o arquivo compactado é apagado.

O endereço de download segue o padrão:

`https://portaldatransparencia.gov.br/download-de-dados/cpgf/AAAAMM`

Em que `AAAA` representa o ano e `MM` representa o mês.

Nesta versão, o período completo considerado é de **janeiro de 2013 (`201301`) a julho de 2026 (`202607`)**, totalizando **163 competências mensais**.

Os CSVs mensais serão salvos diretamente em:

`/content/drive/MyDrive/Suprimentos de Fundos - CPGF`

e o arquivo consolidado será gravado em:

`/content/drive/MyDrive/Suprimentos de Fundos - CPGF/dados_consolidado`

> **Princípio de preservação:** os arquivos mensais são mantidos exatamente como publicados pelo Portal, com alteração apenas do nome do arquivo para o padrão `AAAAMM_CPGF.csv`. Nenhuma linha é eliminada, nenhuma duplicidade é removida e nenhuma coluna é transformada nesses arquivos brutos.

> **Proteção antirrobô:** o Portal da Transparência pode retornar uma página HTML, códigos HTTP de bloqueio temporário ou exigir validação pelo navegador. O notebook utiliza sessão HTTP, cabeçalhos usuais de navegador, pausas aleatórias e tentativas progressivas para reduzir requisições sucessivas. Ele **não tenta contornar CAPTCHA ou validações que exijam interação humana**; nesses casos, há uma alternativa segura de download manual.

## 1️⃣ Montar o Google Drive

Execute esta célula para permitir que o Colab salve os CSVs mensais e o arquivo consolidado diretamente no seu Google Drive.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## 2️⃣ Importar bibliotecas e configurar o projeto

Nesta etapa são definidas as pastas, o período completo da extração e os parâmetros de acesso ao Portal.

### 📁 Organização adotada

- pasta principal do projeto: contém diretamente os **163 CSVs mensais**;
- `dados_consolidado`: recebe o CSV único produzido ao final;
- `logs`: recebe arquivos de controle, validação e diagnóstico;
- pastas temporárias em `/content`: recebem os ZIPs e arquivos intermediários e são apagadas ao longo da execução.

Assim, os arquivos compactados **não são mantidos no Google Drive**.

In [2]:
import csv
import hashlib
import os
import random
import re
import shutil
import time
import zipfile
from pathlib import Path
from datetime import datetime
from typing import List, Optional, Dict, Tuple, Iterable

import pandas as pd
import requests


# ==========================
# 📁 Pastas do projeto
# ==========================

PROJECT_DIR = Path('/content/drive/MyDrive/Suprimentos de Fundos - CPGF')

# Os CSVs mensais ficam diretamente na pasta principal.
CSV_DIR = PROJECT_DIR

# Saídas auxiliares.
CONSOLIDADO_DIR = PROJECT_DIR / 'dados_consolidado'
LOG_DIR = PROJECT_DIR / 'logs'

# ZIPs nunca são mantidos no Drive.
TMP_ZIP_DIR = Path('/content/cpgf_tmp_zip')
TMP_EXTRACT_DIR = Path('/content/cpgf_tmp_extract')
MANUAL_ZIP_DIR = Path('/content/cpgf_zips_manuais')

for pasta in [
    PROJECT_DIR,
    CONSOLIDADO_DIR,
    LOG_DIR,
    TMP_ZIP_DIR,
    TMP_EXTRACT_DIR,
    MANUAL_ZIP_DIR,
]:
    pasta.mkdir(parents=True, exist_ok=True)


# ==========================
# 🧾 Arquivos de controle
# ==========================

LOG_FILE = LOG_DIR / 'download_cpgf.log'
CONTROLE_ARQUIVOS_CSV = LOG_DIR / 'controle_arquivos_cpgf.csv'
RELATORIO_ESQUEMAS_CSV = LOG_DIR / 'relatorio_esquemas_cpgf.csv'
RELATORIO_CONSOLIDACAO_CSV = LOG_DIR / 'relatorio_consolidacao_cpgf.csv'
VALIDACAO_FINAL_CSV = LOG_DIR / 'validacao_final_cpgf.csv'


# ==========================
# ⚙️ Configurações gerais
# ==========================

BASE_URL = 'https://portaldatransparencia.gov.br/download-de-dados/cpgf'

COMPETENCIA_INICIAL = '201301'
COMPETENCIA_FINAL = '202607'

# Pausa aleatória entre competências.
PAUSA_MIN_SEGUNDOS = 25
PAUSA_MAX_SEGUNDOS = 45

# Tentativas por competência.
MAX_TENTATIVAS = 3

# Espera adicional quando houver indício de bloqueio/HTML.
PAUSA_HTML_MIN_SEGUNDOS = 180
PAUSA_HTML_MAX_SEGUNDOS = 300

# Tempo máximo de uma requisição.
TIMEOUT_DOWNLOAD_SEGUNDOS = 1800

# Se True, um bloco anual para ao detectar HTML/bloqueio.
# A recuperação posterior pode ser usada para tentar novamente apenas os meses ausentes.
ABORTAR_BLOCO_SE_DETECTAR_BLOQUEIO = True

# Consolidação em blocos para reduzir uso de RAM.
CHUNKSIZE_CONSOLIDACAO = 250_000

# Por segurança, a consolidação só começa quando todos os 163 arquivos estiverem presentes.
EXIGIR_TODAS_COMPETENCIAS_PARA_CONSOLIDAR = True


def log(msg: str) -> None:
    """Registra uma mensagem na tela e no arquivo de log."""
    agora = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    linha = f'[{agora}] {msg}'
    print(linha)

    with open(LOG_FILE, 'a', encoding='utf-8') as f:
        f.write(linha + '\\n')


log('✅ Configuração concluída.')
log(f'📁 Pasta principal: {PROJECT_DIR}')
log(f'📁 Pasta do consolidado: {CONSOLIDADO_DIR}')
log(f'📁 Pasta de logs: {LOG_DIR}')
log(f'📆 Período configurado: {COMPETENCIA_INICIAL} a {COMPETENCIA_FINAL}')

[2026-08-09 23:12:17] ✅ Configuração concluída.
[2026-08-09 23:12:17] 📁 Pasta principal: /content/drive/MyDrive/Suprimentos de Fundos - CPGF
[2026-08-09 23:12:17] 📁 Pasta do consolidado: /content/drive/MyDrive/Suprimentos de Fundos - CPGF/dados_consolidado
[2026-08-09 23:12:17] 📁 Pasta de logs: /content/drive/MyDrive/Suprimentos de Fundos - CPGF/logs
[2026-08-09 23:12:17] 📆 Período configurado: 201301 a 202607

## 3️⃣ Funções auxiliares de download e extração

As funções abaixo cuidam de sete tarefas principais:

1. gerar a lista de competências no formato `AAAAMM`;
2. criar uma sessão HTTP com cabeçalhos usuais de navegador;
3. baixar o ZIP mensal apenas para o armazenamento temporário do Colab;
4. identificar retorno HTML ou bloqueio temporário;
5. realizar novas tentativas com espera progressiva;
6. extrair somente o CSV e salvá-lo no Drive com nome padronizado;
7. apagar o ZIP imediatamente após a extração.

A função não substitui validações que dependam de JavaScript ou interação humana. Se isso ocorrer, utilize a seção de **download manual** mais adiante.

In [3]:
class PortalRetornouHTML(Exception):
    """O Portal retornou uma página HTML em vez do arquivo ZIP esperado."""
    pass


class PortalBloqueioTemporario(Exception):
    """O Portal sinalizou bloqueio temporário, como HTTP 403 ou 429."""
    pass


def validar_competencia(competencia: str) -> bool:
    """Confere se a competência está no formato AAAAMM."""
    return bool(re.fullmatch(r'20\d{2}(0[1-9]|1[0-2])', str(competencia)))


def proxima_competencia(competencia: str) -> str:
    """Retorna a competência seguinte no formato AAAAMM."""
    if not validar_competencia(competencia):
        raise ValueError(f'Competência inválida: {competencia}')

    ano = int(competencia[:4])
    mes = int(competencia[4:])

    if mes == 12:
        ano += 1
        mes = 1
    else:
        mes += 1

    return f'{ano}{mes:02d}'


def gerar_competencias(
    competencia_inicial: str,
    competencia_final: str
) -> List[str]:
    """Gera competências mensais entre duas datas, inclusive."""
    if not validar_competencia(competencia_inicial):
        raise ValueError(f'Competência inicial inválida: {competencia_inicial}')

    if not validar_competencia(competencia_final):
        raise ValueError(f'Competência final inválida: {competencia_final}')

    if competencia_inicial > competencia_final:
        raise ValueError('A competência inicial não pode ser maior que a competência final.')

    competencias = []
    atual = competencia_inicial

    while atual <= competencia_final:
        competencias.append(atual)
        atual = proxima_competencia(atual)

    return competencias


COMPETENCIAS_ESPERADAS = gerar_competencias(
    COMPETENCIA_INICIAL,
    COMPETENCIA_FINAL
)

print(f'📆 Total de competências esperadas: {len(COMPETENCIAS_ESPERADAS)}')


def caminho_csv_esperado(competencia: str) -> Path:
    """Retorna o caminho padronizado do CSV mensal no Drive."""
    return CSV_DIR / f'{competencia}_CPGF.csv'


def caminho_zip_tmp(competencia: str) -> Path:
    """Retorna o caminho temporário do ZIP no Colab."""
    return TMP_ZIP_DIR / f'{competencia}_CPGF.zip'


def arquivo_tem_assinatura_zip(caminho: Path) -> bool:
    """Verifica a assinatura mágica de um ZIP ('PK')."""
    caminho = Path(caminho)

    if not caminho.exists() or caminho.stat().st_size < 4:
        return False

    with open(caminho, 'rb') as f:
        return f.read(4).startswith(b'PK')


def ler_inicio_arquivo(caminho: Path, limite: int = 1500) -> str:
    """Lê apenas o início de um arquivo para diagnóstico."""
    try:
        with open(caminho, 'rb') as f:
            trecho = f.read(limite)

        return trecho.decode('utf-8', errors='replace')

    except Exception as e:
        return f'Não foi possível ler a prévia: {repr(e)}'


def criar_sessao_requests() -> requests.Session:
    """
    Cria uma sessão HTTP semelhante a uma navegação convencional.

    Os cabeçalhos servem para tornar a requisição mais completa e consistente.
    Eles não substituem validações por JavaScript, CAPTCHA ou interação humana.
    """
    sessao = requests.Session()

    sessao.headers.update({
        'User-Agent': (
            'Mozilla/5.0 (X11; Linux x86_64) '
            'AppleWebKit/537.36 (KHTML, like Gecko) '
            'Chrome/151.0 Safari/537.36'
        ),
        'Accept': (
            'application/zip,application/octet-stream,'
            'application/x-zip-compressed,text/html;q=0.8,*/*;q=0.7'
        ),
        'Accept-Language': 'pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7',
        'Connection': 'keep-alive',
        'Cache-Control': 'no-cache',
        'Pragma': 'no-cache',
        'Referer': BASE_URL,
    })

    return sessao


SESSAO = criar_sessao_requests()


def renovar_sessao() -> None:
    """Fecha a sessão atual e cria uma nova sessão HTTP."""
    global SESSAO

    try:
        SESSAO.close()
    except Exception:
        pass

    SESSAO = criar_sessao_requests()
    log('🔄 Sessão HTTP renovada.')


def pausa_aleatoria(
    minimo: int = PAUSA_MIN_SEGUNDOS,
    maximo: int = PAUSA_MAX_SEGUNDOS,
    motivo: str = 'antes da próxima requisição'
) -> int:
    """Aguarda um intervalo aleatório e retorna o tempo sorteado."""
    segundos = random.randint(minimo, maximo)
    log(f'😴 Aguardando {segundos}s {motivo}...')
    time.sleep(segundos)
    return segundos


def baixar_zip_temporario(
    competencia: str,
    timeout: int = TIMEOUT_DOWNLOAD_SEGUNDOS
) -> Path:
    """
    Baixa o ZIP mensal para o armazenamento temporário do Colab.

    Possíveis situações:
    - ZIP válido -> retorna o caminho;
    - HTML -> levanta PortalRetornouHTML;
    - HTTP 403/429 -> levanta PortalBloqueioTemporario;
    - outros erros HTTP -> requests levanta exceção.
    """
    if not validar_competencia(competencia):
        raise ValueError(f'Competência inválida: {competencia}')

    url = f'{BASE_URL}/{competencia}'
    destino = caminho_zip_tmp(competencia)

    if destino.exists():
        destino.unlink()

    log(f'⬇️ Iniciando download temporário de {competencia}: {url}')

    with SESSAO.get(
        url,
        stream=True,
        timeout=timeout,
        allow_redirects=True
    ) as resposta:

        content_type = resposta.headers.get('Content-Type', '')
        content_length = resposta.headers.get('Content-Length', 'não informado')

        log(
            f'🌐 HTTP {resposta.status_code} | '
            f'Content-Type: {content_type} | '
            f'Content-Length: {content_length}'
        )

        if resposta.status_code in (403, 429):
            previa = resposta.raw.read(1500, decode_content=True)
            texto = previa.decode('utf-8', errors='replace')

            print('\\n' + '-' * 80)
            print(texto[:1500])
            print('-' * 80 + '\\n')

            raise PortalBloqueioTemporario(
                f'O Portal retornou HTTP {resposta.status_code} para {competencia}.'
            )

        resposta.raise_for_status()

        with open(destino, 'wb') as f:
            for bloco in resposta.iter_content(chunk_size=1024 * 1024):
                if bloco:
                    f.write(bloco)

    tamanho_mb = destino.stat().st_size / (1024 ** 2)
    log(f'📦 Arquivo recebido: {tamanho_mb:.2f} MB')

    if arquivo_tem_assinatura_zip(destino):
        log(f'✅ ZIP válido recebido para {competencia}.')
        return destino

    previa = ler_inicio_arquivo(destino)
    previa_minuscula = previa.lower()

    if (
        '<html' in previa_minuscula
        or '<!doctype html' in previa_minuscula
        or 'javascript' in previa_minuscula
        or 'captcha' in previa_minuscula
        or 'robot' in previa_minuscula
        or 'verifica' in previa_minuscula
    ):
        log('⚠️ O Portal retornou HTML em vez de ZIP.')
        print('\\n' + '-' * 80)
        print(previa[:1500])
        print('-' * 80 + '\\n')

        try:
            destino.unlink()
        except Exception:
            pass

        raise PortalRetornouHTML(
            f'O Portal retornou HTML para {competencia}. '
            'Pode haver validação por navegador ou proteção antirrobô.'
        )

    print('\\n' + '-' * 80)
    print(previa[:1500])
    print('-' * 80 + '\\n')

    try:
        destino.unlink()
    except Exception:
        pass

    raise ValueError(
        f'O arquivo recebido para {competencia} não parece ser um ZIP válido.'
    )


def selecionar_csv_no_zip(
    z: zipfile.ZipFile,
    competencia: Optional[str] = None
) -> str:
    """
    Seleciona o CSV mais provável dentro do ZIP.

    Regras:
    1. se houver somente um CSV, usa esse arquivo;
    2. se houver vários, prioriza nome contendo a competência;
    3. persistindo empate, escolhe o maior CSV pelo tamanho descompactado.
    """
    membros_csv = [
        info for info in z.infolist()
        if not info.is_dir() and info.filename.lower().endswith('.csv')
    ]

    if not membros_csv:
        raise ValueError('Nenhum CSV foi encontrado dentro do ZIP.')

    if len(membros_csv) == 1:
        return membros_csv[0].filename

    candidatos = membros_csv

    if competencia:
        com_competencia = [
            info for info in membros_csv
            if competencia in Path(info.filename).name
        ]

        if com_competencia:
            candidatos = com_competencia

    escolhido = max(candidatos, key=lambda info: info.file_size)

    log(
        f'⚠️ O ZIP contém {len(membros_csv)} CSVs. '
        f'Foi selecionado: {Path(escolhido.filename).name}'
    )

    return escolhido.filename


def extrair_csv_do_zip(
    zip_path: Path,
    competencia: str,
    apagar_zip: bool = True
) -> Path:
    """
    Extrai o CSV do ZIP para o Google Drive.

    O conteúdo bruto não é modificado.
    Apenas o nome final é padronizado para AAAAMM_CPGF.csv.
    """
    zip_path = Path(zip_path)

    if not zip_path.exists():
        raise FileNotFoundError(f'ZIP não encontrado: {zip_path}')

    if not zipfile.is_zipfile(zip_path):
        raise ValueError(f'O arquivo não é um ZIP válido: {zip_path}')

    destino_csv = caminho_csv_esperado(competencia)

    if destino_csv.exists() and destino_csv.stat().st_size > 0:
        log(f'⏭️ CSV já existe no Drive: {destino_csv.name}')

        if apagar_zip and zip_path.exists():
            zip_path.unlink()
            log(f'🧹 ZIP temporário apagado: {zip_path.name}')

        return destino_csv

    if TMP_EXTRACT_DIR.exists():
        shutil.rmtree(TMP_EXTRACT_DIR)

    TMP_EXTRACT_DIR.mkdir(parents=True, exist_ok=True)

    with zipfile.ZipFile(zip_path, 'r') as z:
        membro = selecionar_csv_no_zip(z, competencia=competencia)
        extraido_tmp = Path(z.extract(membro, path=TMP_EXTRACT_DIR))

    # Move o conteúdo sem reescrever o CSV.
    shutil.move(str(extraido_tmp), str(destino_csv))

    tamanho_mb = destino_csv.stat().st_size / (1024 ** 2)
    log(f'✅ CSV salvo: {destino_csv.name} ({tamanho_mb:.2f} MB)')

    try:
        shutil.rmtree(TMP_EXTRACT_DIR)
    except Exception:
        pass

    if apagar_zip and zip_path.exists():
        zip_path.unlink()
        log(f'🧹 ZIP temporário apagado: {zip_path.name}')

    return destino_csv


def processar_mes(
    competencia: str,
    max_tentativas: int = MAX_TENTATIVAS,
    espera_progressiva_base: int = 60
) -> bool:
    """
    Baixa, valida e extrai uma competência.

    Em erros temporários, renova a sessão e faz espera progressiva.
    """
    csv_path = caminho_csv_esperado(competencia)

    if csv_path.exists() and csv_path.stat().st_size > 0:
        log(f'⏭️ {competencia}: CSV já existe. Nada a fazer.')
        return True

    ultima_excecao = None

    for tentativa in range(1, max_tentativas + 1):
        log(f'🔁 {competencia} | tentativa {tentativa}/{max_tentativas}')

        try:
            zip_path = baixar_zip_temporario(competencia)
            extrair_csv_do_zip(
                zip_path,
                competencia=competencia,
                apagar_zip=True
            )

            if csv_path.exists() and csv_path.stat().st_size > 0:
                log(f'🎉 Competência concluída: {competencia}')
                return True

            raise RuntimeError(
                f'O processamento terminou, mas o CSV não foi localizado: {csv_path}'
            )

        except (PortalRetornouHTML, PortalBloqueioTemporario) as e:
            ultima_excecao = e
            log(f'🚧 {type(e).__name__}: {e}')

            renovar_sessao()

            if tentativa < max_tentativas:
                minimo = espera_progressiva_base * tentativa
                maximo = minimo + 60
                pausa_aleatoria(
                    minimo=minimo,
                    maximo=maximo,
                    motivo='antes de uma nova tentativa'
                )

        except (
            requests.RequestException,
            zipfile.BadZipFile,
            OSError,
            RuntimeError,
            ValueError
        ) as e:
            ultima_excecao = e
            log(f'❌ Erro em {competencia}: {repr(e)}')

            if tentativa < max_tentativas:
                minimo = 30 * tentativa
                maximo = minimo + 45
                pausa_aleatoria(
                    minimo=minimo,
                    maximo=maximo,
                    motivo='antes de uma nova tentativa'
                )

        finally:
            zip_tmp = caminho_zip_tmp(competencia)

            # Se algum arquivo inválido tiver permanecido, ele é removido.
            if zip_tmp.exists() and not arquivo_tem_assinatura_zip(zip_tmp):
                try:
                    zip_tmp.unlink()
                except Exception:
                    pass

    log(
        f'❌ Não foi possível concluir {competencia} '
        f'após {max_tentativas} tentativas.'
    )

    if isinstance(
        ultima_excecao,
        (PortalRetornouHTML, PortalBloqueioTemporario)
    ):
        raise ultima_excecao

    return False


def executar_bloco(
    competencia_inicial: str,
    competencia_final: str,
    abortar_em_bloqueio: bool = ABORTAR_BLOCO_SE_DETECTAR_BLOQUEIO
) -> Dict[str, List[str]]:
    """Executa uma faixa mensal com pausa aleatória entre as competências."""
    competencias = gerar_competencias(
        competencia_inicial,
        competencia_final
    )

    log(
        f'🚀 Iniciando bloco {competencia_inicial} a {competencia_final} '
        f'({len(competencias)} competência(s)).'
    )

    concluidas = []
    falhas = []
    bloqueadas = []

    for i, competencia in enumerate(competencias, start=1):
        log(f'📌 [{i}/{len(competencias)}] Competência {competencia}')

        try:
            sucesso = processar_mes(competencia)

            if sucesso:
                concluidas.append(competencia)
            else:
                falhas.append(competencia)

        except (PortalRetornouHTML, PortalBloqueioTemporario) as e:
            bloqueadas.append(competencia)
            log(f'🚧 Bloqueio/HTML detectado em {competencia}: {e}')

            if abortar_em_bloqueio:
                log(
                    '🛑 O bloco foi interrompido para evitar requisições '
                    'sucessivas durante a proteção do Portal.'
                )
                break

        except Exception as e:
            falhas.append(competencia)
            log(f'❌ Erro inesperado em {competencia}: {repr(e)}')

        if i < len(competencias):
            pausa_aleatoria()

    resumo = {
        'concluidas': concluidas,
        'falhas': falhas,
        'bloqueadas': bloqueadas,
    }

    log(
        f'📊 Resumo do bloco: '
        f'{len(concluidas)} concluída(s), '
        f'{len(falhas)} falha(s), '
        f'{len(bloqueadas)} bloqueio(s).'
    )

    return resumo

📆 Total de competências esperadas: 163

## 4️⃣ Funções para conferir estrutura, codificação e separador

A amostra de julho de 2026 contém 15 colunas. Elas são usadas apenas como **referência inicial de estrutura**.

A validação:

- lê somente o cabeçalho;
- não modifica o CSV;
- identifica a codificação;
- identifica o separador;
- compara o conjunto e a ordem das colunas;
- registra eventuais diferenças antes da consolidação.

Mesmo que algum arquivo histórico tenha uma estrutura diferente, a consolidação foi preparada para realizar uma **união flexível pelo nome das colunas**, preservando todas as colunas encontradas.

In [4]:
# Estrutura observada na amostra 202607_CPGF.csv.
COLUNAS_REFERENCIA_202607 = [
    'CÓDIGO ÓRGÃO SUPERIOR',
    'NOME ÓRGÃO SUPERIOR',
    'CÓDIGO ÓRGÃO',
    'NOME ÓRGÃO',
    'CÓDIGO UNIDADE GESTORA',
    'NOME UNIDADE GESTORA',
    'ANO EXTRATO',
    'MÊS EXTRATO',
    'CPF PORTADOR',
    'NOME PORTADOR',
    'CNPJ OU CPF FAVORECIDO',
    'NOME FAVORECIDO',
    'TRANSAÇÃO',
    'DATA TRANSAÇÃO',
    'VALOR TRANSAÇÃO',
]

CODIFICACOES_CANDIDATAS = [
    'utf-8-sig',
    'utf-8',
    'cp1252',
    'latin1',
]

SEPARADORES_CANDIDATOS = [';', ',', '\t']


def detectar_codificacao_csv(caminho_csv: Path) -> str:
    """Detecta uma codificação suficiente para leitura do arquivo."""
    caminho_csv = Path(caminho_csv)
    amostra = caminho_csv.read_bytes()[:100_000]

    for encoding in CODIFICACOES_CANDIDATAS:
        try:
            amostra.decode(encoding)
            return encoding
        except UnicodeDecodeError:
            continue

    return 'latin1'


def detectar_separador_csv(
    caminho_csv: Path,
    encoding: Optional[str] = None
) -> str:
    """Detecta o separador entre ; , e tabulação."""
    caminho_csv = Path(caminho_csv)

    if encoding is None:
        encoding = detectar_codificacao_csv(caminho_csv)

    with open(caminho_csv, 'r', encoding=encoding, errors='replace') as f:
        primeira_linha = f.readline()

    contagens = {
        sep: primeira_linha.count(sep)
        for sep in SEPARADORES_CANDIDATOS
    }

    return max(contagens, key=contagens.get)


def ler_cabecalho_csv(caminho_csv: Path) -> Tuple[List[str], str, str]:
    """Lê apenas o cabeçalho e retorna colunas, codificação e separador."""
    caminho_csv = Path(caminho_csv)

    encoding = detectar_codificacao_csv(caminho_csv)
    separador = detectar_separador_csv(caminho_csv, encoding=encoding)

    with open(
        caminho_csv,
        'r',
        encoding=encoding,
        newline=''
    ) as f:
        leitor = csv.reader(f, delimiter=separador)
        cabecalho = next(leitor)

    # Remove eventual BOM residual.
    if cabecalho:
        cabecalho[0] = cabecalho[0].lstrip('\ufeff')

    return cabecalho, encoding, separador


def validar_estrutura_csv(caminho_csv: Path) -> Dict[str, object]:
    """Valida um CSV contra a estrutura de referência de julho/2026."""
    caminho_csv = Path(caminho_csv)
    cabecalho, encoding, separador = ler_cabecalho_csv(caminho_csv)

    ausentes = [
        c for c in COLUNAS_REFERENCIA_202607
        if c not in cabecalho
    ]

    extras = [
        c for c in cabecalho
        if c not in COLUNAS_REFERENCIA_202607
    ]

    return {
        'arquivo': caminho_csv.name,
        'caminho': str(caminho_csv),
        'encoding': encoding,
        'separador': repr(separador),
        'numero_colunas': len(cabecalho),
        'cabecalho': cabecalho,
        'igual_referencia_conjunto': set(cabecalho) == set(COLUNAS_REFERENCIA_202607),
        'igual_referencia_ordem': cabecalho == COLUNAS_REFERENCIA_202607,
        'colunas_ausentes': ausentes,
        'colunas_extras': extras,
    }

## 5️⃣ Teste diagnóstico — julho de 2026

Antes de iniciar os 163 downloads, execute uma competência isolada.

Foi escolhido `202607` porque existe uma amostra desse período para comparação.

A célula:

1. tenta baixar o ZIP;
2. extrai apenas o CSV;
3. salva `202607_CPGF.csv` diretamente na pasta principal;
4. apaga o ZIP temporário;
5. confere o cabeçalho do CSV resultante.

Se o Portal retornar HTML ou bloquear temporariamente a requisição, a mensagem de diagnóstico será exibida.

In [5]:
# 🧪 Teste diagnóstico com julho de 2026

try:
    processar_mes('202607')
except (PortalRetornouHTML, PortalBloqueioTemporario) as e:
    print(f'🚧 Teste interrompido por proteção do Portal: {e}')

csv_teste = caminho_csv_esperado('202607')

if csv_teste.exists() and csv_teste.stat().st_size > 0:
    resultado_teste = validar_estrutura_csv(csv_teste)

    print('\n📋 Resultado da validação do CSV de teste:')
    for chave, valor in resultado_teste.items():
        if chave != 'cabecalho':
            print(f'- {chave}: {valor}')

    print('\n🧩 Cabeçalho encontrado:')
    print(resultado_teste['cabecalho'])
else:
    print('⚠️ O CSV 202607 ainda não está disponível no Drive.')

[2026-08-09 19:45:29] 🔁 202607 | tentativa 1/3
[2026-08-09 19:45:29] ⬇️ Iniciando download temporário de 202607: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202607
[2026-08-09 19:45:30] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 315081
[2026-08-09 19:45:30] 📦 Arquivo recebido: 0.30 MB
[2026-08-09 19:45:30] ✅ ZIP válido recebido para 202607.
[2026-08-09 19:45:30] ✅ CSV salvo: 202607_CPGF.csv (3.98 MB)
[2026-08-09 19:45:30] 🧹 ZIP temporário apagado: 202607_CPGF.zip
[2026-08-09 19:45:30] 🎉 Competência concluída: 202607

📋 Resultado da validação do CSV de teste:
- arquivo: 202607_CPGF.csv
- caminho: /content/drive/MyDrive/Suprimentos de Fundos - CPGF/202607_CPGF.csv
- encoding: cp1252
- separador: ';'
- numero_colunas: 15
- igual_referencia_conjunto: True
- igual_referencia_ordem: True
- colunas_ausentes: []
- colunas_extras: []

🧩 Cabeçalho encontrado:
['CÓDIGO ÓRGÃO SUPERIOR', 'NOME ÓRGÃO SUPERIOR', 'CÓDIGO ÓRGÃO', 'NOME ÓRGÃO', 'CÓDIGO UNIDADE GESTORA', 'NOME UNIDADE GESTORA', 'ANO EXTRATO', 'MÊS EXTRATO', 'CPF PORTADOR', 'NOME PORTADOR', 'CNPJ OU CPF FAVORECIDO', 'NOME FAVORECIDO', 'TRANSAÇÃO', 'DATA TRANSAÇÃO', 'VALOR TRANSAÇÃO']

## 6️⃣ Downloads anuais

A extração foi dividida em **uma célula por ano**.

Isso facilita:

- acompanhar o progresso;
- retomar o processamento após interrupção do Colab;
- identificar o ponto em que o Portal iniciou uma verificação antirrobô;
- evitar repetir competências que já foram baixadas.

Cada célula ignora automaticamente os CSVs que já estiverem salvos.

### 📦 2013 — janeiro a dezembro

Baixa as 12 competências de `201301` a `201312`.

In [6]:
executar_bloco('201301', '201312')

[2026-08-09 19:45:38] 🚀 Iniciando bloco 201301 a 201312 (12 competência(s)).
[2026-08-09 19:45:38] 📌 [1/12] Competência 201301
[2026-08-09 19:45:38] 🔁 201301 | tentativa 1/3
[2026-08-09 19:45:38] ⬇️ Iniciando download temporário de 201301: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201301
[2026-08-09 19:45:39] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 391846
[2026-08-09 19:45:40] 📦 Arquivo recebido: 0.37 MB
[2026-08-09 19:45:40] ✅ ZIP válido recebido para 201301.
[2026-08-09 19:45:40] ✅ CSV salvo: 201301_CPGF.csv (5.03 MB)
[2026-08-09 19:45:40] 🧹 ZIP temporário apagado: 201301_CPGF.zip
[2026-08-09 19:45:40] 🎉 Competência concluída: 201301
[2026-08-09 19:45:40] 😴 Aguardando 28s antes da próxima requisição...
[2026-08-09 19:46:08] 📌 [2/12] Competência 201302
[2026-08-09 19:46:08] 🔁 201302 | tentativa 1/3
[2026-08-09 19:46:08] ⬇️ Iniciando download temporário de 201302: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201302
[2026-08-09 19:46:08] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 83302
[2026-08-09 19:46:09] 📦 Arquivo recebido: 0.08 MB
[2026-08-09 19:46:09] ✅ ZIP válido recebido para 201302.
[2026-08-09 19:46:09] ✅ CSV salvo: 201302_CPGF.csv (0.91 MB)
[2026-08-09 19:46:09] 🧹 ZIP temporário apagado: 201302_CPGF.zip
[2026-08-09 19:46:09] 🎉 Competência concluída: 201302
[2026-08-09 19:46:09] 😴 Aguardando 28s antes da próxima requisição...
[2026-08-09 19:46:37] 📌 [3/12] Competência 201303
[2026-08-09 19:46:37] 🔁 201303 | tentativa 1/3
[2026-08-09 19:46:37] ⬇️ Iniciando download temporário de 201303: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201303
[2026-08-09 19:46:37] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 230945
[2026-08-09 19:46:38] 📦 Arquivo recebido: 0.22 MB
[2026-08-09 19:46:38] ✅ ZIP válido recebido para 201303.
[2026-08-09 19:46:38] ✅ CSV salvo: 201303_CPGF.csv (2.64 MB)
[2026-08-09 19:46:38] 🧹 ZIP temporário apagado: 201303_CPGF.zip
[2026-08-09 19:46:38] 🎉 Competência concluída: 201303
[2026-08-09 19:46:38] 😴 Aguardando 38s antes da próxima requisição...
[2026-08-09 19:47:16] 📌 [4/12] Competência 201304
[2026-08-09 19:47:16] 🔁 201304 | tentativa 1/3
[2026-08-09 19:47:16] ⬇️ Iniciando download temporário de 201304: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201304
[2026-08-09 19:47:16] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 380821
[2026-08-09 19:47:17] 📦 Arquivo recebido: 0.36 MB
[2026-08-09 19:47:17] ✅ ZIP válido recebido para 201304.
[2026-08-09 19:47:17] ✅ CSV salvo: 201304_CPGF.csv (4.52 MB)
[2026-08-09 19:47:17] 🧹 ZIP temporário apagado: 201304_CPGF.zip
[2026-08-09 19:47:17] 🎉 Competência concluída: 201304
[2026-08-09 19:47:17] 😴 Aguardando 38s antes da próxima requisição...
[2026-08-09 19:47:55] 📌 [5/12] Competência 201305
[2026-08-09 19:47:55] 🔁 201305 | tentativa 1/3
[2026-08-09 19:47:55] ⬇️ Iniciando download temporário de 201305: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201305
[2026-08-09 19:47:56] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 452757
[2026-08-09 19:47:56] 📦 Arquivo recebido: 0.43 MB
[2026-08-09 19:47:56] ✅ ZIP válido recebido para 201305.
[2026-08-09 19:47:56] ✅ CSV salvo: 201305_CPGF.csv (5.39 MB)
[2026-08-09 19:47:56] 🧹 ZIP temporário apagado: 201305_CPGF.zip
[2026-08-09 19:47:56] 🎉 Competência concluída: 201305
[2026-08-09 19:47:56] 😴 Aguardando 28s antes da próxima requisição...
[2026-08-09 19:48:24] 📌 [6/12] Competência 201306
[2026-08-09 19:48:24] 🔁 201306 | tentativa 1/3
[2026-08-09 19:48:24] ⬇️ Iniciando download temporário de 201306: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201306
[2026-08-09 19:48:25] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 347213
[2026-08-09 19:48:25] 📦 Arquivo recebido: 0.33 MB
[2026-08-09 19:48:25] ✅ ZIP válido recebido para 201306.
[2026-08-09 19:48:25] ✅ CSV salvo: 201306_CPGF.csv (4.28 MB)
[2026-08-09 19:48:25] 🧹 ZIP temporário apagado: 201306_CPGF.zip
[2026-08-09 19:48:25] 🎉 Competência concluída: 201306
[2026-08-09 19:48:25] 😴 Aguardando 31s antes da próxima requisição...
[2026-08-09 19:48:56] 📌 [7/12] Competência 201307
[2026-08-09 19:48:56] 🔁 201307 | tentativa 1/3
[2026-08-09 19:48:56] ⬇️ Iniciando download temporário de 201307: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201307
[2026-08-09 19:48:57] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 439361
[2026-08-09 19:48:58] 📦 Arquivo recebido: 0.42 MB
[2026-08-09 19:48:58] ✅ ZIP válido recebido para 201307.
[2026-08-09 19:48:58] ✅ CSV salvo: 201307_CPGF.csv (5.12 MB)
[2026-08-09 19:48:58] 🧹 ZIP temporário apagado: 201307_CPGF.zip
[2026-08-09 19:48:58] 🎉 Competência concluída: 201307
[2026-08-09 19:48:58] 😴 Aguardando 26s antes da próxima requisição...
[2026-08-09 19:49:24] 📌 [8/12] Competência 201308
[2026-08-09 19:49:24] 🔁 201308 | tentativa 1/3
[2026-08-09 19:49:24] ⬇️ Iniciando download temporário de 201308: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201308
[2026-08-09 19:49:25] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 437538
[2026-08-09 19:49:25] 📦 Arquivo recebido: 0.42 MB
[2026-08-09 19:49:25] ✅ ZIP válido recebido para 201308.
[2026-08-09 19:49:25] ✅ CSV salvo: 201308_CPGF.csv (5.18 MB)
[2026-08-09 19:49:25] 🧹 ZIP temporário apagado: 201308_CPGF.zip
[2026-08-09 19:49:25] 🎉 Competência concluída: 201308
[2026-08-09 19:49:25] 😴 Aguardando 43s antes da próxima requisição...
[2026-08-09 19:50:08] 📌 [9/12] Competência 201309
[2026-08-09 19:50:08] 🔁 201309 | tentativa 1/3
[2026-08-09 19:50:08] ⬇️ Iniciando download temporário de 201309: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201309
[2026-08-09 19:50:09] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 417240
[2026-08-09 19:50:09] 📦 Arquivo recebido: 0.40 MB
[2026-08-09 19:50:09] ✅ ZIP válido recebido para 201309.
[2026-08-09 19:50:10] ✅ CSV salvo: 201309_CPGF.csv (4.81 MB)
[2026-08-09 19:50:10] 🧹 ZIP temporário apagado: 201309_CPGF.zip
[2026-08-09 19:50:10] 🎉 Competência concluída: 201309
[2026-08-09 19:50:10] 😴 Aguardando 29s antes da próxima requisição...
[2026-08-09 19:50:39] 📌 [10/12] Competência 201310
[2026-08-09 19:50:39] 🔁 201310 | tentativa 1/3
[2026-08-09 19:50:39] ⬇️ Iniciando download temporário de 201310: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201310
[2026-08-09 19:50:39] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 426048
[2026-08-09 19:50:40] 📦 Arquivo recebido: 0.41 MB
[2026-08-09 19:50:40] ✅ ZIP válido recebido para 201310.
[2026-08-09 19:50:40] ✅ CSV salvo: 201310_CPGF.csv (5.01 MB)
[2026-08-09 19:50:40] 🧹 ZIP temporário apagado: 201310_CPGF.zip
[2026-08-09 19:50:40] 🎉 Competência concluída: 201310
[2026-08-09 19:50:40] 😴 Aguardando 31s antes da próxima requisição...
[2026-08-09 19:51:11] 📌 [11/12] Competência 201311
[2026-08-09 19:51:11] 🔁 201311 | tentativa 1/3
[2026-08-09 19:51:11] ⬇️ Iniciando download temporário de 201311: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201311
[2026-08-09 19:51:12] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 435378
[2026-08-09 19:51:12] 📦 Arquivo recebido: 0.42 MB
[2026-08-09 19:51:12] ✅ ZIP válido recebido para 201311.
[2026-08-09 19:51:12] ✅ CSV salvo: 201311_CPGF.csv (5.14 MB)
[2026-08-09 19:51:12] 🧹 ZIP temporário apagado: 201311_CPGF.zip
[2026-08-09 19:51:12] 🎉 Competência concluída: 201311
[2026-08-09 19:51:12] 😴 Aguardando 27s antes da próxima requisição...
[2026-08-09 19:51:39] 📌 [12/12] Competência 201312
[2026-08-09 19:51:39] 🔁 201312 | tentativa 1/3
[2026-08-09 19:51:39] ⬇️ Iniciando download temporário de 201312: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201312
[2026-08-09 19:51:40] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 432064
[2026-08-09 19:51:40] 📦 Arquivo recebido: 0.41 MB
[2026-08-09 19:51:40] ✅ ZIP válido recebido para 201312.
[2026-08-09 19:51:40] ✅ CSV salvo: 201312_CPGF.csv (5.16 MB)
[2026-08-09 19:51:40] 🧹 ZIP temporário apagado: 201312_CPGF.zip
[2026-08-09 19:51:40] 🎉 Competência concluída: 201312
[2026-08-09 19:51:40] 📊 Resumo do bloco: 12 concluída(s), 0 falha(s), 0 bloqueio(s).

{'concluidas': ['201301',
  '201302',
  '201303',
  '201304',
  '201305',
  '201306',
  '201307',
  '201308',
  '201309',
  '201310',
  '201311',
  '201312'],
 'falhas': [],
 'bloqueadas': []}

### 📦 2014 — janeiro a dezembro

Baixa as 12 competências de `201401` a `201412`.

In [7]:
executar_bloco('201401', '201412')

[2026-08-09 19:53:34] 🚀 Iniciando bloco 201401 a 201412 (12 competência(s)).
[2026-08-09 19:53:34] 📌 [1/12] Competência 201401
[2026-08-09 19:53:34] 🔁 201401 | tentativa 1/3
[2026-08-09 19:53:35] ⬇️ Iniciando download temporário de 201401: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201401
[2026-08-09 19:53:35] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 312694
[2026-08-09 19:53:36] 📦 Arquivo recebido: 0.30 MB
[2026-08-09 19:53:36] ✅ ZIP válido recebido para 201401.
[2026-08-09 19:53:36] ✅ CSV salvo: 201401_CPGF.csv (3.98 MB)
[2026-08-09 19:53:36] 🧹 ZIP temporário apagado: 201401_CPGF.zip
[2026-08-09 19:53:36] 🎉 Competência concluída: 201401
[2026-08-09 19:53:36] 😴 Aguardando 27s antes da próxima requisição...
[2026-08-09 19:54:03] 📌 [2/12] Competência 201402
[2026-08-09 19:54:03] 🔁 201402 | tentativa 1/3
[2026-08-09 19:54:03] ⬇️ Iniciando download temporário de 201402: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201402
[2026-08-09 19:54:03] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 70460
[2026-08-09 19:54:04] 📦 Arquivo recebido: 0.07 MB
[2026-08-09 19:54:04] ✅ ZIP válido recebido para 201402.
[2026-08-09 19:54:04] ✅ CSV salvo: 201402_CPGF.csv (0.73 MB)
[2026-08-09 19:54:04] 🧹 ZIP temporário apagado: 201402_CPGF.zip
[2026-08-09 19:54:04] 🎉 Competência concluída: 201402
[2026-08-09 19:54:04] 😴 Aguardando 44s antes da próxima requisição...
[2026-08-09 19:54:48] 📌 [3/12] Competência 201403
[2026-08-09 19:54:48] 🔁 201403 | tentativa 1/3
[2026-08-09 19:54:48] ⬇️ Iniciando download temporário de 201403: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201403
[2026-08-09 19:54:48] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 246693
[2026-08-09 19:54:49] 📦 Arquivo recebido: 0.24 MB
[2026-08-09 19:54:49] ✅ ZIP válido recebido para 201403.
[2026-08-09 19:54:49] ✅ CSV salvo: 201403_CPGF.csv (2.83 MB)
[2026-08-09 19:54:49] 🧹 ZIP temporário apagado: 201403_CPGF.zip
[2026-08-09 19:54:49] 🎉 Competência concluída: 201403
[2026-08-09 19:54:49] 😴 Aguardando 39s antes da próxima requisição...
[2026-08-09 19:55:28] 📌 [4/12] Competência 201404
[2026-08-09 19:55:28] 🔁 201404 | tentativa 1/3
[2026-08-09 19:55:28] ⬇️ Iniciando download temporário de 201404: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201404
[2026-08-09 19:55:29] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 325254
[2026-08-09 19:55:29] 📦 Arquivo recebido: 0.31 MB
[2026-08-09 19:55:29] ✅ ZIP válido recebido para 201404.
[2026-08-09 19:55:29] ✅ CSV salvo: 201404_CPGF.csv (3.82 MB)
[2026-08-09 19:55:29] 🧹 ZIP temporário apagado: 201404_CPGF.zip
[2026-08-09 19:55:29] 🎉 Competência concluída: 201404
[2026-08-09 19:55:29] 😴 Aguardando 39s antes da próxima requisição...
[2026-08-09 19:56:08] 📌 [5/12] Competência 201405
[2026-08-09 19:56:08] 🔁 201405 | tentativa 1/3
[2026-08-09 19:56:08] ⬇️ Iniciando download temporário de 201405: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201405
[2026-08-09 19:56:09] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 354520
[2026-08-09 19:56:09] 📦 Arquivo recebido: 0.34 MB
[2026-08-09 19:56:09] ✅ ZIP válido recebido para 201405.
[2026-08-09 19:56:09] ✅ CSV salvo: 201405_CPGF.csv (4.14 MB)
[2026-08-09 19:56:09] 🧹 ZIP temporário apagado: 201405_CPGF.zip
[2026-08-09 19:56:09] 🎉 Competência concluída: 201405
[2026-08-09 19:56:09] 😴 Aguardando 27s antes da próxima requisição...
[2026-08-09 19:56:36] 📌 [6/12] Competência 201406
[2026-08-09 19:56:36] 🔁 201406 | tentativa 1/3
[2026-08-09 19:56:36] ⬇️ Iniciando download temporário de 201406: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201406
[2026-08-09 19:56:37] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 376137
[2026-08-09 19:56:37] 📦 Arquivo recebido: 0.36 MB
[2026-08-09 19:56:37] ✅ ZIP válido recebido para 201406.
[2026-08-09 19:56:37] ✅ CSV salvo: 201406_CPGF.csv (4.49 MB)
[2026-08-09 19:56:37] 🧹 ZIP temporário apagado: 201406_CPGF.zip
[2026-08-09 19:56:37] 🎉 Competência concluída: 201406
[2026-08-09 19:56:37] 😴 Aguardando 43s antes da próxima requisição...
[2026-08-09 19:57:20] 📌 [7/12] Competência 201407
[2026-08-09 19:57:20] 🔁 201407 | tentativa 1/3
[2026-08-09 19:57:20] ⬇️ Iniciando download temporário de 201407: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201407
[2026-08-09 19:57:21] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 362934
[2026-08-09 19:57:22] 📦 Arquivo recebido: 0.35 MB
[2026-08-09 19:57:22] ✅ ZIP válido recebido para 201407.
[2026-08-09 19:57:22] ✅ CSV salvo: 201407_CPGF.csv (4.55 MB)
[2026-08-09 19:57:22] 🧹 ZIP temporário apagado: 201407_CPGF.zip
[2026-08-09 19:57:22] 🎉 Competência concluída: 201407
[2026-08-09 19:57:22] 😴 Aguardando 34s antes da próxima requisição...
[2026-08-09 19:57:56] 📌 [8/12] Competência 201408
[2026-08-09 19:57:56] 🔁 201408 | tentativa 1/3
[2026-08-09 19:57:56] ⬇️ Iniciando download temporário de 201408: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201408
[2026-08-09 19:57:56] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 336683
[2026-08-09 19:57:57] 📦 Arquivo recebido: 0.32 MB
[2026-08-09 19:57:57] ✅ ZIP válido recebido para 201408.
[2026-08-09 19:57:57] ✅ CSV salvo: 201408_CPGF.csv (4.01 MB)
[2026-08-09 19:57:57] 🧹 ZIP temporário apagado: 201408_CPGF.zip
[2026-08-09 19:57:57] 🎉 Competência concluída: 201408
[2026-08-09 19:57:57] 😴 Aguardando 26s antes da próxima requisição...
[2026-08-09 19:58:23] 📌 [9/12] Competência 201409
[2026-08-09 19:58:23] 🔁 201409 | tentativa 1/3
[2026-08-09 19:58:23] ⬇️ Iniciando download temporário de 201409: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201409
[2026-08-09 19:58:23] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 400137
[2026-08-09 19:58:24] 📦 Arquivo recebido: 0.38 MB
[2026-08-09 19:58:24] ✅ ZIP válido recebido para 201409.
[2026-08-09 19:58:24] ✅ CSV salvo: 201409_CPGF.csv (4.66 MB)
[2026-08-09 19:58:24] 🧹 ZIP temporário apagado: 201409_CPGF.zip
[2026-08-09 19:58:24] 🎉 Competência concluída: 201409
[2026-08-09 19:58:24] 😴 Aguardando 35s antes da próxima requisição...
[2026-08-09 19:58:59] 📌 [10/12] Competência 201410
[2026-08-09 19:58:59] 🔁 201410 | tentativa 1/3
[2026-08-09 19:58:59] ⬇️ Iniciando download temporário de 201410: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201410
[2026-08-09 19:59:00] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 391152
[2026-08-09 19:59:00] 📦 Arquivo recebido: 0.37 MB
[2026-08-09 19:59:00] ✅ ZIP válido recebido para 201410.
[2026-08-09 19:59:00] ✅ CSV salvo: 201410_CPGF.csv (4.52 MB)
[2026-08-09 19:59:00] 🧹 ZIP temporário apagado: 201410_CPGF.zip
[2026-08-09 19:59:00] 🎉 Competência concluída: 201410
[2026-08-09 19:59:00] 😴 Aguardando 45s antes da próxima requisição...
[2026-08-09 19:59:45] 📌 [11/12] Competência 201411
[2026-08-09 19:59:45] 🔁 201411 | tentativa 1/3
[2026-08-09 19:59:45] ⬇️ Iniciando download temporário de 201411: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201411
[2026-08-09 19:59:46] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 424654
[2026-08-09 19:59:46] 📦 Arquivo recebido: 0.40 MB
[2026-08-09 19:59:46] ✅ ZIP válido recebido para 201411.
[2026-08-09 19:59:47] ✅ CSV salvo: 201411_CPGF.csv (5.04 MB)
[2026-08-09 19:59:47] 🧹 ZIP temporário apagado: 201411_CPGF.zip
[2026-08-09 19:59:47] 🎉 Competência concluída: 201411
[2026-08-09 19:59:47] 😴 Aguardando 26s antes da próxima requisição...
[2026-08-09 20:00:13] 📌 [12/12] Competência 201412
[2026-08-09 20:00:13] 🔁 201412 | tentativa 1/3
[2026-08-09 20:00:13] ⬇️ Iniciando download temporário de 201412: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201412
[2026-08-09 20:00:13] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 437942
[2026-08-09 20:00:14] 📦 Arquivo recebido: 0.42 MB
[2026-08-09 20:00:14] ✅ ZIP válido recebido para 201412.
[2026-08-09 20:00:14] ✅ CSV salvo: 201412_CPGF.csv (5.24 MB)
[2026-08-09 20:00:14] 🧹 ZIP temporário apagado: 201412_CPGF.zip
[2026-08-09 20:00:14] 🎉 Competência concluída: 201412
[2026-08-09 20:00:14] 📊 Resumo do bloco: 12 concluída(s), 0 falha(s), 0 bloqueio(s).

{'concluidas': ['201401',
  '201402',
  '201403',
  '201404',
  '201405',
  '201406',
  '201407',
  '201408',
  '201409',
  '201410',
  '201411',
  '201412'],
 'falhas': [],
 'bloqueadas': []}

### 📦 2015 — janeiro a dezembro

Baixa as 12 competências de `201501` a `201512`.

In [8]:
executar_bloco('201501', '201512')

[2026-08-09 20:04:38] 🚀 Iniciando bloco 201501 a 201512 (12 competência(s)).
[2026-08-09 20:04:38] 📌 [1/12] Competência 201501
[2026-08-09 20:04:38] 🔁 201501 | tentativa 1/3
[2026-08-09 20:04:38] ⬇️ Iniciando download temporário de 201501: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201501
[2026-08-09 20:04:39] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 304912
[2026-08-09 20:04:40] 📦 Arquivo recebido: 0.29 MB
[2026-08-09 20:04:40] ✅ ZIP válido recebido para 201501.
[2026-08-09 20:04:40] ✅ CSV salvo: 201501_CPGF.csv (3.82 MB)
[2026-08-09 20:04:40] 🧹 ZIP temporário apagado: 201501_CPGF.zip
[2026-08-09 20:04:40] 🎉 Competência concluída: 201501
[2026-08-09 20:04:40] 😴 Aguardando 45s antes da próxima requisição...
[2026-08-09 20:05:25] 📌 [2/12] Competência 201502
[2026-08-09 20:05:25] 🔁 201502 | tentativa 1/3
[2026-08-09 20:05:25] ⬇️ Iniciando download temporário de 201502: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201502
[2026-08-09 20:05:25] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 41964
[2026-08-09 20:05:26] 📦 Arquivo recebido: 0.04 MB
[2026-08-09 20:05:26] ✅ ZIP válido recebido para 201502.
[2026-08-09 20:05:26] ✅ CSV salvo: 201502_CPGF.csv (0.48 MB)
[2026-08-09 20:05:26] 🧹 ZIP temporário apagado: 201502_CPGF.zip
[2026-08-09 20:05:26] 🎉 Competência concluída: 201502
[2026-08-09 20:05:26] 😴 Aguardando 26s antes da próxima requisição...
[2026-08-09 20:05:52] 📌 [3/12] Competência 201503
[2026-08-09 20:05:52] 🔁 201503 | tentativa 1/3
[2026-08-09 20:05:52] ⬇️ Iniciando download temporário de 201503: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201503
[2026-08-09 20:05:52] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 173678
[2026-08-09 20:05:53] 📦 Arquivo recebido: 0.17 MB
[2026-08-09 20:05:53] ✅ ZIP válido recebido para 201503.
[2026-08-09 20:05:53] ✅ CSV salvo: 201503_CPGF.csv (2.12 MB)
[2026-08-09 20:05:53] 🧹 ZIP temporário apagado: 201503_CPGF.zip
[2026-08-09 20:05:53] 🎉 Competência concluída: 201503
[2026-08-09 20:05:53] 😴 Aguardando 45s antes da próxima requisição...
[2026-08-09 20:06:38] 📌 [4/12] Competência 201504
[2026-08-09 20:06:38] 🔁 201504 | tentativa 1/3
[2026-08-09 20:06:38] ⬇️ Iniciando download temporário de 201504: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201504
[2026-08-09 20:06:38] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 300230
[2026-08-09 20:06:39] 📦 Arquivo recebido: 0.29 MB
[2026-08-09 20:06:39] ✅ ZIP válido recebido para 201504.
[2026-08-09 20:06:39] ✅ CSV salvo: 201504_CPGF.csv (3.90 MB)
[2026-08-09 20:06:39] 🧹 ZIP temporário apagado: 201504_CPGF.zip
[2026-08-09 20:06:39] 🎉 Competência concluída: 201504
[2026-08-09 20:06:39] 😴 Aguardando 42s antes da próxima requisição...
[2026-08-09 20:07:21] 📌 [5/12] Competência 201505
[2026-08-09 20:07:21] 🔁 201505 | tentativa 1/3
[2026-08-09 20:07:21] ⬇️ Iniciando download temporário de 201505: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201505
[2026-08-09 20:07:21] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 283112
[2026-08-09 20:07:22] 📦 Arquivo recebido: 0.27 MB
[2026-08-09 20:07:22] ✅ ZIP válido recebido para 201505.
[2026-08-09 20:07:22] ✅ CSV salvo: 201505_CPGF.csv (3.45 MB)
[2026-08-09 20:07:22] 🧹 ZIP temporário apagado: 201505_CPGF.zip
[2026-08-09 20:07:22] 🎉 Competência concluída: 201505
[2026-08-09 20:07:22] 😴 Aguardando 39s antes da próxima requisição...
[2026-08-09 20:08:01] 📌 [6/12] Competência 201506
[2026-08-09 20:08:01] 🔁 201506 | tentativa 1/3
[2026-08-09 20:08:01] ⬇️ Iniciando download temporário de 201506: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201506
[2026-08-09 20:08:01] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 328669
[2026-08-09 20:08:02] 📦 Arquivo recebido: 0.31 MB
[2026-08-09 20:08:02] ✅ ZIP válido recebido para 201506.
[2026-08-09 20:08:02] ✅ CSV salvo: 201506_CPGF.csv (3.92 MB)
[2026-08-09 20:08:02] 🧹 ZIP temporário apagado: 201506_CPGF.zip
[2026-08-09 20:08:02] 🎉 Competência concluída: 201506
[2026-08-09 20:08:02] 😴 Aguardando 27s antes da próxima requisição...
[2026-08-09 20:08:29] 📌 [7/12] Competência 201507
[2026-08-09 20:08:29] 🔁 201507 | tentativa 1/3
[2026-08-09 20:08:29] ⬇️ Iniciando download temporário de 201507: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201507
[2026-08-09 20:08:30] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 324856
[2026-08-09 20:08:30] 📦 Arquivo recebido: 0.31 MB
[2026-08-09 20:08:30] ✅ ZIP válido recebido para 201507.
[2026-08-09 20:08:30] ✅ CSV salvo: 201507_CPGF.csv (3.92 MB)
[2026-08-09 20:08:30] 🧹 ZIP temporário apagado: 201507_CPGF.zip
[2026-08-09 20:08:30] 🎉 Competência concluída: 201507
[2026-08-09 20:08:30] 😴 Aguardando 41s antes da próxima requisição...
[2026-08-09 20:09:11] 📌 [8/12] Competência 201508
[2026-08-09 20:09:11] 🔁 201508 | tentativa 1/3
[2026-08-09 20:09:11] ⬇️ Iniciando download temporário de 201508: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201508
[2026-08-09 20:09:12] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 304446
[2026-08-09 20:09:12] 📦 Arquivo recebido: 0.29 MB
[2026-08-09 20:09:12] ✅ ZIP válido recebido para 201508.
[2026-08-09 20:09:12] ✅ CSV salvo: 201508_CPGF.csv (3.65 MB)
[2026-08-09 20:09:12] 🧹 ZIP temporário apagado: 201508_CPGF.zip
[2026-08-09 20:09:12] 🎉 Competência concluída: 201508
[2026-08-09 20:09:12] 😴 Aguardando 31s antes da próxima requisição...
[2026-08-09 20:09:43] 📌 [9/12] Competência 201509
[2026-08-09 20:09:43] 🔁 201509 | tentativa 1/3
[2026-08-09 20:09:43] ⬇️ Iniciando download temporário de 201509: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201509
[2026-08-09 20:09:44] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 312303
[2026-08-09 20:09:45] 📦 Arquivo recebido: 0.30 MB
[2026-08-09 20:09:45] ✅ ZIP válido recebido para 201509.
[2026-08-09 20:09:45] ✅ CSV salvo: 201509_CPGF.csv (3.74 MB)
[2026-08-09 20:09:45] 🧹 ZIP temporário apagado: 201509_CPGF.zip
[2026-08-09 20:09:45] 🎉 Competência concluída: 201509
[2026-08-09 20:09:45] 😴 Aguardando 30s antes da próxima requisição...
[2026-08-09 20:10:15] 📌 [10/12] Competência 201510
[2026-08-09 20:10:15] 🔁 201510 | tentativa 1/3
[2026-08-09 20:10:15] ⬇️ Iniciando download temporário de 201510: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201510
[2026-08-09 20:10:15] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 311373
[2026-08-09 20:10:16] 📦 Arquivo recebido: 0.30 MB
[2026-08-09 20:10:16] ✅ ZIP válido recebido para 201510.
[2026-08-09 20:10:16] ✅ CSV salvo: 201510_CPGF.csv (3.60 MB)
[2026-08-09 20:10:16] 🧹 ZIP temporário apagado: 201510_CPGF.zip
[2026-08-09 20:10:16] 🎉 Competência concluída: 201510
[2026-08-09 20:10:16] 😴 Aguardando 39s antes da próxima requisição...
[2026-08-09 20:10:55] 📌 [11/12] Competência 201511
[2026-08-09 20:10:55] 🔁 201511 | tentativa 1/3
[2026-08-09 20:10:55] ⬇️ Iniciando download temporário de 201511: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201511
[2026-08-09 20:10:56] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 332016
[2026-08-09 20:10:56] 📦 Arquivo recebido: 0.32 MB
[2026-08-09 20:10:56] ✅ ZIP válido recebido para 201511.
[2026-08-09 20:10:56] ✅ CSV salvo: 201511_CPGF.csv (3.91 MB)
[2026-08-09 20:10:56] 🧹 ZIP temporário apagado: 201511_CPGF.zip
[2026-08-09 20:10:56] 🎉 Competência concluída: 201511
[2026-08-09 20:10:56] 😴 Aguardando 25s antes da próxima requisição...
[2026-08-09 20:11:21] 📌 [12/12] Competência 201512
[2026-08-09 20:11:21] 🔁 201512 | tentativa 1/3
[2026-08-09 20:11:21] ⬇️ Iniciando download temporário de 201512: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201512
[2026-08-09 20:11:22] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 355590
[2026-08-09 20:11:22] 📦 Arquivo recebido: 0.34 MB
[2026-08-09 20:11:22] ✅ ZIP válido recebido para 201512.
[2026-08-09 20:11:22] ✅ CSV salvo: 201512_CPGF.csv (4.32 MB)
[2026-08-09 20:11:22] 🧹 ZIP temporário apagado: 201512_CPGF.zip
[2026-08-09 20:11:22] 🎉 Competência concluída: 201512
[2026-08-09 20:11:22] 📊 Resumo do bloco: 12 concluída(s), 0 falha(s), 0 bloqueio(s).

{'concluidas': ['201501',
  '201502',
  '201503',
  '201504',
  '201505',
  '201506',
  '201507',
  '201508',
  '201509',
  '201510',
  '201511',
  '201512'],
 'falhas': [],
 'bloqueadas': []}

### 📦 2016 — janeiro a dezembro

Baixa as 12 competências de `201601` a `201612`.

In [9]:
executar_bloco('201601', '201612')

[2026-08-09 20:11:22] 🚀 Iniciando bloco 201601 a 201612 (12 competência(s)).
[2026-08-09 20:11:22] 📌 [1/12] Competência 201601
[2026-08-09 20:11:22] 🔁 201601 | tentativa 1/3
[2026-08-09 20:11:22] ⬇️ Iniciando download temporário de 201601: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201601
[2026-08-09 20:11:23] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 255850
[2026-08-09 20:11:23] 📦 Arquivo recebido: 0.24 MB
[2026-08-09 20:11:23] ✅ ZIP válido recebido para 201601.
[2026-08-09 20:11:23] ✅ CSV salvo: 201601_CPGF.csv (3.30 MB)
[2026-08-09 20:11:23] 🧹 ZIP temporário apagado: 201601_CPGF.zip
[2026-08-09 20:11:23] 🎉 Competência concluída: 201601
[2026-08-09 20:11:23] 😴 Aguardando 45s antes da próxima requisição...
[2026-08-09 20:12:08] 📌 [2/12] Competência 201602
[2026-08-09 20:12:08] 🔁 201602 | tentativa 1/3
[2026-08-09 20:12:08] ⬇️ Iniciando download temporário de 201602: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201602
[2026-08-09 20:12:09] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 37529
[2026-08-09 20:12:09] 📦 Arquivo recebido: 0.04 MB
[2026-08-09 20:12:09] ✅ ZIP válido recebido para 201602.
[2026-08-09 20:12:09] ✅ CSV salvo: 201602_CPGF.csv (0.43 MB)
[2026-08-09 20:12:09] 🧹 ZIP temporário apagado: 201602_CPGF.zip
[2026-08-09 20:12:09] 🎉 Competência concluída: 201602
[2026-08-09 20:12:09] 😴 Aguardando 36s antes da próxima requisição...
[2026-08-09 20:12:45] 📌 [3/12] Competência 201603
[2026-08-09 20:12:45] 🔁 201603 | tentativa 1/3
[2026-08-09 20:12:45] ⬇️ Iniciando download temporário de 201603: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201603
[2026-08-09 20:12:46] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 163462
[2026-08-09 20:12:47] 📦 Arquivo recebido: 0.16 MB
[2026-08-09 20:12:47] ✅ ZIP válido recebido para 201603.
[2026-08-09 20:12:47] ✅ CSV salvo: 201603_CPGF.csv (1.90 MB)
[2026-08-09 20:12:47] 🧹 ZIP temporário apagado: 201603_CPGF.zip
[2026-08-09 20:12:47] 🎉 Competência concluída: 201603
[2026-08-09 20:12:47] 😴 Aguardando 34s antes da próxima requisição...
[2026-08-09 20:13:21] 📌 [4/12] Competência 201604
[2026-08-09 20:13:21] 🔁 201604 | tentativa 1/3
[2026-08-09 20:13:21] ⬇️ Iniciando download temporário de 201604: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201604
[2026-08-09 20:13:21] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 295144
[2026-08-09 20:13:22] 📦 Arquivo recebido: 0.28 MB
[2026-08-09 20:13:22] ✅ ZIP válido recebido para 201604.
[2026-08-09 20:13:22] ✅ CSV salvo: 201604_CPGF.csv (3.57 MB)
[2026-08-09 20:13:22] 🧹 ZIP temporário apagado: 201604_CPGF.zip
[2026-08-09 20:13:22] 🎉 Competência concluída: 201604
[2026-08-09 20:13:22] 😴 Aguardando 34s antes da próxima requisição...
[2026-08-09 20:13:56] 📌 [5/12] Competência 201605
[2026-08-09 20:13:56] 🔁 201605 | tentativa 1/3
[2026-08-09 20:13:56] ⬇️ Iniciando download temporário de 201605: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201605
[2026-08-09 20:13:57] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 277313
[2026-08-09 20:13:57] 📦 Arquivo recebido: 0.26 MB
[2026-08-09 20:13:57] ✅ ZIP válido recebido para 201605.
[2026-08-09 20:13:57] ✅ CSV salvo: 201605_CPGF.csv (3.39 MB)
[2026-08-09 20:13:57] 🧹 ZIP temporário apagado: 201605_CPGF.zip
[2026-08-09 20:13:57] 🎉 Competência concluída: 201605
[2026-08-09 20:13:57] 😴 Aguardando 25s antes da próxima requisição...
[2026-08-09 20:14:22] 📌 [6/12] Competência 201606
[2026-08-09 20:14:22] 🔁 201606 | tentativa 1/3
[2026-08-09 20:14:22] ⬇️ Iniciando download temporário de 201606: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201606
[2026-08-09 20:14:23] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 305305
[2026-08-09 20:14:23] 📦 Arquivo recebido: 0.29 MB
[2026-08-09 20:14:23] ✅ ZIP válido recebido para 201606.
[2026-08-09 20:14:23] ✅ CSV salvo: 201606_CPGF.csv (3.67 MB)
[2026-08-09 20:14:23] 🧹 ZIP temporário apagado: 201606_CPGF.zip
[2026-08-09 20:14:23] 🎉 Competência concluída: 201606
[2026-08-09 20:14:23] 😴 Aguardando 29s antes da próxima requisição...
[2026-08-09 20:14:52] 📌 [7/12] Competência 201607
[2026-08-09 20:14:52] 🔁 201607 | tentativa 1/3
[2026-08-09 20:14:52] ⬇️ Iniciando download temporário de 201607: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201607
[2026-08-09 20:14:53] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 289844
[2026-08-09 20:14:54] 📦 Arquivo recebido: 0.28 MB
[2026-08-09 20:14:54] ✅ ZIP válido recebido para 201607.
[2026-08-09 20:14:54] ✅ CSV salvo: 201607_CPGF.csv (3.55 MB)
[2026-08-09 20:14:54] 🧹 ZIP temporário apagado: 201607_CPGF.zip
[2026-08-09 20:14:54] 🎉 Competência concluída: 201607
[2026-08-09 20:14:54] 😴 Aguardando 31s antes da próxima requisição...
[2026-08-09 20:15:25] 📌 [8/12] Competência 201608
[2026-08-09 20:15:25] 🔁 201608 | tentativa 1/3
[2026-08-09 20:15:25] ⬇️ Iniciando download temporário de 201608: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201608
[2026-08-09 20:15:26] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 290102
[2026-08-09 20:15:26] 📦 Arquivo recebido: 0.28 MB
[2026-08-09 20:15:26] ✅ ZIP válido recebido para 201608.
[2026-08-09 20:15:26] ✅ CSV salvo: 201608_CPGF.csv (3.55 MB)
[2026-08-09 20:15:26] 🧹 ZIP temporário apagado: 201608_CPGF.zip
[2026-08-09 20:15:26] 🎉 Competência concluída: 201608
[2026-08-09 20:15:26] 😴 Aguardando 26s antes da próxima requisição...
[2026-08-09 20:15:52] 📌 [9/12] Competência 201609
[2026-08-09 20:15:52] 🔁 201609 | tentativa 1/3
[2026-08-09 20:15:52] ⬇️ Iniciando download temporário de 201609: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201609
[2026-08-09 20:15:53] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 315312
[2026-08-09 20:15:53] 📦 Arquivo recebido: 0.30 MB
[2026-08-09 20:15:53] ✅ ZIP válido recebido para 201609.
[2026-08-09 20:15:53] ✅ CSV salvo: 201609_CPGF.csv (3.85 MB)
[2026-08-09 20:15:53] 🧹 ZIP temporário apagado: 201609_CPGF.zip
[2026-08-09 20:15:53] 🎉 Competência concluída: 201609
[2026-08-09 20:15:53] 😴 Aguardando 32s antes da próxima requisição...
[2026-08-09 20:16:25] 📌 [10/12] Competência 201610
[2026-08-09 20:16:25] 🔁 201610 | tentativa 1/3
[2026-08-09 20:16:25] ⬇️ Iniciando download temporário de 201610: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201610
[2026-08-09 20:16:26] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 292378
[2026-08-09 20:16:26] 📦 Arquivo recebido: 0.28 MB
[2026-08-09 20:16:26] ✅ ZIP válido recebido para 201610.
[2026-08-09 20:16:26] ✅ CSV salvo: 201610_CPGF.csv (3.36 MB)
[2026-08-09 20:16:26] 🧹 ZIP temporário apagado: 201610_CPGF.zip
[2026-08-09 20:16:26] 🎉 Competência concluída: 201610
[2026-08-09 20:16:26] 😴 Aguardando 28s antes da próxima requisição...
[2026-08-09 20:16:54] 📌 [11/12] Competência 201611
[2026-08-09 20:16:54] 🔁 201611 | tentativa 1/3
[2026-08-09 20:16:54] ⬇️ Iniciando download temporário de 201611: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201611
[2026-08-09 20:16:55] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 294329
[2026-08-09 20:16:55] 📦 Arquivo recebido: 0.28 MB
[2026-08-09 20:16:55] ✅ ZIP válido recebido para 201611.
[2026-08-09 20:16:56] ✅ CSV salvo: 201611_CPGF.csv (3.37 MB)
[2026-08-09 20:16:56] 🧹 ZIP temporário apagado: 201611_CPGF.zip
[2026-08-09 20:16:56] 🎉 Competência concluída: 201611
[2026-08-09 20:16:56] 😴 Aguardando 42s antes da próxima requisição...
[2026-08-09 20:17:38] 📌 [12/12] Competência 201612
[2026-08-09 20:17:38] 🔁 201612 | tentativa 1/3
[2026-08-09 20:17:38] ⬇️ Iniciando download temporário de 201612: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201612
[2026-08-09 20:17:38] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 308280
[2026-08-09 20:17:39] 📦 Arquivo recebido: 0.29 MB
[2026-08-09 20:17:39] ✅ ZIP válido recebido para 201612.
[2026-08-09 20:17:39] ✅ CSV salvo: 201612_CPGF.csv (3.66 MB)
[2026-08-09 20:17:39] 🧹 ZIP temporário apagado: 201612_CPGF.zip
[2026-08-09 20:17:39] 🎉 Competência concluída: 201612
[2026-08-09 20:17:39] 📊 Resumo do bloco: 12 concluída(s), 0 falha(s), 0 bloqueio(s).

{'concluidas': ['201601',
  '201602',
  '201603',
  '201604',
  '201605',
  '201606',
  '201607',
  '201608',
  '201609',
  '201610',
  '201611',
  '201612'],
 'falhas': [],
 'bloqueadas': []}

### 📦 2017 — janeiro a dezembro

Baixa as 12 competências de `201701` a `201712`.

In [10]:
executar_bloco('201701', '201712')

[2026-08-09 20:19:23] 🚀 Iniciando bloco 201701 a 201712 (12 competência(s)).
[2026-08-09 20:19:23] 📌 [1/12] Competência 201701
[2026-08-09 20:19:23] 🔁 201701 | tentativa 1/3
[2026-08-09 20:19:23] ⬇️ Iniciando download temporário de 201701: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201701
[2026-08-09 20:19:24] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 230477
[2026-08-09 20:19:25] 📦 Arquivo recebido: 0.22 MB
[2026-08-09 20:19:25] ✅ ZIP válido recebido para 201701.
[2026-08-09 20:19:25] ✅ CSV salvo: 201701_CPGF.csv (2.95 MB)
[2026-08-09 20:19:25] 🧹 ZIP temporário apagado: 201701_CPGF.zip
[2026-08-09 20:19:25] 🎉 Competência concluída: 201701
[2026-08-09 20:19:25] 😴 Aguardando 33s antes da próxima requisição...
[2026-08-09 20:19:58] 📌 [2/12] Competência 201702
[2026-08-09 20:19:58] 🔁 201702 | tentativa 1/3
[2026-08-09 20:19:58] ⬇️ Iniciando download temporário de 201702: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201702
[2026-08-09 20:19:59] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 39948
[2026-08-09 20:19:59] 📦 Arquivo recebido: 0.04 MB
[2026-08-09 20:19:59] ✅ ZIP válido recebido para 201702.
[2026-08-09 20:19:59] ✅ CSV salvo: 201702_CPGF.csv (0.43 MB)
[2026-08-09 20:19:59] 🧹 ZIP temporário apagado: 201702_CPGF.zip
[2026-08-09 20:19:59] 🎉 Competência concluída: 201702
[2026-08-09 20:19:59] 😴 Aguardando 39s antes da próxima requisição...
[2026-08-09 20:20:38] 📌 [3/12] Competência 201703
[2026-08-09 20:20:38] 🔁 201703 | tentativa 1/3
[2026-08-09 20:20:38] ⬇️ Iniciando download temporário de 201703: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201703
[2026-08-09 20:20:38] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 181303
[2026-08-09 20:20:39] 📦 Arquivo recebido: 0.17 MB
[2026-08-09 20:20:39] ✅ ZIP válido recebido para 201703.
[2026-08-09 20:20:39] ✅ CSV salvo: 201703_CPGF.csv (2.10 MB)
[2026-08-09 20:20:39] 🧹 ZIP temporário apagado: 201703_CPGF.zip
[2026-08-09 20:20:39] 🎉 Competência concluída: 201703
[2026-08-09 20:20:39] 😴 Aguardando 35s antes da próxima requisição...
[2026-08-09 20:21:14] 📌 [4/12] Competência 201704
[2026-08-09 20:21:14] 🔁 201704 | tentativa 1/3
[2026-08-09 20:21:14] ⬇️ Iniciando download temporário de 201704: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201704
[2026-08-09 20:21:15] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 265677
[2026-08-09 20:21:15] 📦 Arquivo recebido: 0.25 MB
[2026-08-09 20:21:15] ✅ ZIP válido recebido para 201704.
[2026-08-09 20:21:15] ✅ CSV salvo: 201704_CPGF.csv (3.20 MB)
[2026-08-09 20:21:15] 🧹 ZIP temporário apagado: 201704_CPGF.zip
[2026-08-09 20:21:15] 🎉 Competência concluída: 201704
[2026-08-09 20:21:15] 😴 Aguardando 40s antes da próxima requisição...
[2026-08-09 20:21:55] 📌 [5/12] Competência 201705
[2026-08-09 20:21:55] 🔁 201705 | tentativa 1/3
[2026-08-09 20:21:55] ⬇️ Iniciando download temporário de 201705: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201705
[2026-08-09 20:21:56] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 246208
[2026-08-09 20:21:56] 📦 Arquivo recebido: 0.23 MB
[2026-08-09 20:21:56] ✅ ZIP válido recebido para 201705.
[2026-08-09 20:21:56] ✅ CSV salvo: 201705_CPGF.csv (2.88 MB)
[2026-08-09 20:21:56] 🧹 ZIP temporário apagado: 201705_CPGF.zip
[2026-08-09 20:21:56] 🎉 Competência concluída: 201705
[2026-08-09 20:21:56] 😴 Aguardando 38s antes da próxima requisição...
[2026-08-09 20:22:34] 📌 [6/12] Competência 201706
[2026-08-09 20:22:34] 🔁 201706 | tentativa 1/3
[2026-08-09 20:22:34] ⬇️ Iniciando download temporário de 201706: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201706
[2026-08-09 20:22:35] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 293256
[2026-08-09 20:22:35] 📦 Arquivo recebido: 0.28 MB
[2026-08-09 20:22:35] ✅ ZIP válido recebido para 201706.
[2026-08-09 20:22:35] ✅ CSV salvo: 201706_CPGF.csv (3.51 MB)
[2026-08-09 20:22:35] 🧹 ZIP temporário apagado: 201706_CPGF.zip
[2026-08-09 20:22:35] 🎉 Competência concluída: 201706
[2026-08-09 20:22:35] 😴 Aguardando 39s antes da próxima requisição...
[2026-08-09 20:23:14] 📌 [7/12] Competência 201707
[2026-08-09 20:23:14] 🔁 201707 | tentativa 1/3
[2026-08-09 20:23:14] ⬇️ Iniciando download temporário de 201707: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201707
[2026-08-09 20:23:15] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 285633
[2026-08-09 20:23:16] 📦 Arquivo recebido: 0.27 MB
[2026-08-09 20:23:16] ✅ ZIP válido recebido para 201707.
[2026-08-09 20:23:16] ✅ CSV salvo: 201707_CPGF.csv (3.41 MB)
[2026-08-09 20:23:16] 🧹 ZIP temporário apagado: 201707_CPGF.zip
[2026-08-09 20:23:16] 🎉 Competência concluída: 201707
[2026-08-09 20:23:16] 😴 Aguardando 25s antes da próxima requisição...
[2026-08-09 20:23:41] 📌 [8/12] Competência 201708
[2026-08-09 20:23:41] 🔁 201708 | tentativa 1/3
[2026-08-09 20:23:41] ⬇️ Iniciando download temporário de 201708: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201708
[2026-08-09 20:23:42] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 263818
[2026-08-09 20:23:42] 📦 Arquivo recebido: 0.25 MB
[2026-08-09 20:23:42] ✅ ZIP válido recebido para 201708.
[2026-08-09 20:23:42] ✅ CSV salvo: 201708_CPGF.csv (3.10 MB)
[2026-08-09 20:23:42] 🧹 ZIP temporário apagado: 201708_CPGF.zip
[2026-08-09 20:23:42] 🎉 Competência concluída: 201708
[2026-08-09 20:23:42] 😴 Aguardando 29s antes da próxima requisição...
[2026-08-09 20:24:11] 📌 [9/12] Competência 201709
[2026-08-09 20:24:11] 🔁 201709 | tentativa 1/3
[2026-08-09 20:24:11] ⬇️ Iniciando download temporário de 201709: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201709
[2026-08-09 20:24:12] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 300210
[2026-08-09 20:24:12] 📦 Arquivo recebido: 0.29 MB
[2026-08-09 20:24:12] ✅ ZIP válido recebido para 201709.
[2026-08-09 20:24:12] ✅ CSV salvo: 201709_CPGF.csv (3.62 MB)
[2026-08-09 20:24:12] 🧹 ZIP temporário apagado: 201709_CPGF.zip
[2026-08-09 20:24:12] 🎉 Competência concluída: 201709
[2026-08-09 20:24:12] 😴 Aguardando 42s antes da próxima requisição...
[2026-08-09 20:24:54] 📌 [10/12] Competência 201710
[2026-08-09 20:24:54] 🔁 201710 | tentativa 1/3
[2026-08-09 20:24:54] ⬇️ Iniciando download temporário de 201710: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201710
[2026-08-09 20:24:55] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 299530
[2026-08-09 20:24:55] 📦 Arquivo recebido: 0.29 MB
[2026-08-09 20:24:55] ✅ ZIP válido recebido para 201710.
[2026-08-09 20:24:55] ✅ CSV salvo: 201710_CPGF.csv (3.62 MB)
[2026-08-09 20:24:55] 🧹 ZIP temporário apagado: 201710_CPGF.zip
[2026-08-09 20:24:55] 🎉 Competência concluída: 201710
[2026-08-09 20:24:55] 😴 Aguardando 32s antes da próxima requisição...
[2026-08-09 20:25:27] 📌 [11/12] Competência 201711
[2026-08-09 20:25:27] 🔁 201711 | tentativa 1/3
[2026-08-09 20:25:27] ⬇️ Iniciando download temporário de 201711: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201711
[2026-08-09 20:25:28] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 357204
[2026-08-09 20:25:28] 📦 Arquivo recebido: 0.34 MB
[2026-08-09 20:25:28] ✅ ZIP válido recebido para 201711.
[2026-08-09 20:25:28] ✅ CSV salvo: 201711_CPGF.csv (4.52 MB)
[2026-08-09 20:25:28] 🧹 ZIP temporário apagado: 201711_CPGF.zip
[2026-08-09 20:25:28] 🎉 Competência concluída: 201711
[2026-08-09 20:25:28] 😴 Aguardando 45s antes da próxima requisição...
[2026-08-09 20:26:13] 📌 [12/12] Competência 201712
[2026-08-09 20:26:13] 🔁 201712 | tentativa 1/3
[2026-08-09 20:26:13] ⬇️ Iniciando download temporário de 201712: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201712
[2026-08-09 20:26:14] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 379128
[2026-08-09 20:26:14] 📦 Arquivo recebido: 0.36 MB
[2026-08-09 20:26:14] ✅ ZIP válido recebido para 201712.
[2026-08-09 20:26:14] ✅ CSV salvo: 201712_CPGF.csv (4.98 MB)
[2026-08-09 20:26:14] 🧹 ZIP temporário apagado: 201712_CPGF.zip
[2026-08-09 20:26:14] 🎉 Competência concluída: 201712
[2026-08-09 20:26:14] 📊 Resumo do bloco: 12 concluída(s), 0 falha(s), 0 bloqueio(s).

{'concluidas': ['201701',
  '201702',
  '201703',
  '201704',
  '201705',
  '201706',
  '201707',
  '201708',
  '201709',
  '201710',
  '201711',
  '201712'],
 'falhas': [],
 'bloqueadas': []}

### 📦 2018 — janeiro a dezembro

Baixa as 12 competências de `201801` a `201812`.

In [11]:
executar_bloco('201801', '201812')

[2026-08-09 20:26:15] 🚀 Iniciando bloco 201801 a 201812 (12 competência(s)).
[2026-08-09 20:26:15] 📌 [1/12] Competência 201801
[2026-08-09 20:26:15] 🔁 201801 | tentativa 1/3
[2026-08-09 20:26:15] ⬇️ Iniciando download temporário de 201801: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201801
[2026-08-09 20:26:15] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 274964
[2026-08-09 20:26:16] 📦 Arquivo recebido: 0.26 MB
[2026-08-09 20:26:16] ✅ ZIP válido recebido para 201801.
[2026-08-09 20:26:16] ✅ CSV salvo: 201801_CPGF.csv (3.87 MB)
[2026-08-09 20:26:16] 🧹 ZIP temporário apagado: 201801_CPGF.zip
[2026-08-09 20:26:16] 🎉 Competência concluída: 201801
[2026-08-09 20:26:16] 😴 Aguardando 25s antes da próxima requisição...
[2026-08-09 20:26:41] 📌 [2/12] Competência 201802
[2026-08-09 20:26:41] 🔁 201802 | tentativa 1/3
[2026-08-09 20:26:41] ⬇️ Iniciando download temporário de 201802: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201802
[2026-08-09 20:26:42] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 112948
[2026-08-09 20:26:42] 📦 Arquivo recebido: 0.11 MB
[2026-08-09 20:26:42] ✅ ZIP válido recebido para 201802.
[2026-08-09 20:26:42] ✅ CSV salvo: 201802_CPGF.csv (1.54 MB)
[2026-08-09 20:26:42] 🧹 ZIP temporário apagado: 201802_CPGF.zip
[2026-08-09 20:26:42] 🎉 Competência concluída: 201802
[2026-08-09 20:26:42] 😴 Aguardando 32s antes da próxima requisição...
[2026-08-09 20:27:14] 📌 [3/12] Competência 201803
[2026-08-09 20:27:14] 🔁 201803 | tentativa 1/3
[2026-08-09 20:27:14] ⬇️ Iniciando download temporário de 201803: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201803
[2026-08-09 20:27:15] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 181415
[2026-08-09 20:27:15] 📦 Arquivo recebido: 0.17 MB
[2026-08-09 20:27:15] ✅ ZIP válido recebido para 201803.
[2026-08-09 20:27:15] ✅ CSV salvo: 201803_CPGF.csv (2.31 MB)
[2026-08-09 20:27:15] 🧹 ZIP temporário apagado: 201803_CPGF.zip
[2026-08-09 20:27:15] 🎉 Competência concluída: 201803
[2026-08-09 20:27:15] 😴 Aguardando 37s antes da próxima requisição...
[2026-08-09 20:27:52] 📌 [4/12] Competência 201804
[2026-08-09 20:27:52] 🔁 201804 | tentativa 1/3
[2026-08-09 20:27:52] ⬇️ Iniciando download temporário de 201804: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201804
[2026-08-09 20:27:53] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 297493
[2026-08-09 20:27:53] 📦 Arquivo recebido: 0.28 MB
[2026-08-09 20:27:53] ✅ ZIP válido recebido para 201804.
[2026-08-09 20:27:53] ✅ CSV salvo: 201804_CPGF.csv (3.87 MB)
[2026-08-09 20:27:53] 🧹 ZIP temporário apagado: 201804_CPGF.zip
[2026-08-09 20:27:53] 🎉 Competência concluída: 201804
[2026-08-09 20:27:53] 😴 Aguardando 44s antes da próxima requisição...
[2026-08-09 20:28:37] 📌 [5/12] Competência 201805
[2026-08-09 20:28:37] 🔁 201805 | tentativa 1/3
[2026-08-09 20:28:37] ⬇️ Iniciando download temporário de 201805: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201805
[2026-08-09 20:28:38] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 318509
[2026-08-09 20:28:38] 📦 Arquivo recebido: 0.30 MB
[2026-08-09 20:28:38] ✅ ZIP válido recebido para 201805.
[2026-08-09 20:28:38] ✅ CSV salvo: 201805_CPGF.csv (4.08 MB)
[2026-08-09 20:28:38] 🧹 ZIP temporário apagado: 201805_CPGF.zip
[2026-08-09 20:28:38] 🎉 Competência concluída: 201805
[2026-08-09 20:28:38] 😴 Aguardando 33s antes da próxima requisição...
[2026-08-09 20:29:11] 📌 [6/12] Competência 201806
[2026-08-09 20:29:11] 🔁 201806 | tentativa 1/3
[2026-08-09 20:29:11] ⬇️ Iniciando download temporário de 201806: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201806
[2026-08-09 20:29:12] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 296131
[2026-08-09 20:29:12] 📦 Arquivo recebido: 0.28 MB
[2026-08-09 20:29:12] ✅ ZIP válido recebido para 201806.
[2026-08-09 20:29:12] ✅ CSV salvo: 201806_CPGF.csv (3.64 MB)
[2026-08-09 20:29:12] 🧹 ZIP temporário apagado: 201806_CPGF.zip
[2026-08-09 20:29:12] 🎉 Competência concluída: 201806
[2026-08-09 20:29:12] 😴 Aguardando 26s antes da próxima requisição...
[2026-08-09 20:29:38] 📌 [7/12] Competência 201807
[2026-08-09 20:29:38] 🔁 201807 | tentativa 1/3
[2026-08-09 20:29:38] ⬇️ Iniciando download temporário de 201807: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201807
[2026-08-09 20:29:39] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 251435
[2026-08-09 20:29:40] 📦 Arquivo recebido: 0.24 MB
[2026-08-09 20:29:40] ✅ ZIP válido recebido para 201807.
[2026-08-09 20:29:40] ✅ CSV salvo: 201807_CPGF.csv (3.04 MB)
[2026-08-09 20:29:40] 🧹 ZIP temporário apagado: 201807_CPGF.zip
[2026-08-09 20:29:40] 🎉 Competência concluída: 201807
[2026-08-09 20:29:40] 😴 Aguardando 35s antes da próxima requisição...
[2026-08-09 20:30:15] 📌 [8/12] Competência 201808
[2026-08-09 20:30:15] 🔁 201808 | tentativa 1/3
[2026-08-09 20:30:15] ⬇️ Iniciando download temporário de 201808: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201808
[2026-08-09 20:30:15] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 238386
[2026-08-09 20:30:16] 📦 Arquivo recebido: 0.23 MB
[2026-08-09 20:30:16] ✅ ZIP válido recebido para 201808.
[2026-08-09 20:30:16] ✅ CSV salvo: 201808_CPGF.csv (2.82 MB)
[2026-08-09 20:30:16] 🧹 ZIP temporário apagado: 201808_CPGF.zip
[2026-08-09 20:30:16] 🎉 Competência concluída: 201808
[2026-08-09 20:30:16] 😴 Aguardando 32s antes da próxima requisição...
[2026-08-09 20:30:48] 📌 [9/12] Competência 201809
[2026-08-09 20:30:48] 🔁 201809 | tentativa 1/3
[2026-08-09 20:30:48] ⬇️ Iniciando download temporário de 201809: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201809
[2026-08-09 20:30:49] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 266203
[2026-08-09 20:30:49] 📦 Arquivo recebido: 0.25 MB
[2026-08-09 20:30:49] ✅ ZIP válido recebido para 201809.
[2026-08-09 20:30:49] ✅ CSV salvo: 201809_CPGF.csv (3.18 MB)
[2026-08-09 20:30:49] 🧹 ZIP temporário apagado: 201809_CPGF.zip
[2026-08-09 20:30:49] 🎉 Competência concluída: 201809
[2026-08-09 20:30:49] 😴 Aguardando 41s antes da próxima requisição...
[2026-08-09 20:31:30] 📌 [10/12] Competência 201810
[2026-08-09 20:31:30] 🔁 201810 | tentativa 1/3
[2026-08-09 20:31:30] ⬇️ Iniciando download temporário de 201810: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201810
[2026-08-09 20:31:31] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 256540
[2026-08-09 20:31:31] 📦 Arquivo recebido: 0.24 MB
[2026-08-09 20:31:31] ✅ ZIP válido recebido para 201810.
[2026-08-09 20:31:31] ✅ CSV salvo: 201810_CPGF.csv (3.11 MB)
[2026-08-09 20:31:31] 🧹 ZIP temporário apagado: 201810_CPGF.zip
[2026-08-09 20:31:31] 🎉 Competência concluída: 201810
[2026-08-09 20:31:31] 😴 Aguardando 38s antes da próxima requisição...
[2026-08-09 20:32:09] 📌 [11/12] Competência 201811
[2026-08-09 20:32:09] 🔁 201811 | tentativa 1/3
[2026-08-09 20:32:09] ⬇️ Iniciando download temporário de 201811: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201811
[2026-08-09 20:32:10] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 292631
[2026-08-09 20:32:10] 📦 Arquivo recebido: 0.28 MB
[2026-08-09 20:32:10] ✅ ZIP válido recebido para 201811.
[2026-08-09 20:32:10] ✅ CSV salvo: 201811_CPGF.csv (3.71 MB)
[2026-08-09 20:32:10] 🧹 ZIP temporário apagado: 201811_CPGF.zip
[2026-08-09 20:32:10] 🎉 Competência concluída: 201811
[2026-08-09 20:32:10] 😴 Aguardando 43s antes da próxima requisição...
[2026-08-09 20:32:53] 📌 [12/12] Competência 201812
[2026-08-09 20:32:53] 🔁 201812 | tentativa 1/3
[2026-08-09 20:32:53] ⬇️ Iniciando download temporário de 201812: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201812
[2026-08-09 20:32:54] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 292115
[2026-08-09 20:32:54] 📦 Arquivo recebido: 0.28 MB
[2026-08-09 20:32:54] ✅ ZIP válido recebido para 201812.
[2026-08-09 20:32:54] ✅ CSV salvo: 201812_CPGF.csv (3.77 MB)
[2026-08-09 20:32:54] 🧹 ZIP temporário apagado: 201812_CPGF.zip
[2026-08-09 20:32:54] 🎉 Competência concluída: 201812
[2026-08-09 20:32:54] 📊 Resumo do bloco: 12 concluída(s), 0 falha(s), 0 bloqueio(s).

{'concluidas': ['201801',
  '201802',
  '201803',
  '201804',
  '201805',
  '201806',
  '201807',
  '201808',
  '201809',
  '201810',
  '201811',
  '201812'],
 'falhas': [],
 'bloqueadas': []}

### 📦 2019 — janeiro a dezembro

Baixa as 12 competências de `201901` a `201912`.

In [12]:
executar_bloco('201901', '201912')

[2026-08-09 20:34:57] 🚀 Iniciando bloco 201901 a 201912 (12 competência(s)).
[2026-08-09 20:34:57] 📌 [1/12] Competência 201901
[2026-08-09 20:34:57] 🔁 201901 | tentativa 1/3
[2026-08-09 20:34:57] ⬇️ Iniciando download temporário de 201901: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201901
[2026-08-09 20:34:57] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 193477
[2026-08-09 20:34:58] 📦 Arquivo recebido: 0.18 MB
[2026-08-09 20:34:58] ✅ ZIP válido recebido para 201901.
[2026-08-09 20:34:58] ✅ CSV salvo: 201901_CPGF.csv (2.45 MB)
[2026-08-09 20:34:58] 🧹 ZIP temporário apagado: 201901_CPGF.zip
[2026-08-09 20:34:58] 🎉 Competência concluída: 201901
[2026-08-09 20:34:58] 😴 Aguardando 26s antes da próxima requisição...
[2026-08-09 20:35:24] 📌 [2/12] Competência 201902
[2026-08-09 20:35:24] 🔁 201902 | tentativa 1/3
[2026-08-09 20:35:24] ⬇️ Iniciando download temporário de 201902: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201902
[2026-08-09 20:35:24] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 45147
[2026-08-09 20:35:24] 📦 Arquivo recebido: 0.04 MB
[2026-08-09 20:35:24] ✅ ZIP válido recebido para 201902.
[2026-08-09 20:35:24] ✅ CSV salvo: 201902_CPGF.csv (0.52 MB)
[2026-08-09 20:35:25] 🧹 ZIP temporário apagado: 201902_CPGF.zip
[2026-08-09 20:35:25] 🎉 Competência concluída: 201902
[2026-08-09 20:35:25] 😴 Aguardando 30s antes da próxima requisição...
[2026-08-09 20:35:55] 📌 [3/12] Competência 201903
[2026-08-09 20:35:55] 🔁 201903 | tentativa 1/3
[2026-08-09 20:35:55] ⬇️ Iniciando download temporário de 201903: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201903
[2026-08-09 20:35:55] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 159591
[2026-08-09 20:35:56] 📦 Arquivo recebido: 0.15 MB
[2026-08-09 20:35:56] ✅ ZIP válido recebido para 201903.
[2026-08-09 20:35:56] ✅ CSV salvo: 201903_CPGF.csv (1.93 MB)
[2026-08-09 20:35:56] 🧹 ZIP temporário apagado: 201903_CPGF.zip
[2026-08-09 20:35:56] 🎉 Competência concluída: 201903
[2026-08-09 20:35:56] 😴 Aguardando 41s antes da próxima requisição...
[2026-08-09 20:36:37] 📌 [4/12] Competência 201904
[2026-08-09 20:36:37] 🔁 201904 | tentativa 1/3
[2026-08-09 20:36:37] ⬇️ Iniciando download temporário de 201904: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201904
[2026-08-09 20:36:38] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 183819
[2026-08-09 20:36:38] 📦 Arquivo recebido: 0.18 MB
[2026-08-09 20:36:38] ✅ ZIP válido recebido para 201904.
[2026-08-09 20:36:38] ✅ CSV salvo: 201904_CPGF.csv (2.25 MB)
[2026-08-09 20:36:38] 🧹 ZIP temporário apagado: 201904_CPGF.zip
[2026-08-09 20:36:38] 🎉 Competência concluída: 201904
[2026-08-09 20:36:38] 😴 Aguardando 39s antes da próxima requisição...
[2026-08-09 20:37:17] 📌 [5/12] Competência 201905
[2026-08-09 20:37:17] 🔁 201905 | tentativa 1/3
[2026-08-09 20:37:17] ⬇️ Iniciando download temporário de 201905: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201905
[2026-08-09 20:37:18] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 238766
[2026-08-09 20:37:18] 📦 Arquivo recebido: 0.23 MB
[2026-08-09 20:37:18] ✅ ZIP válido recebido para 201905.
[2026-08-09 20:37:18] ✅ CSV salvo: 201905_CPGF.csv (2.93 MB)
[2026-08-09 20:37:18] 🧹 ZIP temporário apagado: 201905_CPGF.zip
[2026-08-09 20:37:18] 🎉 Competência concluída: 201905
[2026-08-09 20:37:18] 😴 Aguardando 26s antes da próxima requisição...
[2026-08-09 20:37:44] 📌 [6/12] Competência 201906
[2026-08-09 20:37:44] 🔁 201906 | tentativa 1/3
[2026-08-09 20:37:44] ⬇️ Iniciando download temporário de 201906: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201906
[2026-08-09 20:37:45] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 247281
[2026-08-09 20:37:45] 📦 Arquivo recebido: 0.24 MB
[2026-08-09 20:37:45] ✅ ZIP válido recebido para 201906.
[2026-08-09 20:37:45] ✅ CSV salvo: 201906_CPGF.csv (3.14 MB)
[2026-08-09 20:37:45] 🧹 ZIP temporário apagado: 201906_CPGF.zip
[2026-08-09 20:37:45] 🎉 Competência concluída: 201906
[2026-08-09 20:37:45] 😴 Aguardando 26s antes da próxima requisição...
[2026-08-09 20:38:11] 📌 [7/12] Competência 201907
[2026-08-09 20:38:11] 🔁 201907 | tentativa 1/3
[2026-08-09 20:38:11] ⬇️ Iniciando download temporário de 201907: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201907
[2026-08-09 20:38:12] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 215051
[2026-08-09 20:38:13] 📦 Arquivo recebido: 0.21 MB
[2026-08-09 20:38:13] ✅ ZIP válido recebido para 201907.
[2026-08-09 20:38:13] ✅ CSV salvo: 201907_CPGF.csv (2.67 MB)
[2026-08-09 20:38:13] 🧹 ZIP temporário apagado: 201907_CPGF.zip
[2026-08-09 20:38:13] 🎉 Competência concluída: 201907
[2026-08-09 20:38:13] 😴 Aguardando 33s antes da próxima requisição...
[2026-08-09 20:38:46] 📌 [8/12] Competência 201908
[2026-08-09 20:38:46] 🔁 201908 | tentativa 1/3
[2026-08-09 20:38:46] ⬇️ Iniciando download temporário de 201908: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201908
[2026-08-09 20:38:46] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 230791
[2026-08-09 20:38:47] 📦 Arquivo recebido: 0.22 MB
[2026-08-09 20:38:47] ✅ ZIP válido recebido para 201908.
[2026-08-09 20:38:47] ✅ CSV salvo: 201908_CPGF.csv (2.89 MB)
[2026-08-09 20:38:47] 🧹 ZIP temporário apagado: 201908_CPGF.zip
[2026-08-09 20:38:47] 🎉 Competência concluída: 201908
[2026-08-09 20:38:47] 😴 Aguardando 37s antes da próxima requisição...
[2026-08-09 20:39:24] 📌 [9/12] Competência 201909
[2026-08-09 20:39:24] 🔁 201909 | tentativa 1/3
[2026-08-09 20:39:24] ⬇️ Iniciando download temporário de 201909: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201909
[2026-08-09 20:39:24] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 223505
[2026-08-09 20:39:25] 📦 Arquivo recebido: 0.21 MB
[2026-08-09 20:39:25] ✅ ZIP válido recebido para 201909.
[2026-08-09 20:39:25] ✅ CSV salvo: 201909_CPGF.csv (2.75 MB)
[2026-08-09 20:39:25] 🧹 ZIP temporário apagado: 201909_CPGF.zip
[2026-08-09 20:39:25] 🎉 Competência concluída: 201909
[2026-08-09 20:39:25] 😴 Aguardando 44s antes da próxima requisição...
[2026-08-09 20:40:09] 📌 [10/12] Competência 201910
[2026-08-09 20:40:09] 🔁 201910 | tentativa 1/3
[2026-08-09 20:40:09] ⬇️ Iniciando download temporário de 201910: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201910
[2026-08-09 20:40:10] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 230870
[2026-08-09 20:40:10] 📦 Arquivo recebido: 0.22 MB
[2026-08-09 20:40:10] ✅ ZIP válido recebido para 201910.
[2026-08-09 20:40:10] ✅ CSV salvo: 201910_CPGF.csv (2.84 MB)
[2026-08-09 20:40:10] 🧹 ZIP temporário apagado: 201910_CPGF.zip
[2026-08-09 20:40:10] 🎉 Competência concluída: 201910
[2026-08-09 20:40:10] 😴 Aguardando 26s antes da próxima requisição...
[2026-08-09 20:40:36] 📌 [11/12] Competência 201911
[2026-08-09 20:40:36] 🔁 201911 | tentativa 1/3
[2026-08-09 20:40:36] ⬇️ Iniciando download temporário de 201911: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201911
[2026-08-09 20:40:37] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 254698
[2026-08-09 20:40:37] 📦 Arquivo recebido: 0.24 MB
[2026-08-09 20:40:37] ✅ ZIP válido recebido para 201911.
[2026-08-09 20:40:37] ✅ CSV salvo: 201911_CPGF.csv (3.26 MB)
[2026-08-09 20:40:37] 🧹 ZIP temporário apagado: 201911_CPGF.zip
[2026-08-09 20:40:37] 🎉 Competência concluída: 201911
[2026-08-09 20:40:37] 😴 Aguardando 44s antes da próxima requisição...
[2026-08-09 20:41:21] 📌 [12/12] Competência 201912
[2026-08-09 20:41:21] 🔁 201912 | tentativa 1/3
[2026-08-09 20:41:21] ⬇️ Iniciando download temporário de 201912: https://portaldatransparencia.gov.br/download-de-dados/cpgf/201912
[2026-08-09 20:41:22] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 260974
[2026-08-09 20:41:23] 📦 Arquivo recebido: 0.25 MB
[2026-08-09 20:41:23] ✅ ZIP válido recebido para 201912.
[2026-08-09 20:41:23] ✅ CSV salvo: 201912_CPGF.csv (3.32 MB)
[2026-08-09 20:41:23] 🧹 ZIP temporário apagado: 201912_CPGF.zip
[2026-08-09 20:41:23] 🎉 Competência concluída: 201912
[2026-08-09 20:41:23] 📊 Resumo do bloco: 12 concluída(s), 0 falha(s), 0 bloqueio(s).

{'concluidas': ['201901',
  '201902',
  '201903',
  '201904',
  '201905',
  '201906',
  '201907',
  '201908',
  '201909',
  '201910',
  '201911',
  '201912'],
 'falhas': [],
 'bloqueadas': []}

### 📦 2020 — janeiro a dezembro

Baixa as 12 competências de `202001` a `202012`.

In [13]:
executar_bloco('202001', '202012')

[2026-08-09 20:41:23] 🚀 Iniciando bloco 202001 a 202012 (12 competência(s)).
[2026-08-09 20:41:23] 📌 [1/12] Competência 202001
[2026-08-09 20:41:23] 🔁 202001 | tentativa 1/3
[2026-08-09 20:41:23] ⬇️ Iniciando download temporário de 202001: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202001
[2026-08-09 20:41:24] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 169298
[2026-08-09 20:41:24] 📦 Arquivo recebido: 0.16 MB
[2026-08-09 20:41:24] ✅ ZIP válido recebido para 202001.
[2026-08-09 20:41:24] ✅ CSV salvo: 202001_CPGF.csv (2.20 MB)
[2026-08-09 20:41:24] 🧹 ZIP temporário apagado: 202001_CPGF.zip
[2026-08-09 20:41:24] 🎉 Competência concluída: 202001
[2026-08-09 20:41:24] 😴 Aguardando 32s antes da próxima requisição...
[2026-08-09 20:41:56] 📌 [2/12] Competência 202002
[2026-08-09 20:41:56] 🔁 202002 | tentativa 1/3
[2026-08-09 20:41:56] ⬇️ Iniciando download temporário de 202002: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202002
[2026-08-09 20:41:57] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 37492
[2026-08-09 20:41:57] 📦 Arquivo recebido: 0.04 MB
[2026-08-09 20:41:57] ✅ ZIP válido recebido para 202002.
[2026-08-09 20:41:57] ✅ CSV salvo: 202002_CPGF.csv (0.46 MB)
[2026-08-09 20:41:57] 🧹 ZIP temporário apagado: 202002_CPGF.zip
[2026-08-09 20:41:57] 🎉 Competência concluída: 202002
[2026-08-09 20:41:57] 😴 Aguardando 40s antes da próxima requisição...
[2026-08-09 20:42:37] 📌 [3/12] Competência 202003
[2026-08-09 20:42:37] 🔁 202003 | tentativa 1/3
[2026-08-09 20:42:37] ⬇️ Iniciando download temporário de 202003: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202003
[2026-08-09 20:42:38] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 125614
[2026-08-09 20:42:38] 📦 Arquivo recebido: 0.12 MB
[2026-08-09 20:42:38] ✅ ZIP válido recebido para 202003.
[2026-08-09 20:42:38] ✅ CSV salvo: 202003_CPGF.csv (1.53 MB)
[2026-08-09 20:42:38] 🧹 ZIP temporário apagado: 202003_CPGF.zip
[2026-08-09 20:42:38] 🎉 Competência concluída: 202003
[2026-08-09 20:42:38] 😴 Aguardando 42s antes da próxima requisição...
[2026-08-09 20:43:20] 📌 [4/12] Competência 202004
[2026-08-09 20:43:20] 🔁 202004 | tentativa 1/3
[2026-08-09 20:43:20] ⬇️ Iniciando download temporário de 202004: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202004
[2026-08-09 20:43:21] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 174304
[2026-08-09 20:43:21] 📦 Arquivo recebido: 0.17 MB
[2026-08-09 20:43:21] ✅ ZIP válido recebido para 202004.
[2026-08-09 20:43:21] ✅ CSV salvo: 202004_CPGF.csv (2.09 MB)
[2026-08-09 20:43:21] 🧹 ZIP temporário apagado: 202004_CPGF.zip
[2026-08-09 20:43:21] 🎉 Competência concluída: 202004
[2026-08-09 20:43:21] 😴 Aguardando 40s antes da próxima requisição...
[2026-08-09 20:44:01] 📌 [5/12] Competência 202005
[2026-08-09 20:44:01] 🔁 202005 | tentativa 1/3
[2026-08-09 20:44:01] ⬇️ Iniciando download temporário de 202005: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202005
[2026-08-09 20:44:02] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 93355
[2026-08-09 20:44:02] 📦 Arquivo recebido: 0.09 MB
[2026-08-09 20:44:02] ✅ ZIP válido recebido para 202005.
[2026-08-09 20:44:02] ✅ CSV salvo: 202005_CPGF.csv (1.16 MB)
[2026-08-09 20:44:02] 🧹 ZIP temporário apagado: 202005_CPGF.zip
[2026-08-09 20:44:02] 🎉 Competência concluída: 202005
[2026-08-09 20:44:02] 😴 Aguardando 40s antes da próxima requisição...
[2026-08-09 20:44:42] 📌 [6/12] Competência 202006
[2026-08-09 20:44:42] 🔁 202006 | tentativa 1/3
[2026-08-09 20:44:42] ⬇️ Iniciando download temporário de 202006: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202006
[2026-08-09 20:44:43] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 127345
[2026-08-09 20:44:43] 📦 Arquivo recebido: 0.12 MB
[2026-08-09 20:44:43] ✅ ZIP válido recebido para 202006.
[2026-08-09 20:44:43] ✅ CSV salvo: 202006_CPGF.csv (1.66 MB)
[2026-08-09 20:44:43] 🧹 ZIP temporário apagado: 202006_CPGF.zip
[2026-08-09 20:44:43] 🎉 Competência concluída: 202006
[2026-08-09 20:44:43] 😴 Aguardando 43s antes da próxima requisição...
[2026-08-09 20:45:26] 📌 [7/12] Competência 202007
[2026-08-09 20:45:26] 🔁 202007 | tentativa 1/3
[2026-08-09 20:45:26] ⬇️ Iniciando download temporário de 202007: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202007
[2026-08-09 20:45:27] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 122754
[2026-08-09 20:45:27] 📦 Arquivo recebido: 0.12 MB
[2026-08-09 20:45:27] ✅ ZIP válido recebido para 202007.
[2026-08-09 20:45:27] ✅ CSV salvo: 202007_CPGF.csv (1.55 MB)
[2026-08-09 20:45:27] 🧹 ZIP temporário apagado: 202007_CPGF.zip
[2026-08-09 20:45:27] 🎉 Competência concluída: 202007
[2026-08-09 20:45:27] 😴 Aguardando 43s antes da próxima requisição...
[2026-08-09 20:46:10] 📌 [8/12] Competência 202008
[2026-08-09 20:46:10] 🔁 202008 | tentativa 1/3
[2026-08-09 20:46:10] ⬇️ Iniciando download temporário de 202008: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202008
[2026-08-09 20:46:11] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 122683
[2026-08-09 20:46:11] 📦 Arquivo recebido: 0.12 MB
[2026-08-09 20:46:11] ✅ ZIP válido recebido para 202008.
[2026-08-09 20:46:11] ✅ CSV salvo: 202008_CPGF.csv (1.61 MB)
[2026-08-09 20:46:11] 🧹 ZIP temporário apagado: 202008_CPGF.zip
[2026-08-09 20:46:11] 🎉 Competência concluída: 202008
[2026-08-09 20:46:11] 😴 Aguardando 26s antes da próxima requisição...
[2026-08-09 20:46:37] 📌 [9/12] Competência 202009
[2026-08-09 20:46:37] 🔁 202009 | tentativa 1/3
[2026-08-09 20:46:37] ⬇️ Iniciando download temporário de 202009: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202009
[2026-08-09 20:46:38] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 144044
[2026-08-09 20:46:38] 📦 Arquivo recebido: 0.14 MB
[2026-08-09 20:46:38] ✅ ZIP válido recebido para 202009.
[2026-08-09 20:46:38] ✅ CSV salvo: 202009_CPGF.csv (1.86 MB)
[2026-08-09 20:46:38] 🧹 ZIP temporário apagado: 202009_CPGF.zip
[2026-08-09 20:46:38] 🎉 Competência concluída: 202009
[2026-08-09 20:46:38] 😴 Aguardando 35s antes da próxima requisição...
[2026-08-09 20:47:13] 📌 [10/12] Competência 202010
[2026-08-09 20:47:13] 🔁 202010 | tentativa 1/3
[2026-08-09 20:47:13] ⬇️ Iniciando download temporário de 202010: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202010
[2026-08-09 20:47:14] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 162225
[2026-08-09 20:47:14] 📦 Arquivo recebido: 0.15 MB
[2026-08-09 20:47:14] ✅ ZIP válido recebido para 202010.
[2026-08-09 20:47:14] ✅ CSV salvo: 202010_CPGF.csv (2.00 MB)
[2026-08-09 20:47:14] 🧹 ZIP temporário apagado: 202010_CPGF.zip
[2026-08-09 20:47:14] 🎉 Competência concluída: 202010
[2026-08-09 20:47:14] 😴 Aguardando 31s antes da próxima requisição...
[2026-08-09 20:47:45] 📌 [11/12] Competência 202011
[2026-08-09 20:47:45] 🔁 202011 | tentativa 1/3
[2026-08-09 20:47:45] ⬇️ Iniciando download temporário de 202011: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202011
[2026-08-09 20:47:46] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 181582
[2026-08-09 20:47:47] 📦 Arquivo recebido: 0.17 MB
[2026-08-09 20:47:47] ✅ ZIP válido recebido para 202011.
[2026-08-09 20:47:47] ✅ CSV salvo: 202011_CPGF.csv (2.30 MB)
[2026-08-09 20:47:47] 🧹 ZIP temporário apagado: 202011_CPGF.zip
[2026-08-09 20:47:47] 🎉 Competência concluída: 202011
[2026-08-09 20:47:47] 😴 Aguardando 43s antes da próxima requisição...
[2026-08-09 20:48:30] 📌 [12/12] Competência 202012
[2026-08-09 20:48:30] 🔁 202012 | tentativa 1/3
[2026-08-09 20:48:30] ⬇️ Iniciando download temporário de 202012: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202012
[2026-08-09 20:48:31] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 213004
[2026-08-09 20:48:31] 📦 Arquivo recebido: 0.20 MB
[2026-08-09 20:48:31] ✅ ZIP válido recebido para 202012.
[2026-08-09 20:48:31] ✅ CSV salvo: 202012_CPGF.csv (2.69 MB)
[2026-08-09 20:48:31] 🧹 ZIP temporário apagado: 202012_CPGF.zip
[2026-08-09 20:48:31] 🎉 Competência concluída: 202012
[2026-08-09 20:48:31] 📊 Resumo do bloco: 12 concluída(s), 0 falha(s), 0 bloqueio(s).

{'concluidas': ['202001',
  '202002',
  '202003',
  '202004',
  '202005',
  '202006',
  '202007',
  '202008',
  '202009',
  '202010',
  '202011',
  '202012'],
 'falhas': [],
 'bloqueadas': []}

### 📦 2021 — janeiro a dezembro

Baixa as 12 competências de `202101` a `202112`.

In [14]:
executar_bloco('202101', '202112')

[2026-08-09 20:49:37] 🚀 Iniciando bloco 202101 a 202112 (12 competência(s)).
[2026-08-09 20:49:37] 📌 [1/12] Competência 202101
[2026-08-09 20:49:37] 🔁 202101 | tentativa 1/3
[2026-08-09 20:49:37] ⬇️ Iniciando download temporário de 202101: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202101
[2026-08-09 20:49:37] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 148489
[2026-08-09 20:49:38] 📦 Arquivo recebido: 0.14 MB
[2026-08-09 20:49:38] ✅ ZIP válido recebido para 202101.
[2026-08-09 20:49:38] ✅ CSV salvo: 202101_CPGF.csv (1.87 MB)
[2026-08-09 20:49:38] 🧹 ZIP temporário apagado: 202101_CPGF.zip
[2026-08-09 20:49:38] 🎉 Competência concluída: 202101
[2026-08-09 20:49:38] 😴 Aguardando 25s antes da próxima requisição...
[2026-08-09 20:50:03] 📌 [2/12] Competência 202102
[2026-08-09 20:50:03] 🔁 202102 | tentativa 1/3
[2026-08-09 20:50:03] ⬇️ Iniciando download temporário de 202102: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202102
[2026-08-09 20:50:03] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 22943
[2026-08-09 20:50:03] 📦 Arquivo recebido: 0.02 MB
[2026-08-09 20:50:03] ✅ ZIP válido recebido para 202102.
[2026-08-09 20:50:03] ✅ CSV salvo: 202102_CPGF.csv (0.29 MB)
[2026-08-09 20:50:03] 🧹 ZIP temporário apagado: 202102_CPGF.zip
[2026-08-09 20:50:03] 🎉 Competência concluída: 202102
[2026-08-09 20:50:03] 😴 Aguardando 28s antes da próxima requisição...
[2026-08-09 20:50:31] 📌 [3/12] Competência 202103
[2026-08-09 20:50:31] 🔁 202103 | tentativa 1/3
[2026-08-09 20:50:31] ⬇️ Iniciando download temporário de 202103: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202103
[2026-08-09 20:50:32] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 71973
[2026-08-09 20:50:33] 📦 Arquivo recebido: 0.07 MB
[2026-08-09 20:50:33] ✅ ZIP válido recebido para 202103.
[2026-08-09 20:50:33] ✅ CSV salvo: 202103_CPGF.csv (0.93 MB)
[2026-08-09 20:50:33] 🧹 ZIP temporário apagado: 202103_CPGF.zip
[2026-08-09 20:50:33] 🎉 Competência concluída: 202103
[2026-08-09 20:50:33] 😴 Aguardando 44s antes da próxima requisição...
[2026-08-09 20:51:17] 📌 [4/12] Competência 202104
[2026-08-09 20:51:17] 🔁 202104 | tentativa 1/3
[2026-08-09 20:51:17] ⬇️ Iniciando download temporário de 202104: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202104
[2026-08-09 20:51:18] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 121422
[2026-08-09 20:51:18] 📦 Arquivo recebido: 0.12 MB
[2026-08-09 20:51:18] ✅ ZIP válido recebido para 202104.
[2026-08-09 20:51:18] ✅ CSV salvo: 202104_CPGF.csv (1.53 MB)
[2026-08-09 20:51:18] 🧹 ZIP temporário apagado: 202104_CPGF.zip
[2026-08-09 20:51:18] 🎉 Competência concluída: 202104
[2026-08-09 20:51:18] 😴 Aguardando 43s antes da próxima requisição...
[2026-08-09 20:52:01] 📌 [5/12] Competência 202105
[2026-08-09 20:52:01] 🔁 202105 | tentativa 1/3
[2026-08-09 20:52:01] ⬇️ Iniciando download temporário de 202105: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202105
[2026-08-09 20:52:02] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 117864
[2026-08-09 20:52:02] 📦 Arquivo recebido: 0.11 MB
[2026-08-09 20:52:02] ✅ ZIP válido recebido para 202105.
[2026-08-09 20:52:02] ✅ CSV salvo: 202105_CPGF.csv (1.47 MB)
[2026-08-09 20:52:02] 🧹 ZIP temporário apagado: 202105_CPGF.zip
[2026-08-09 20:52:02] 🎉 Competência concluída: 202105
[2026-08-09 20:52:02] 😴 Aguardando 35s antes da próxima requisição...
[2026-08-09 20:52:37] 📌 [6/12] Competência 202106
[2026-08-09 20:52:37] 🔁 202106 | tentativa 1/3
[2026-08-09 20:52:37] ⬇️ Iniciando download temporário de 202106: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202106
[2026-08-09 20:52:38] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 139191
[2026-08-09 20:52:38] 📦 Arquivo recebido: 0.13 MB
[2026-08-09 20:52:38] ✅ ZIP válido recebido para 202106.
[2026-08-09 20:52:38] ✅ CSV salvo: 202106_CPGF.csv (1.68 MB)
[2026-08-09 20:52:38] 🧹 ZIP temporário apagado: 202106_CPGF.zip
[2026-08-09 20:52:38] 🎉 Competência concluída: 202106
[2026-08-09 20:52:38] 😴 Aguardando 30s antes da próxima requisição...
[2026-08-09 20:53:08] 📌 [7/12] Competência 202107
[2026-08-09 20:53:08] 🔁 202107 | tentativa 1/3
[2026-08-09 20:53:08] ⬇️ Iniciando download temporário de 202107: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202107
[2026-08-09 20:53:09] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 151424
[2026-08-09 20:53:09] 📦 Arquivo recebido: 0.14 MB
[2026-08-09 20:53:09] ✅ ZIP válido recebido para 202107.
[2026-08-09 20:53:09] ✅ CSV salvo: 202107_CPGF.csv (1.93 MB)
[2026-08-09 20:53:09] 🧹 ZIP temporário apagado: 202107_CPGF.zip
[2026-08-09 20:53:09] 🎉 Competência concluída: 202107
[2026-08-09 20:53:09] 😴 Aguardando 33s antes da próxima requisição...
[2026-08-09 20:53:42] 📌 [8/12] Competência 202108
[2026-08-09 20:53:42] 🔁 202108 | tentativa 1/3
[2026-08-09 20:53:42] ⬇️ Iniciando download temporário de 202108: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202108
[2026-08-09 20:53:43] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 152977
[2026-08-09 20:53:43] 📦 Arquivo recebido: 0.15 MB
[2026-08-09 20:53:43] ✅ ZIP válido recebido para 202108.
[2026-08-09 20:53:43] ✅ CSV salvo: 202108_CPGF.csv (1.83 MB)
[2026-08-09 20:53:43] 🧹 ZIP temporário apagado: 202108_CPGF.zip
[2026-08-09 20:53:43] 🎉 Competência concluída: 202108
[2026-08-09 20:53:43] 😴 Aguardando 28s antes da próxima requisição...
[2026-08-09 20:54:11] 📌 [9/12] Competência 202109
[2026-08-09 20:54:11] 🔁 202109 | tentativa 1/3
[2026-08-09 20:54:11] ⬇️ Iniciando download temporário de 202109: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202109
[2026-08-09 20:54:12] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 184903
[2026-08-09 20:54:13] 📦 Arquivo recebido: 0.18 MB
[2026-08-09 20:54:13] ✅ ZIP válido recebido para 202109.
[2026-08-09 20:54:13] ✅ CSV salvo: 202109_CPGF.csv (2.25 MB)
[2026-08-09 20:54:13] 🧹 ZIP temporário apagado: 202109_CPGF.zip
[2026-08-09 20:54:13] 🎉 Competência concluída: 202109
[2026-08-09 20:54:13] 😴 Aguardando 34s antes da próxima requisição...
[2026-08-09 20:54:47] 📌 [10/12] Competência 202110
[2026-08-09 20:54:47] 🔁 202110 | tentativa 1/3
[2026-08-09 20:54:47] ⬇️ Iniciando download temporário de 202110: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202110
[2026-08-09 20:54:47] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 185797
[2026-08-09 20:54:48] 📦 Arquivo recebido: 0.18 MB
[2026-08-09 20:54:48] ✅ ZIP válido recebido para 202110.
[2026-08-09 20:54:48] ✅ CSV salvo: 202110_CPGF.csv (2.27 MB)
[2026-08-09 20:54:48] 🧹 ZIP temporário apagado: 202110_CPGF.zip
[2026-08-09 20:54:48] 🎉 Competência concluída: 202110
[2026-08-09 20:54:48] 😴 Aguardando 42s antes da próxima requisição...
[2026-08-09 20:55:30] 📌 [11/12] Competência 202111
[2026-08-09 20:55:30] 🔁 202111 | tentativa 1/3
[2026-08-09 20:55:30] ⬇️ Iniciando download temporário de 202111: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202111
[2026-08-09 20:55:31] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 200937
[2026-08-09 20:55:31] 📦 Arquivo recebido: 0.19 MB
[2026-08-09 20:55:31] ✅ ZIP válido recebido para 202111.
[2026-08-09 20:55:31] ✅ CSV salvo: 202111_CPGF.csv (2.51 MB)
[2026-08-09 20:55:31] 🧹 ZIP temporário apagado: 202111_CPGF.zip
[2026-08-09 20:55:31] 🎉 Competência concluída: 202111
[2026-08-09 20:55:31] 😴 Aguardando 41s antes da próxima requisição...
[2026-08-09 20:56:12] 📌 [12/12] Competência 202112
[2026-08-09 20:56:12] 🔁 202112 | tentativa 1/3
[2026-08-09 20:56:12] ⬇️ Iniciando download temporário de 202112: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202112
[2026-08-09 20:56:13] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 237057
[2026-08-09 20:56:13] 📦 Arquivo recebido: 0.23 MB
[2026-08-09 20:56:13] ✅ ZIP válido recebido para 202112.
[2026-08-09 20:56:13] ✅ CSV salvo: 202112_CPGF.csv (3.03 MB)
[2026-08-09 20:56:13] 🧹 ZIP temporário apagado: 202112_CPGF.zip
[2026-08-09 20:56:13] 🎉 Competência concluída: 202112
[2026-08-09 20:56:13] 📊 Resumo do bloco: 12 concluída(s), 0 falha(s), 0 bloqueio(s).

{'concluidas': ['202101',
  '202102',
  '202103',
  '202104',
  '202105',
  '202106',
  '202107',
  '202108',
  '202109',
  '202110',
  '202111',
  '202112'],
 'falhas': [],
 'bloqueadas': []}

### 📦 2022 — janeiro a dezembro

Baixa as 12 competências de `202201` a `202212`.

In [15]:
executar_bloco('202201', '202212')

[2026-08-09 20:56:13] 🚀 Iniciando bloco 202201 a 202212 (12 competência(s)).
[2026-08-09 20:56:13] 📌 [1/12] Competência 202201
[2026-08-09 20:56:13] 🔁 202201 | tentativa 1/3
[2026-08-09 20:56:13] ⬇️ Iniciando download temporário de 202201: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202201
[2026-08-09 20:56:14] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 176990
[2026-08-09 20:56:14] 📦 Arquivo recebido: 0.17 MB
[2026-08-09 20:56:14] ✅ ZIP válido recebido para 202201.
[2026-08-09 20:56:14] ✅ CSV salvo: 202201_CPGF.csv (2.32 MB)
[2026-08-09 20:56:14] 🧹 ZIP temporário apagado: 202201_CPGF.zip
[2026-08-09 20:56:14] 🎉 Competência concluída: 202201
[2026-08-09 20:56:14] 😴 Aguardando 33s antes da próxima requisição...
[2026-08-09 20:56:47] 📌 [2/12] Competência 202202
[2026-08-09 20:56:47] 🔁 202202 | tentativa 1/3
[2026-08-09 20:56:47] ⬇️ Iniciando download temporário de 202202: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202202
[2026-08-09 20:56:48] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 37257
[2026-08-09 20:56:48] 📦 Arquivo recebido: 0.04 MB
[2026-08-09 20:56:48] ✅ ZIP válido recebido para 202202.
[2026-08-09 20:56:48] ✅ CSV salvo: 202202_CPGF.csv (0.46 MB)
[2026-08-09 20:56:48] 🧹 ZIP temporário apagado: 202202_CPGF.zip
[2026-08-09 20:56:48] 🎉 Competência concluída: 202202
[2026-08-09 20:56:48] 😴 Aguardando 33s antes da próxima requisição...
[2026-08-09 20:57:21] 📌 [3/12] Competência 202203
[2026-08-09 20:57:21] 🔁 202203 | tentativa 1/3
[2026-08-09 20:57:21] ⬇️ Iniciando download temporário de 202203: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202203
[2026-08-09 20:57:22] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 125932
[2026-08-09 20:57:22] 📦 Arquivo recebido: 0.12 MB
[2026-08-09 20:57:22] ✅ ZIP válido recebido para 202203.
[2026-08-09 20:57:22] ✅ CSV salvo: 202203_CPGF.csv (1.59 MB)
[2026-08-09 20:57:22] 🧹 ZIP temporário apagado: 202203_CPGF.zip
[2026-08-09 20:57:22] 🎉 Competência concluída: 202203
[2026-08-09 20:57:22] 😴 Aguardando 30s antes da próxima requisição...
[2026-08-09 20:57:52] 📌 [4/12] Competência 202204
[2026-08-09 20:57:52] 🔁 202204 | tentativa 1/3
[2026-08-09 20:57:52] ⬇️ Iniciando download temporário de 202204: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202204
[2026-08-09 20:57:53] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 203450
[2026-08-09 20:57:54] 📦 Arquivo recebido: 0.19 MB
[2026-08-09 20:57:54] ✅ ZIP válido recebido para 202204.
[2026-08-09 20:57:54] ✅ CSV salvo: 202204_CPGF.csv (2.54 MB)
[2026-08-09 20:57:54] 🧹 ZIP temporário apagado: 202204_CPGF.zip
[2026-08-09 20:57:54] 🎉 Competência concluída: 202204
[2026-08-09 20:57:54] 😴 Aguardando 39s antes da próxima requisição...
[2026-08-09 20:58:33] 📌 [5/12] Competência 202205
[2026-08-09 20:58:33] 🔁 202205 | tentativa 1/3
[2026-08-09 20:58:33] ⬇️ Iniciando download temporário de 202205: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202205
[2026-08-09 20:58:33] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 198723
[2026-08-09 20:58:34] 📦 Arquivo recebido: 0.19 MB
[2026-08-09 20:58:34] ✅ ZIP válido recebido para 202205.
[2026-08-09 20:58:34] ✅ CSV salvo: 202205_CPGF.csv (2.46 MB)
[2026-08-09 20:58:34] 🧹 ZIP temporário apagado: 202205_CPGF.zip
[2026-08-09 20:58:34] 🎉 Competência concluída: 202205
[2026-08-09 20:58:34] 😴 Aguardando 29s antes da próxima requisição...
[2026-08-09 20:59:03] 📌 [6/12] Competência 202206
[2026-08-09 20:59:03] 🔁 202206 | tentativa 1/3
[2026-08-09 20:59:03] ⬇️ Iniciando download temporário de 202206: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202206
[2026-08-09 20:59:03] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 252395
[2026-08-09 20:59:04] 📦 Arquivo recebido: 0.24 MB
[2026-08-09 20:59:04] ✅ ZIP válido recebido para 202206.
[2026-08-09 20:59:04] ✅ CSV salvo: 202206_CPGF.csv (3.09 MB)
[2026-08-09 20:59:04] 🧹 ZIP temporário apagado: 202206_CPGF.zip
[2026-08-09 20:59:04] 🎉 Competência concluída: 202206
[2026-08-09 20:59:04] 😴 Aguardando 34s antes da próxima requisição...
[2026-08-09 20:59:38] 📌 [7/12] Competência 202207
[2026-08-09 20:59:38] 🔁 202207 | tentativa 1/3
[2026-08-09 20:59:38] ⬇️ Iniciando download temporário de 202207: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202207
[2026-08-09 20:59:38] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 278379
[2026-08-09 20:59:39] 📦 Arquivo recebido: 0.27 MB
[2026-08-09 20:59:39] ✅ ZIP válido recebido para 202207.
[2026-08-09 20:59:39] ✅ CSV salvo: 202207_CPGF.csv (3.39 MB)
[2026-08-09 20:59:39] 🧹 ZIP temporário apagado: 202207_CPGF.zip
[2026-08-09 20:59:39] 🎉 Competência concluída: 202207
[2026-08-09 20:59:39] 😴 Aguardando 32s antes da próxima requisição...
[2026-08-09 21:00:11] 📌 [8/12] Competência 202208
[2026-08-09 21:00:11] 🔁 202208 | tentativa 1/3
[2026-08-09 21:00:11] ⬇️ Iniciando download temporário de 202208: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202208
[2026-08-09 21:00:11] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 328212
[2026-08-09 21:00:12] 📦 Arquivo recebido: 0.31 MB
[2026-08-09 21:00:12] ✅ ZIP válido recebido para 202208.
[2026-08-09 21:00:12] ✅ CSV salvo: 202208_CPGF.csv (4.07 MB)
[2026-08-09 21:00:12] 🧹 ZIP temporário apagado: 202208_CPGF.zip
[2026-08-09 21:00:12] 🎉 Competência concluída: 202208
[2026-08-09 21:00:12] 😴 Aguardando 40s antes da próxima requisição...
[2026-08-09 21:00:52] 📌 [9/12] Competência 202209
[2026-08-09 21:00:52] 🔁 202209 | tentativa 1/3
[2026-08-09 21:00:52] ⬇️ Iniciando download temporário de 202209: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202209
[2026-08-09 21:00:53] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 348631
[2026-08-09 21:00:53] 📦 Arquivo recebido: 0.33 MB
[2026-08-09 21:00:53] ✅ ZIP válido recebido para 202209.
[2026-08-09 21:00:53] ✅ CSV salvo: 202209_CPGF.csv (4.35 MB)
[2026-08-09 21:00:53] 🧹 ZIP temporário apagado: 202209_CPGF.zip
[2026-08-09 21:00:53] 🎉 Competência concluída: 202209
[2026-08-09 21:00:53] 😴 Aguardando 27s antes da próxima requisição...
[2026-08-09 21:01:20] 📌 [10/12] Competência 202210
[2026-08-09 21:01:20] 🔁 202210 | tentativa 1/3
[2026-08-09 21:01:20] ⬇️ Iniciando download temporário de 202210: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202210
[2026-08-09 21:01:21] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 309583
[2026-08-09 21:01:21] 📦 Arquivo recebido: 0.30 MB
[2026-08-09 21:01:21] ✅ ZIP válido recebido para 202210.
[2026-08-09 21:01:21] ✅ CSV salvo: 202210_CPGF.csv (4.01 MB)
[2026-08-09 21:01:21] 🧹 ZIP temporário apagado: 202210_CPGF.zip
[2026-08-09 21:01:21] 🎉 Competência concluída: 202210
[2026-08-09 21:01:21] 😴 Aguardando 27s antes da próxima requisição...
[2026-08-09 21:01:48] 📌 [11/12] Competência 202211
[2026-08-09 21:01:48] 🔁 202211 | tentativa 1/3
[2026-08-09 21:01:48] ⬇️ Iniciando download temporário de 202211: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202211
[2026-08-09 21:01:49] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 307866
[2026-08-09 21:01:49] 📦 Arquivo recebido: 0.29 MB
[2026-08-09 21:01:49] ✅ ZIP válido recebido para 202211.
[2026-08-09 21:01:49] ✅ CSV salvo: 202211_CPGF.csv (4.06 MB)
[2026-08-09 21:01:49] 🧹 ZIP temporário apagado: 202211_CPGF.zip
[2026-08-09 21:01:49] 🎉 Competência concluída: 202211
[2026-08-09 21:01:49] 😴 Aguardando 33s antes da próxima requisição...
[2026-08-09 21:02:22] 📌 [12/12] Competência 202212
[2026-08-09 21:02:22] 🔁 202212 | tentativa 1/3
[2026-08-09 21:02:22] ⬇️ Iniciando download temporário de 202212: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202212
[2026-08-09 21:02:23] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 309857
[2026-08-09 21:02:24] 📦 Arquivo recebido: 0.30 MB
[2026-08-09 21:02:24] ✅ ZIP válido recebido para 202212.
[2026-08-09 21:02:24] ✅ CSV salvo: 202212_CPGF.csv (4.25 MB)
[2026-08-09 21:02:24] 🧹 ZIP temporário apagado: 202212_CPGF.zip
[2026-08-09 21:02:24] 🎉 Competência concluída: 202212
[2026-08-09 21:02:24] 📊 Resumo do bloco: 12 concluída(s), 0 falha(s), 0 bloqueio(s).

{'concluidas': ['202201',
  '202202',
  '202203',
  '202204',
  '202205',
  '202206',
  '202207',
  '202208',
  '202209',
  '202210',
  '202211',
  '202212'],
 'falhas': [],
 'bloqueadas': []}

### 📦 2023 — janeiro a dezembro

Baixa as 12 competências de `202301` a `202312`.

In [16]:
executar_bloco('202301', '202312')

[2026-08-09 21:02:24] 🚀 Iniciando bloco 202301 a 202312 (12 competência(s)).
[2026-08-09 21:02:24] 📌 [1/12] Competência 202301
[2026-08-09 21:02:24] 🔁 202301 | tentativa 1/3
[2026-08-09 21:02:24] ⬇️ Iniciando download temporário de 202301: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202301
[2026-08-09 21:02:25] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 195798
[2026-08-09 21:02:25] 📦 Arquivo recebido: 0.19 MB
[2026-08-09 21:02:25] ✅ ZIP válido recebido para 202301.
[2026-08-09 21:02:25] ✅ CSV salvo: 202301_CPGF.csv (2.86 MB)
[2026-08-09 21:02:25] 🧹 ZIP temporário apagado: 202301_CPGF.zip
[2026-08-09 21:02:25] 🎉 Competência concluída: 202301
[2026-08-09 21:02:25] 😴 Aguardando 34s antes da próxima requisição...
[2026-08-09 21:02:59] 📌 [2/12] Competência 202302
[2026-08-09 21:02:59] 🔁 202302 | tentativa 1/3
[2026-08-09 21:02:59] ⬇️ Iniciando download temporário de 202302: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202302
[2026-08-09 21:03:00] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 42389
[2026-08-09 21:03:00] 📦 Arquivo recebido: 0.04 MB
[2026-08-09 21:03:00] ✅ ZIP válido recebido para 202302.
[2026-08-09 21:03:00] ✅ CSV salvo: 202302_CPGF.csv (0.48 MB)
[2026-08-09 21:03:00] 🧹 ZIP temporário apagado: 202302_CPGF.zip
[2026-08-09 21:03:00] 🎉 Competência concluída: 202302
[2026-08-09 21:03:00] 😴 Aguardando 28s antes da próxima requisição...
[2026-08-09 21:03:28] 📌 [3/12] Competência 202303
[2026-08-09 21:03:28] 🔁 202303 | tentativa 1/3
[2026-08-09 21:03:28] ⬇️ Iniciando download temporário de 202303: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202303
[2026-08-09 21:03:29] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 140744
[2026-08-09 21:03:29] 📦 Arquivo recebido: 0.13 MB
[2026-08-09 21:03:29] ✅ ZIP válido recebido para 202303.
[2026-08-09 21:03:29] ✅ CSV salvo: 202303_CPGF.csv (1.73 MB)
[2026-08-09 21:03:29] 🧹 ZIP temporário apagado: 202303_CPGF.zip
[2026-08-09 21:03:29] 🎉 Competência concluída: 202303
[2026-08-09 21:03:29] 😴 Aguardando 30s antes da próxima requisição...
[2026-08-09 21:03:59] 📌 [4/12] Competência 202304
[2026-08-09 21:03:59] 🔁 202304 | tentativa 1/3
[2026-08-09 21:03:59] ⬇️ Iniciando download temporário de 202304: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202304
[2026-08-09 21:04:00] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 234715
[2026-08-09 21:04:00] 📦 Arquivo recebido: 0.22 MB
[2026-08-09 21:04:00] ✅ ZIP válido recebido para 202304.
[2026-08-09 21:04:00] ✅ CSV salvo: 202304_CPGF.csv (2.99 MB)
[2026-08-09 21:04:00] 🧹 ZIP temporário apagado: 202304_CPGF.zip
[2026-08-09 21:04:00] 🎉 Competência concluída: 202304
[2026-08-09 21:04:00] 😴 Aguardando 34s antes da próxima requisição...
[2026-08-09 21:04:34] 📌 [5/12] Competência 202305
[2026-08-09 21:04:34] 🔁 202305 | tentativa 1/3
[2026-08-09 21:04:34] ⬇️ Iniciando download temporário de 202305: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202305
[2026-08-09 21:04:35] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 219446
[2026-08-09 21:04:36] 📦 Arquivo recebido: 0.21 MB
[2026-08-09 21:04:36] ✅ ZIP válido recebido para 202305.
[2026-08-09 21:04:36] ✅ CSV salvo: 202305_CPGF.csv (2.67 MB)
[2026-08-09 21:04:36] 🧹 ZIP temporário apagado: 202305_CPGF.zip
[2026-08-09 21:04:36] 🎉 Competência concluída: 202305
[2026-08-09 21:04:36] 😴 Aguardando 27s antes da próxima requisição...
[2026-08-09 21:05:03] 📌 [6/12] Competência 202306
[2026-08-09 21:05:03] 🔁 202306 | tentativa 1/3
[2026-08-09 21:05:03] ⬇️ Iniciando download temporário de 202306: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202306
[2026-08-09 21:05:03] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 285793
[2026-08-09 21:05:04] 📦 Arquivo recebido: 0.27 MB
[2026-08-09 21:05:04] ✅ ZIP válido recebido para 202306.
[2026-08-09 21:05:04] ✅ CSV salvo: 202306_CPGF.csv (3.61 MB)
[2026-08-09 21:05:04] 🧹 ZIP temporário apagado: 202306_CPGF.zip
[2026-08-09 21:05:04] 🎉 Competência concluída: 202306
[2026-08-09 21:05:04] 😴 Aguardando 42s antes da próxima requisição...
[2026-08-09 21:05:46] 📌 [7/12] Competência 202307
[2026-08-09 21:05:46] 🔁 202307 | tentativa 1/3
[2026-08-09 21:05:46] ⬇️ Iniciando download temporário de 202307: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202307
[2026-08-09 21:05:46] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 253309
[2026-08-09 21:05:47] 📦 Arquivo recebido: 0.24 MB
[2026-08-09 21:05:47] ✅ ZIP válido recebido para 202307.
[2026-08-09 21:05:47] ✅ CSV salvo: 202307_CPGF.csv (3.12 MB)
[2026-08-09 21:05:47] 🧹 ZIP temporário apagado: 202307_CPGF.zip
[2026-08-09 21:05:47] 🎉 Competência concluída: 202307
[2026-08-09 21:05:47] 😴 Aguardando 25s antes da próxima requisição...
[2026-08-09 21:06:12] 📌 [8/12] Competência 202308
[2026-08-09 21:06:12] 🔁 202308 | tentativa 1/3
[2026-08-09 21:06:12] ⬇️ Iniciando download temporário de 202308: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202308
[2026-08-09 21:06:13] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 258710
[2026-08-09 21:06:13] 📦 Arquivo recebido: 0.25 MB
[2026-08-09 21:06:13] ✅ ZIP válido recebido para 202308.
[2026-08-09 21:06:13] ✅ CSV salvo: 202308_CPGF.csv (3.26 MB)
[2026-08-09 21:06:13] 🧹 ZIP temporário apagado: 202308_CPGF.zip
[2026-08-09 21:06:13] 🎉 Competência concluída: 202308
[2026-08-09 21:06:13] 😴 Aguardando 44s antes da próxima requisição...
[2026-08-09 21:06:57] 📌 [9/12] Competência 202309
[2026-08-09 21:06:57] 🔁 202309 | tentativa 1/3
[2026-08-09 21:06:57] ⬇️ Iniciando download temporário de 202309: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202309
[2026-08-09 21:06:58] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 279702
[2026-08-09 21:06:58] 📦 Arquivo recebido: 0.27 MB
[2026-08-09 21:06:58] ✅ ZIP válido recebido para 202309.
[2026-08-09 21:06:58] ✅ CSV salvo: 202309_CPGF.csv (3.53 MB)
[2026-08-09 21:06:58] 🧹 ZIP temporário apagado: 202309_CPGF.zip
[2026-08-09 21:06:58] 🎉 Competência concluída: 202309
[2026-08-09 21:06:58] 😴 Aguardando 35s antes da próxima requisição...
[2026-08-09 21:07:33] 📌 [10/12] Competência 202310
[2026-08-09 21:07:33] 🔁 202310 | tentativa 1/3
[2026-08-09 21:07:33] ⬇️ Iniciando download temporário de 202310: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202310
[2026-08-09 21:07:34] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 249137
[2026-08-09 21:07:35] 📦 Arquivo recebido: 0.24 MB
[2026-08-09 21:07:35] ✅ ZIP válido recebido para 202310.
[2026-08-09 21:07:35] ✅ CSV salvo: 202310_CPGF.csv (3.15 MB)
[2026-08-09 21:07:35] 🧹 ZIP temporário apagado: 202310_CPGF.zip
[2026-08-09 21:07:35] 🎉 Competência concluída: 202310
[2026-08-09 21:07:35] 😴 Aguardando 42s antes da próxima requisição...
[2026-08-09 21:08:17] 📌 [11/12] Competência 202311
[2026-08-09 21:08:17] 🔁 202311 | tentativa 1/3
[2026-08-09 21:08:17] ⬇️ Iniciando download temporário de 202311: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202311
[2026-08-09 21:08:17] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 299127
[2026-08-09 21:08:18] 📦 Arquivo recebido: 0.29 MB
[2026-08-09 21:08:18] ✅ ZIP válido recebido para 202311.
[2026-08-09 21:08:18] ✅ CSV salvo: 202311_CPGF.csv (3.85 MB)
[2026-08-09 21:08:18] 🧹 ZIP temporário apagado: 202311_CPGF.zip
[2026-08-09 21:08:18] 🎉 Competência concluída: 202311
[2026-08-09 21:08:18] 😴 Aguardando 39s antes da próxima requisição...
[2026-08-09 21:08:57] 📌 [12/12] Competência 202312
[2026-08-09 21:08:57] 🔁 202312 | tentativa 1/3
[2026-08-09 21:08:57] ⬇️ Iniciando download temporário de 202312: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202312
[2026-08-09 21:08:58] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 320843
[2026-08-09 21:08:58] 📦 Arquivo recebido: 0.31 MB
[2026-08-09 21:08:58] ✅ ZIP válido recebido para 202312.
[2026-08-09 21:08:58] ✅ CSV salvo: 202312_CPGF.csv (4.27 MB)
[2026-08-09 21:08:58] 🧹 ZIP temporário apagado: 202312_CPGF.zip
[2026-08-09 21:08:58] 🎉 Competência concluída: 202312
[2026-08-09 21:08:58] 📊 Resumo do bloco: 12 concluída(s), 0 falha(s), 0 bloqueio(s).

{'concluidas': ['202301',
  '202302',
  '202303',
  '202304',
  '202305',
  '202306',
  '202307',
  '202308',
  '202309',
  '202310',
  '202311',
  '202312'],
 'falhas': [],
 'bloqueadas': []}

### 📦 2024 — janeiro a dezembro

Baixa as 12 competências de `202401` a `202412`.

In [17]:
executar_bloco('202401', '202412')

[2026-08-09 21:08:58] 🚀 Iniciando bloco 202401 a 202412 (12 competência(s)).
[2026-08-09 21:08:58] 📌 [1/12] Competência 202401
[2026-08-09 21:08:58] 🔁 202401 | tentativa 1/3
[2026-08-09 21:08:58] ⬇️ Iniciando download temporário de 202401: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202401
[2026-08-09 21:08:59] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 186543
[2026-08-09 21:08:59] 📦 Arquivo recebido: 0.18 MB
[2026-08-09 21:08:59] ✅ ZIP válido recebido para 202401.
[2026-08-09 21:08:59] ✅ CSV salvo: 202401_CPGF.csv (2.55 MB)
[2026-08-09 21:08:59] 🧹 ZIP temporário apagado: 202401_CPGF.zip
[2026-08-09 21:08:59] 🎉 Competência concluída: 202401
[2026-08-09 21:08:59] 😴 Aguardando 39s antes da próxima requisição...
[2026-08-09 21:09:38] 📌 [2/12] Competência 202402
[2026-08-09 21:09:38] 🔁 202402 | tentativa 1/3
[2026-08-09 21:09:38] ⬇️ Iniciando download temporário de 202402: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202402
[2026-08-09 21:09:39] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 52633
[2026-08-09 21:09:39] 📦 Arquivo recebido: 0.05 MB
[2026-08-09 21:09:39] ✅ ZIP válido recebido para 202402.
[2026-08-09 21:09:39] ✅ CSV salvo: 202402_CPGF.csv (0.66 MB)
[2026-08-09 21:09:40] 🧹 ZIP temporário apagado: 202402_CPGF.zip
[2026-08-09 21:09:40] 🎉 Competência concluída: 202402
[2026-08-09 21:09:40] 😴 Aguardando 39s antes da próxima requisição...
[2026-08-09 21:10:19] 📌 [3/12] Competência 202403
[2026-08-09 21:10:19] 🔁 202403 | tentativa 1/3
[2026-08-09 21:10:19] ⬇️ Iniciando download temporário de 202403: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202403
[2026-08-09 21:10:19] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 155785
[2026-08-09 21:10:20] 📦 Arquivo recebido: 0.15 MB
[2026-08-09 21:10:20] ✅ ZIP válido recebido para 202403.
[2026-08-09 21:10:20] ✅ CSV salvo: 202403_CPGF.csv (1.97 MB)
[2026-08-09 21:10:20] 🧹 ZIP temporário apagado: 202403_CPGF.zip
[2026-08-09 21:10:20] 🎉 Competência concluída: 202403
[2026-08-09 21:10:20] 😴 Aguardando 33s antes da próxima requisição...
[2026-08-09 21:10:53] 📌 [4/12] Competência 202404
[2026-08-09 21:10:53] 🔁 202404 | tentativa 1/3
[2026-08-09 21:10:53] ⬇️ Iniciando download temporário de 202404: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202404
[2026-08-09 21:10:54] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 250258
[2026-08-09 21:10:54] 📦 Arquivo recebido: 0.24 MB
[2026-08-09 21:10:54] ✅ ZIP válido recebido para 202404.
[2026-08-09 21:10:54] ✅ CSV salvo: 202404_CPGF.csv (3.30 MB)
[2026-08-09 21:10:54] 🧹 ZIP temporário apagado: 202404_CPGF.zip
[2026-08-09 21:10:54] 🎉 Competência concluída: 202404
[2026-08-09 21:10:54] 😴 Aguardando 27s antes da próxima requisição...
[2026-08-09 21:11:21] 📌 [5/12] Competência 202405
[2026-08-09 21:11:21] 🔁 202405 | tentativa 1/3
[2026-08-09 21:11:21] ⬇️ Iniciando download temporário de 202405: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202405
[2026-08-09 21:11:22] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 256479
[2026-08-09 21:11:22] 📦 Arquivo recebido: 0.24 MB
[2026-08-09 21:11:22] ✅ ZIP válido recebido para 202405.
[2026-08-09 21:11:22] ✅ CSV salvo: 202405_CPGF.csv (3.42 MB)
[2026-08-09 21:11:22] 🧹 ZIP temporário apagado: 202405_CPGF.zip
[2026-08-09 21:11:22] 🎉 Competência concluída: 202405
[2026-08-09 21:11:22] 😴 Aguardando 37s antes da próxima requisição...
[2026-08-09 21:11:59] 📌 [6/12] Competência 202406
[2026-08-09 21:11:59] 🔁 202406 | tentativa 1/3
[2026-08-09 21:11:59] ⬇️ Iniciando download temporário de 202406: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202406
[2026-08-09 21:12:00] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 253337
[2026-08-09 21:12:00] 📦 Arquivo recebido: 0.24 MB
[2026-08-09 21:12:00] ✅ ZIP válido recebido para 202406.
[2026-08-09 21:12:00] ✅ CSV salvo: 202406_CPGF.csv (3.30 MB)
[2026-08-09 21:12:00] 🧹 ZIP temporário apagado: 202406_CPGF.zip
[2026-08-09 21:12:00] 🎉 Competência concluída: 202406
[2026-08-09 21:12:00] 😴 Aguardando 31s antes da próxima requisição...
[2026-08-09 21:12:31] 📌 [7/12] Competência 202407
[2026-08-09 21:12:31] 🔁 202407 | tentativa 1/3
[2026-08-09 21:12:31] ⬇️ Iniciando download temporário de 202407: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202407
[2026-08-09 21:12:32] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 267687
[2026-08-09 21:12:32] 📦 Arquivo recebido: 0.26 MB
[2026-08-09 21:12:32] ✅ ZIP válido recebido para 202407.
[2026-08-09 21:12:33] ✅ CSV salvo: 202407_CPGF.csv (3.42 MB)
[2026-08-09 21:12:33] 🧹 ZIP temporário apagado: 202407_CPGF.zip
[2026-08-09 21:12:33] 🎉 Competência concluída: 202407
[2026-08-09 21:12:33] 😴 Aguardando 33s antes da próxima requisição...
[2026-08-09 21:13:06] 📌 [8/12] Competência 202408
[2026-08-09 21:13:06] 🔁 202408 | tentativa 1/3
[2026-08-09 21:13:06] ⬇️ Iniciando download temporário de 202408: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202408
[2026-08-09 21:13:06] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 285977
[2026-08-09 21:13:07] 📦 Arquivo recebido: 0.27 MB
[2026-08-09 21:13:07] ✅ ZIP válido recebido para 202408.
[2026-08-09 21:13:07] ✅ CSV salvo: 202408_CPGF.csv (3.52 MB)
[2026-08-09 21:13:07] 🧹 ZIP temporário apagado: 202408_CPGF.zip
[2026-08-09 21:13:07] 🎉 Competência concluída: 202408
[2026-08-09 21:13:07] 😴 Aguardando 45s antes da próxima requisição...
[2026-08-09 21:13:52] 📌 [9/12] Competência 202409
[2026-08-09 21:13:52] 🔁 202409 | tentativa 1/3
[2026-08-09 21:13:52] ⬇️ Iniciando download temporário de 202409: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202409
[2026-08-09 21:13:53] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 280511
[2026-08-09 21:13:53] 📦 Arquivo recebido: 0.27 MB
[2026-08-09 21:13:53] ✅ ZIP válido recebido para 202409.
[2026-08-09 21:13:53] ✅ CSV salvo: 202409_CPGF.csv (3.35 MB)
[2026-08-09 21:13:53] 🧹 ZIP temporário apagado: 202409_CPGF.zip
[2026-08-09 21:13:53] 🎉 Competência concluída: 202409
[2026-08-09 21:13:53] 😴 Aguardando 36s antes da próxima requisição...
[2026-08-09 21:14:29] 📌 [10/12] Competência 202410
[2026-08-09 21:14:29] 🔁 202410 | tentativa 1/3
[2026-08-09 21:14:29] ⬇️ Iniciando download temporário de 202410: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202410
[2026-08-09 21:14:30] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 291113
[2026-08-09 21:14:30] 📦 Arquivo recebido: 0.28 MB
[2026-08-09 21:14:30] ✅ ZIP válido recebido para 202410.
[2026-08-09 21:14:30] ✅ CSV salvo: 202410_CPGF.csv (3.54 MB)
[2026-08-09 21:14:30] 🧹 ZIP temporário apagado: 202410_CPGF.zip
[2026-08-09 21:14:30] 🎉 Competência concluída: 202410
[2026-08-09 21:14:30] 😴 Aguardando 42s antes da próxima requisição...
[2026-08-09 21:15:12] 📌 [11/12] Competência 202411
[2026-08-09 21:15:12] 🔁 202411 | tentativa 1/3
[2026-08-09 21:15:12] ⬇️ Iniciando download temporário de 202411: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202411
[2026-08-09 21:15:13] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 340648
[2026-08-09 21:15:13] 📦 Arquivo recebido: 0.32 MB
[2026-08-09 21:15:13] ✅ ZIP válido recebido para 202411.
[2026-08-09 21:15:13] ✅ CSV salvo: 202411_CPGF.csv (4.32 MB)
[2026-08-09 21:15:13] 🧹 ZIP temporário apagado: 202411_CPGF.zip
[2026-08-09 21:15:13] 🎉 Competência concluída: 202411
[2026-08-09 21:15:13] 😴 Aguardando 29s antes da próxima requisição...
[2026-08-09 21:15:42] 📌 [12/12] Competência 202412
[2026-08-09 21:15:42] 🔁 202412 | tentativa 1/3
[2026-08-09 21:15:42] ⬇️ Iniciando download temporário de 202412: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202412
[2026-08-09 21:15:43] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 327394
[2026-08-09 21:15:44] 📦 Arquivo recebido: 0.31 MB
[2026-08-09 21:15:44] ✅ ZIP válido recebido para 202412.
[2026-08-09 21:15:44] ✅ CSV salvo: 202412_CPGF.csv (4.17 MB)
[2026-08-09 21:15:44] 🧹 ZIP temporário apagado: 202412_CPGF.zip
[2026-08-09 21:15:44] 🎉 Competência concluída: 202412
[2026-08-09 21:15:44] 📊 Resumo do bloco: 12 concluída(s), 0 falha(s), 0 bloqueio(s).

{'concluidas': ['202401',
  '202402',
  '202403',
  '202404',
  '202405',
  '202406',
  '202407',
  '202408',
  '202409',
  '202410',
  '202411',
  '202412'],
 'falhas': [],
 'bloqueadas': []}

### 📦 2025 — janeiro a dezembro

Baixa as 12 competências de `202501` a `202512`.

In [18]:
executar_bloco('202501', '202512')

[2026-08-09 21:15:44] 🚀 Iniciando bloco 202501 a 202512 (12 competência(s)).
[2026-08-09 21:15:44] 📌 [1/12] Competência 202501
[2026-08-09 21:15:44] 🔁 202501 | tentativa 1/3
[2026-08-09 21:15:44] ⬇️ Iniciando download temporário de 202501: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202501
[2026-08-09 21:15:45] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 219642
[2026-08-09 21:15:45] 📦 Arquivo recebido: 0.21 MB
[2026-08-09 21:15:45] ✅ ZIP válido recebido para 202501.
[2026-08-09 21:15:45] ✅ CSV salvo: 202501_CPGF.csv (2.90 MB)
[2026-08-09 21:15:45] 🧹 ZIP temporário apagado: 202501_CPGF.zip
[2026-08-09 21:15:45] 🎉 Competência concluída: 202501
[2026-08-09 21:15:45] 😴 Aguardando 26s antes da próxima requisição...
[2026-08-09 21:16:11] 📌 [2/12] Competência 202502
[2026-08-09 21:16:11] 🔁 202502 | tentativa 1/3
[2026-08-09 21:16:11] ⬇️ Iniciando download temporário de 202502: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202502
[2026-08-09 21:16:12] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 54521
[2026-08-09 21:16:12] 📦 Arquivo recebido: 0.05 MB
[2026-08-09 21:16:12] ✅ ZIP válido recebido para 202502.
[2026-08-09 21:16:12] ✅ CSV salvo: 202502_CPGF.csv (0.64 MB)
[2026-08-09 21:16:12] 🧹 ZIP temporário apagado: 202502_CPGF.zip
[2026-08-09 21:16:12] 🎉 Competência concluída: 202502
[2026-08-09 21:16:12] 😴 Aguardando 31s antes da próxima requisição...
[2026-08-09 21:16:43] 📌 [3/12] Competência 202503
[2026-08-09 21:16:43] 🔁 202503 | tentativa 1/3
[2026-08-09 21:16:43] ⬇️ Iniciando download temporário de 202503: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202503
[2026-08-09 21:16:44] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 202879
[2026-08-09 21:16:44] 📦 Arquivo recebido: 0.19 MB
[2026-08-09 21:16:44] ✅ ZIP válido recebido para 202503.
[2026-08-09 21:16:44] ✅ CSV salvo: 202503_CPGF.csv (2.50 MB)
[2026-08-09 21:16:44] 🧹 ZIP temporário apagado: 202503_CPGF.zip
[2026-08-09 21:16:44] 🎉 Competência concluída: 202503
[2026-08-09 21:16:44] 😴 Aguardando 29s antes da próxima requisição...
[2026-08-09 21:17:13] 📌 [4/12] Competência 202504
[2026-08-09 21:17:13] 🔁 202504 | tentativa 1/3
[2026-08-09 21:17:13] ⬇️ Iniciando download temporário de 202504: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202504
[2026-08-09 21:17:14] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 252303
[2026-08-09 21:17:14] 📦 Arquivo recebido: 0.24 MB
[2026-08-09 21:17:14] ✅ ZIP válido recebido para 202504.
[2026-08-09 21:17:14] ✅ CSV salvo: 202504_CPGF.csv (3.22 MB)
[2026-08-09 21:17:14] 🧹 ZIP temporário apagado: 202504_CPGF.zip
[2026-08-09 21:17:14] 🎉 Competência concluída: 202504
[2026-08-09 21:17:14] 😴 Aguardando 30s antes da próxima requisição...
[2026-08-09 21:17:44] 📌 [5/12] Competência 202505
[2026-08-09 21:17:44] 🔁 202505 | tentativa 1/3
[2026-08-09 21:17:44] ⬇️ Iniciando download temporário de 202505: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202505
[2026-08-09 21:17:45] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 271041
[2026-08-09 21:17:45] 📦 Arquivo recebido: 0.26 MB
[2026-08-09 21:17:45] ✅ ZIP válido recebido para 202505.
[2026-08-09 21:17:45] ✅ CSV salvo: 202505_CPGF.csv (3.38 MB)
[2026-08-09 21:17:45] 🧹 ZIP temporário apagado: 202505_CPGF.zip
[2026-08-09 21:17:45] 🎉 Competência concluída: 202505
[2026-08-09 21:17:45] 😴 Aguardando 33s antes da próxima requisição...
[2026-08-09 21:18:18] 📌 [6/12] Competência 202506
[2026-08-09 21:18:18] 🔁 202506 | tentativa 1/3
[2026-08-09 21:18:18] ⬇️ Iniciando download temporário de 202506: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202506
[2026-08-09 21:18:19] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 290059
[2026-08-09 21:18:20] 📦 Arquivo recebido: 0.28 MB
[2026-08-09 21:18:20] ✅ ZIP válido recebido para 202506.
[2026-08-09 21:18:20] ✅ CSV salvo: 202506_CPGF.csv (3.63 MB)
[2026-08-09 21:18:20] 🧹 ZIP temporário apagado: 202506_CPGF.zip
[2026-08-09 21:18:20] 🎉 Competência concluída: 202506
[2026-08-09 21:18:20] 😴 Aguardando 25s antes da próxima requisição...
[2026-08-09 21:18:45] 📌 [7/12] Competência 202507
[2026-08-09 21:18:45] 🔁 202507 | tentativa 1/3
[2026-08-09 21:18:45] ⬇️ Iniciando download temporário de 202507: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202507
[2026-08-09 21:18:46] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 281252
[2026-08-09 21:18:46] 📦 Arquivo recebido: 0.27 MB
[2026-08-09 21:18:46] ✅ ZIP válido recebido para 202507.
[2026-08-09 21:18:46] ✅ CSV salvo: 202507_CPGF.csv (3.53 MB)
[2026-08-09 21:18:46] 🧹 ZIP temporário apagado: 202507_CPGF.zip
[2026-08-09 21:18:46] 🎉 Competência concluída: 202507
[2026-08-09 21:18:46] 😴 Aguardando 31s antes da próxima requisição...
[2026-08-09 21:19:17] 📌 [8/12] Competência 202508
[2026-08-09 21:19:17] 🔁 202508 | tentativa 1/3
[2026-08-09 21:19:17] ⬇️ Iniciando download temporário de 202508: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202508
[2026-08-09 21:19:18] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 316260
[2026-08-09 21:19:18] 📦 Arquivo recebido: 0.30 MB
[2026-08-09 21:19:18] ✅ ZIP válido recebido para 202508.
[2026-08-09 21:19:18] ✅ CSV salvo: 202508_CPGF.csv (4.01 MB)
[2026-08-09 21:19:18] 🧹 ZIP temporário apagado: 202508_CPGF.zip
[2026-08-09 21:19:18] 🎉 Competência concluída: 202508
[2026-08-09 21:19:18] 😴 Aguardando 36s antes da próxima requisição...
[2026-08-09 21:19:54] 📌 [9/12] Competência 202509
[2026-08-09 21:19:54] 🔁 202509 | tentativa 1/3
[2026-08-09 21:19:54] ⬇️ Iniciando download temporário de 202509: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202509
[2026-08-09 21:19:55] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 317981
[2026-08-09 21:19:56] 📦 Arquivo recebido: 0.30 MB
[2026-08-09 21:19:56] ✅ ZIP válido recebido para 202509.
[2026-08-09 21:19:56] ✅ CSV salvo: 202509_CPGF.csv (3.92 MB)
[2026-08-09 21:19:56] 🧹 ZIP temporário apagado: 202509_CPGF.zip
[2026-08-09 21:19:56] 🎉 Competência concluída: 202509
[2026-08-09 21:19:56] 😴 Aguardando 36s antes da próxima requisição...
[2026-08-09 21:20:32] 📌 [10/12] Competência 202510
[2026-08-09 21:20:32] 🔁 202510 | tentativa 1/3
[2026-08-09 21:20:32] ⬇️ Iniciando download temporário de 202510: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202510
[2026-08-09 21:20:32] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 354853
[2026-08-09 21:20:33] 📦 Arquivo recebido: 0.34 MB
[2026-08-09 21:20:33] ✅ ZIP válido recebido para 202510.
[2026-08-09 21:20:33] ✅ CSV salvo: 202510_CPGF.csv (4.45 MB)
[2026-08-09 21:20:33] 🧹 ZIP temporário apagado: 202510_CPGF.zip
[2026-08-09 21:20:33] 🎉 Competência concluída: 202510
[2026-08-09 21:20:33] 😴 Aguardando 38s antes da próxima requisição...
[2026-08-09 21:21:11] 📌 [11/12] Competência 202511
[2026-08-09 21:21:11] 🔁 202511 | tentativa 1/3
[2026-08-09 21:21:11] ⬇️ Iniciando download temporário de 202511: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202511
[2026-08-09 21:21:11] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 360183
[2026-08-09 21:21:12] 📦 Arquivo recebido: 0.34 MB
[2026-08-09 21:21:12] ✅ ZIP válido recebido para 202511.
[2026-08-09 21:21:12] ✅ CSV salvo: 202511_CPGF.csv (4.45 MB)
[2026-08-09 21:21:12] 🧹 ZIP temporário apagado: 202511_CPGF.zip
[2026-08-09 21:21:12] 🎉 Competência concluída: 202511
[2026-08-09 21:21:12] 😴 Aguardando 42s antes da próxima requisição...
[2026-08-09 21:21:54] 📌 [12/12] Competência 202512
[2026-08-09 21:21:54] 🔁 202512 | tentativa 1/3
[2026-08-09 21:21:54] ⬇️ Iniciando download temporário de 202512: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202512
[2026-08-09 21:21:55] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 431754
[2026-08-09 21:21:55] 📦 Arquivo recebido: 0.41 MB
[2026-08-09 21:21:55] ✅ ZIP válido recebido para 202512.
[2026-08-09 21:21:55] ✅ CSV salvo: 202512_CPGF.csv (5.70 MB)
[2026-08-09 21:21:55] 🧹 ZIP temporário apagado: 202512_CPGF.zip
[2026-08-09 21:21:55] 🎉 Competência concluída: 202512
[2026-08-09 21:21:55] 📊 Resumo do bloco: 12 concluída(s), 0 falha(s), 0 bloqueio(s).

{'concluidas': ['202501',
  '202502',
  '202503',
  '202504',
  '202505',
  '202506',
  '202507',
  '202508',
  '202509',
  '202510',
  '202511',
  '202512'],
 'falhas': [],
 'bloqueadas': []}

### 📦 2026 — janeiro a julho

Baixa as sete competências de `202601` a `202607`.

In [19]:
executar_bloco('202601', '202607')

[2026-08-09 21:21:55] 🚀 Iniciando bloco 202601 a 202607 (7 competência(s)).
[2026-08-09 21:21:55] 📌 [1/7] Competência 202601
[2026-08-09 21:21:55] 🔁 202601 | tentativa 1/3
[2026-08-09 21:21:55] ⬇️ Iniciando download temporário de 202601: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202601
[2026-08-09 21:21:56] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 178124
[2026-08-09 21:21:56] 📦 Arquivo recebido: 0.17 MB
[2026-08-09 21:21:56] ✅ ZIP válido recebido para 202601.
[2026-08-09 21:21:57] ✅ CSV salvo: 202601_CPGF.csv (2.67 MB)
[2026-08-09 21:21:57] 🧹 ZIP temporário apagado: 202601_CPGF.zip
[2026-08-09 21:21:57] 🎉 Competência concluída: 202601
[2026-08-09 21:21:57] 😴 Aguardando 44s antes da próxima requisição...
[2026-08-09 21:22:41] 📌 [2/7] Competência 202602
[2026-08-09 21:22:41] 🔁 202602 | tentativa 1/3
[2026-08-09 21:22:41] ⬇️ Iniciando download temporário de 202602: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202602
[2026-08-09 21:22:41] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 59634
[2026-08-09 21:22:42] 📦 Arquivo recebido: 0.06 MB
[2026-08-09 21:22:42] ✅ ZIP válido recebido para 202602.
[2026-08-09 21:22:42] ✅ CSV salvo: 202602_CPGF.csv (0.70 MB)
[2026-08-09 21:22:42] 🧹 ZIP temporário apagado: 202602_CPGF.zip
[2026-08-09 21:22:42] 🎉 Competência concluída: 202602
[2026-08-09 21:22:42] 😴 Aguardando 36s antes da próxima requisição...
[2026-08-09 21:23:18] 📌 [3/7] Competência 202603
[2026-08-09 21:23:18] 🔁 202603 | tentativa 1/3
[2026-08-09 21:23:18] ⬇️ Iniciando download temporário de 202603: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202603
[2026-08-09 21:23:18] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 168370
[2026-08-09 21:23:19] 📦 Arquivo recebido: 0.16 MB
[2026-08-09 21:23:19] ✅ ZIP válido recebido para 202603.
[2026-08-09 21:23:19] ✅ CSV salvo: 202603_CPGF.csv (2.05 MB)
[2026-08-09 21:23:19] 🧹 ZIP temporário apagado: 202603_CPGF.zip
[2026-08-09 21:23:19] 🎉 Competência concluída: 202603
[2026-08-09 21:23:19] 😴 Aguardando 42s antes da próxima requisição...
[2026-08-09 21:24:01] 📌 [4/7] Competência 202604
[2026-08-09 21:24:01] 🔁 202604 | tentativa 1/3
[2026-08-09 21:24:01] ⬇️ Iniciando download temporário de 202604: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202604
[2026-08-09 21:24:02] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 301386
[2026-08-09 21:24:02] 📦 Arquivo recebido: 0.29 MB
[2026-08-09 21:24:02] ✅ ZIP válido recebido para 202604.
[2026-08-09 21:24:02] ✅ CSV salvo: 202604_CPGF.csv (3.89 MB)
[2026-08-09 21:24:02] 🧹 ZIP temporário apagado: 202604_CPGF.zip
[2026-08-09 21:24:02] 🎉 Competência concluída: 202604
[2026-08-09 21:24:02] 😴 Aguardando 40s antes da próxima requisição...
[2026-08-09 21:24:42] 📌 [5/7] Competência 202605
[2026-08-09 21:24:42] 🔁 202605 | tentativa 1/3
[2026-08-09 21:24:42] ⬇️ Iniciando download temporário de 202605: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202605
[2026-08-09 21:24:43] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 272778
[2026-08-09 21:24:43] 📦 Arquivo recebido: 0.26 MB
[2026-08-09 21:24:43] ✅ ZIP válido recebido para 202605.
[2026-08-09 21:24:43] ✅ CSV salvo: 202605_CPGF.csv (3.51 MB)
[2026-08-09 21:24:43] 🧹 ZIP temporário apagado: 202605_CPGF.zip
[2026-08-09 21:24:43] 🎉 Competência concluída: 202605
[2026-08-09 21:24:43] 😴 Aguardando 27s antes da próxima requisição...
[2026-08-09 21:25:10] 📌 [6/7] Competência 202606
[2026-08-09 21:25:10] 🔁 202606 | tentativa 1/3
[2026-08-09 21:25:10] ⬇️ Iniciando download temporário de 202606: https://portaldatransparencia.gov.br/download-de-dados/cpgf/202606
[2026-08-09 21:25:11] 🌐 HTTP 200 | Content-Type: application/x-zip-compressed | Content-Length: 377831
[2026-08-09 21:25:11] 📦 Arquivo recebido: 0.36 MB
[2026-08-09 21:25:11] ✅ ZIP válido recebido para 202606.
[2026-08-09 21:25:11] ✅ CSV salvo: 202606_CPGF.csv (4.95 MB)
[2026-08-09 21:25:11] 🧹 ZIP temporário apagado: 202606_CPGF.zip
[2026-08-09 21:25:11] 🎉 Competência concluída: 202606
[2026-08-09 21:25:11] 😴 Aguardando 42s antes da próxima requisição...
[2026-08-09 21:25:53] 📌 [7/7] Competência 202607
[2026-08-09 21:25:53] ⏭️ 202607: CSV já existe. Nada a fazer.
[2026-08-09 21:25:53] 📊 Resumo do bloco: 7 concluída(s), 0 falha(s), 0 bloqueio(s).

{'concluidas': ['202601',
  '202602',
  '202603',
  '202604',
  '202605',
  '202606',
  '202607'],
 'falhas': [],
 'bloqueadas': []}

## 7️⃣ 🛡️ Recuperação das competências ausentes

Esta é a célula específica para situações em que o Portal da Transparência apresenta comportamento de proteção antirrobô.

Ela:

- identifica somente os meses que ainda não possuem CSV;
- renova a sessão HTTP antes da recuperação;
- usa novas tentativas;
- adota pausas aleatórias mais longas;
- diante de HTML/HTTP 403/429, aguarda de **3 a 5 minutos** antes de seguir;
- não insiste indefinidamente no mesmo mês.

> Se o Portal exigir CAPTCHA, JavaScript ou outra validação interativa, utilize a etapa de download manual. O notebook não tenta contornar esses mecanismos.

In [10]:
def listar_competencias_ausentes(
    competencia_inicial: str = COMPETENCIA_INICIAL,
    competencia_final: str = COMPETENCIA_FINAL
) -> List[str]:
    """Retorna as competências sem CSV válido no Google Drive."""
    ausentes = []

    for competencia in gerar_competencias(
        competencia_inicial,
        competencia_final
    ):
        csv_path = caminho_csv_esperado(competencia)

        if not csv_path.exists() or csv_path.stat().st_size == 0:
            ausentes.append(competencia)

    return ausentes


def executar_bloco_recuperacao(
    competencia_inicial: str = COMPETENCIA_INICIAL,
    competencia_final: str = COMPETENCIA_FINAL,
    limite_meses: Optional[int] = None
) -> None:
    """
    Tenta novamente apenas as competências ausentes.

    Ao detectar proteção do Portal:
    - renova a sessão;
    - espera de 3 a 5 minutos;
    - continua para a próxima competência ausente.
    """
    competencias = listar_competencias_ausentes(
        competencia_inicial,
        competencia_final
    )

    if limite_meses is not None:
        competencias = competencias[:limite_meses]

    if not competencias:
        log('✅ Não há competências remanescentes.')
        return

    renovar_sessao()

    log('🛡️ Iniciando recuperação das competências remanescentes.')
    log(f'📌 Total nesta execução: {len(competencias)}')

    concluidas = []
    falhas = []
    bloqueadas = []

    for i, competencia in enumerate(competencias, start=1):
        log(f'📌 [Recuperação {i}/{len(competencias)}] {competencia}')

        try:
            sucesso = processar_mes(
                competencia,
                max_tentativas=MAX_TENTATIVAS,
                espera_progressiva_base=90
            )

            if sucesso:
                concluidas.append(competencia)
            else:
                falhas.append(competencia)

        except (PortalRetornouHTML, PortalBloqueioTemporario) as e:
            bloqueadas.append(competencia)
            log(f'🚧 {competencia} ainda encontrou proteção do Portal: {e}')

            renovar_sessao()

            pausa_aleatoria(
                minimo=PAUSA_HTML_MIN_SEGUNDOS,
                maximo=PAUSA_HTML_MAX_SEGUNDOS,
                motivo='antes de seguir para outra competência ausente'
            )

            continue

        except Exception as e:
            falhas.append(competencia)
            log(f'❌ Erro inesperado em {competencia}: {repr(e)}')

        if i < len(competencias):
            pausa_aleatoria(
                minimo=45,
                maximo=90,
                motivo='antes da próxima competência remanescente'
            )

    ainda_ausentes = listar_competencias_ausentes(
        competencia_inicial,
        competencia_final
    )

    print('\\n' + '=' * 80)
    print('📊 RESUMO DA RECUPERAÇÃO')
    print('=' * 80)
    print(f'✅ Concluídas nesta execução: {len(concluidas)}')
    print(f'❌ Falhas comuns: {len(falhas)}')
    print(f'🚧 Bloqueadas/HTML: {len(bloqueadas)}')
    print(f'📂 Ainda ausentes: {len(ainda_ausentes)}')

    if ainda_ausentes:
        print('\\n📌 Competências ainda ausentes:')
        print(ainda_ausentes)


# ▶️ Execute quando houver competências ausentes.
executar_bloco_recuperacao(
    competencia_inicial=COMPETENCIA_INICIAL,
    competencia_final=COMPETENCIA_FINAL,
    limite_meses=None
)

[2026-08-09 23:15:40] ✅ Não há competências remanescentes.

## 8️⃣ Gerar links para download manual das competências ausentes

Se o Portal funcionar normalmente no navegador, mas bloquear as requisições do Colab, esta célula cria uma lista de links somente para os meses que continuam ausentes.

Os arquivos de apoio são gravados na pasta `logs`.

Os ZIPs baixados manualmente **não precisam ser salvos no Google Drive**. Na etapa seguinte, eles podem ser enviados diretamente ao armazenamento temporário do Colab e serão apagados após a extração.

In [11]:
competencias_para_download_manual = listar_competencias_ausentes(
    COMPETENCIA_INICIAL,
    COMPETENCIA_FINAL
)

html_path = LOG_DIR / 'links_download_manual_cpgf.html'
txt_path = LOG_DIR / 'links_download_manual_cpgf.txt'

if not competencias_para_download_manual:
    print('✅ Não há competências ausentes. Nenhum arquivo de links foi gerado.')

else:
    linhas_html = [
        '<!DOCTYPE html>',
        '<html lang="pt-BR">',
        '<head><meta charset="utf-8"><title>Links CPGF</title></head>',
        '<body>',
        '<h1>Links de download manual — CPGF</h1>',
        '<p>Use estes links somente quando o download automatizado pelo Colab não funcionar.</p>',
        '<ul>'
    ]

    linhas_txt = []

    for comp in competencias_para_download_manual:
        url = f'{BASE_URL}/{comp}'
        linhas_html.append(
            f'<li><a href="{url}" target="_blank">{comp}</a></li>'
        )
        linhas_txt.append(url)

    linhas_html.extend(['</ul>', '</body>', '</html>'])

    html_path.write_text(
        '\\n'.join(linhas_html),
        encoding='utf-8'
    )

    txt_path.write_text(
        '\\n'.join(linhas_txt),
        encoding='utf-8'
    )

    print(f'✅ HTML criado: {html_path}')
    print(f'✅ TXT criado: {txt_path}')
    print(f'📌 Total de links: {len(competencias_para_download_manual)}')
    print(competencias_para_download_manual)

✅ Não há competências ausentes. Nenhum arquivo de links foi gerado.

## 9️⃣ Alternativa segura — enviar ZIPs manualmente ao Colab

Use esta etapa apenas se o download automatizado continuar bloqueado.

### Procedimento

1. baixe pelo navegador os ZIPs correspondentes às competências ausentes;
2. execute a célula abaixo;
3. selecione um ou mais ZIPs no seu computador;
4. os arquivos serão enviados para `/content/cpgf_zips_manuais`;
5. o CSV será extraído diretamente para o Google Drive;
6. o ZIP temporário será apagado.

Assim, nenhum arquivo compactado permanece no Drive.

In [ ]:
from google.colab import files


def competencia_a_partir_do_nome(nome_arquivo: str) -> Optional[str]:
    """Tenta identificar AAAAMM no nome do arquivo."""
    m = re.search(r'(20\d{2}(0[1-9]|1[0-2]))', nome_arquivo)
    return m.group(1) if m else None


def enviar_e_extrair_zips_manuais() -> None:
    """Recebe ZIPs pelo navegador do Colab, extrai os CSVs e apaga os ZIPs."""
    MANUAL_ZIP_DIR.mkdir(parents=True, exist_ok=True)

    # Limpa resíduos de uma execução anterior.
    for arquivo in MANUAL_ZIP_DIR.iterdir():
        if arquivo.is_file():
            arquivo.unlink()

    print('📤 Selecione um ou mais ZIPs baixados manualmente do Portal.')
    uploaded = files.upload()

    if not uploaded:
        print('⚠️ Nenhum arquivo foi enviado.')
        return

    zips_recebidos = []

    for nome, conteudo in uploaded.items():
        destino = MANUAL_ZIP_DIR / Path(nome).name
        destino.write_bytes(conteudo)
        zips_recebidos.append(destino)

    print(f'📦 Arquivos recebidos: {len(zips_recebidos)}')

    for zip_path in zips_recebidos:
        competencia = competencia_a_partir_do_nome(zip_path.name)

        if not competencia:
            log(
                f'⚠️ Não foi possível identificar AAAAMM no nome: '
                f'{zip_path.name}'
            )
            continue

        try:
            extrair_csv_do_zip(
                zip_path,
                competencia=competencia,
                apagar_zip=True
            )

        except Exception as e:
            log(f'❌ Falha na extração manual de {zip_path.name}: {repr(e)}')

    # Limpeza final.
    for arquivo in MANUAL_ZIP_DIR.iterdir():
        if arquivo.is_file():
            try:
                arquivo.unlink()
            except Exception:
                pass

    print('🧹 Limpeza dos ZIPs temporários concluída.')


# ▶️ Execute somente se precisar do procedimento manual.
# enviar_e_extrair_zips_manuais()

## 🔟 Conferência dos 163 arquivos mensais

Esta etapa verifica:

- quantas competências deveriam existir;
- quantas estão presentes;
- quais ainda estão ausentes;
- tamanho individual dos arquivos;
- volume total armazenado.

Ela gera o arquivo:

`logs/controle_arquivos_cpgf.csv`

A contagem detalhada de registros de cada CSV será produzida durante a consolidação, evitando uma leitura completa duplicada dos 163 arquivos.

In [8]:
def gerar_controle_arquivos(
    competencia_inicial: str = COMPETENCIA_INICIAL,
    competencia_final: str = COMPETENCIA_FINAL
) -> List[Dict[str, object]]:
    """Gera o controle das competências mensais presentes e ausentes."""
    competencias = gerar_competencias(
        competencia_inicial,
        competencia_final
    )

    controle = []

    for comp in competencias:
        csv_path = caminho_csv_esperado(comp)
        existe = csv_path.exists() and csv_path.stat().st_size > 0
        tamanho_bytes = csv_path.stat().st_size if existe else 0

        controle.append({
            'competencia': comp,
            'arquivo_esperado': csv_path.name,
            'status': 'presente' if existe else 'ausente',
            'tamanho_bytes': tamanho_bytes,
            'tamanho_mb': round(tamanho_bytes / (1024 ** 2), 2),
            'caminho': str(csv_path),
        })

    with open(
        CONTROLE_ARQUIVOS_CSV,
        'w',
        encoding='utf-8-sig',
        newline=''
    ) as f:

        campos = [
            'competencia',
            'arquivo_esperado',
            'status',
            'tamanho_bytes',
            'tamanho_mb',
            'caminho',
        ]

        escritor = csv.DictWriter(
            f,
            fieldnames=campos,
            delimiter=';'
        )

        escritor.writeheader()
        escritor.writerows(controle)

    return controle


controle = gerar_controle_arquivos()

presentes = [
    r for r in controle
    if r['status'] == 'presente'
]

ausentes = [
    r['competencia'] for r in controle
    if r['status'] == 'ausente'
]

tamanho_total_bytes = sum(
    r['tamanho_bytes'] for r in controle
)

tamanho_total_gb = tamanho_total_bytes / (1024 ** 3)

print(f'✅ CSVs presentes: {len(presentes)} de {len(controle)}')
print(f'❌ CSVs ausentes: {len(ausentes)}')
print(f'💾 Volume aproximado: {tamanho_total_gb:.2f} GB')
print(f'🧾 Arquivo de controle: {CONTROLE_ARQUIVOS_CSV}')

if ausentes:
    print('\\n📌 Competências ausentes:')
    print(ausentes)
else:
    print('\\n🎉 Todas as 163 competências foram localizadas.')

✅ CSVs presentes: 163 de 163
❌ CSVs ausentes: 0
💾 Volume aproximado: 0.49 GB
🧾 Arquivo de controle: /content/drive/MyDrive/Suprimentos de Fundos - CPGF/logs/controle_arquivos_cpgf.csv
\n🎉 Todas as 163 competências foram localizadas.

## 1️⃣1️⃣ Verificar os cabeçalhos antes da consolidação

Antes de unir os dados, esta célula percorre os 163 arquivos **sem carregar o conteúdo completo** e compara os cabeçalhos.

A saída mostra:

- codificação detectada;
- separador;
- quantidade de colunas;
- diferenças em relação à amostra de julho/2026;
- quantidade de esquemas distintos encontrada no período.

O relatório completo é salvo em:

`logs/relatorio_esquemas_cpgf.csv`

Se houver alguma diferença histórica de estrutura, ela será registrada. A consolidação posterior fará a união flexível pelo **nome da coluna**.

In [5]:
def analisar_esquemas_periodo() -> List[Dict[str, object]]:
    """Analisa os cabeçalhos de todos os CSVs disponíveis."""
    resultados = []

    for comp in COMPETENCIAS_ESPERADAS:
        caminho = caminho_csv_esperado(comp)

        if not caminho.exists() or caminho.stat().st_size == 0:
            continue

        try:
            info = validar_estrutura_csv(caminho)

            resultados.append({
                'competencia': comp,
                'arquivo': caminho.name,
                'encoding': info['encoding'],
                'separador': info['separador'],
                'numero_colunas': info['numero_colunas'],
                'igual_referencia_conjunto': info['igual_referencia_conjunto'],
                'igual_referencia_ordem': info['igual_referencia_ordem'],
                'colunas_ausentes': ' | '.join(info['colunas_ausentes']),
                'colunas_extras': ' | '.join(info['colunas_extras']),
                'assinatura_esquema': ' || '.join(info['cabecalho']),
                'cabecalho': info['cabecalho'],
            })

        except Exception as e:
            log(f'❌ Erro ao ler cabeçalho de {caminho.name}: {repr(e)}')

    # Relatório tabular sem a lista Python do cabeçalho.
    with open(
        RELATORIO_ESQUEMAS_CSV,
        'w',
        encoding='utf-8-sig',
        newline=''
    ) as f:

        campos = [
            'competencia',
            'arquivo',
            'encoding',
            'separador',
            'numero_colunas',
            'igual_referencia_conjunto',
            'igual_referencia_ordem',
            'colunas_ausentes',
            'colunas_extras',
            'assinatura_esquema',
        ]

        escritor = csv.DictWriter(
            f,
            fieldnames=campos,
            delimiter=';'
        )

        escritor.writeheader()

        for item in resultados:
            escritor.writerow({
                chave: item[chave]
                for chave in campos
            })

    return resultados


resultados_esquemas = analisar_esquemas_periodo()

assinaturas = {}

for item in resultados_esquemas:
    assinatura = item['assinatura_esquema']
    assinaturas.setdefault(assinatura, []).append(item['competencia'])

print(f'✅ Arquivos analisados: {len(resultados_esquemas)}')
print(f'🧩 Esquemas distintos encontrados: {len(assinaturas)}')
print(f'🧾 Relatório: {RELATORIO_ESQUEMAS_CSV}')

for i, (assinatura, competencias) in enumerate(
    assinaturas.items(),
    start=1
):
    print('\\n' + '-' * 80)
    print(f'🧩 Esquema {i}')
    print(f'📆 Competências: {len(competencias)}')
    print(f'🔎 Primeiras competências: {competencias[:10]}')

    colunas = assinatura.split(' || ')
    print(f'📋 Colunas ({len(colunas)}):')
    for coluna in colunas:
        print(f'  - {coluna}')

divergentes = [
    item for item in resultados_esquemas
    if not item['igual_referencia_conjunto']
]

if divergentes:
    print(
        f'\\n⚠️ {len(divergentes)} arquivo(s) possuem conjunto de colunas '
        'diferente da referência 202607.'
    )
else:
    print(
        '\\n🎉 Todos os arquivos analisados possuem o mesmo conjunto de '
        'colunas da referência 202607.'
    )

✅ Arquivos analisados: 163
🧩 Esquemas distintos encontrados: 1
🧾 Relatório: /content/drive/MyDrive/Suprimentos de Fundos - CPGF/logs/relatorio_esquemas_cpgf.csv
\n--------------------------------------------------------------------------------
🧩 Esquema 1
📆 Competências: 163
🔎 Primeiras competências: ['201301', '201302', '201303', '201304', '201305', '201306', '201307', '201308', '201309', '201310']
📋 Colunas (15):
  - CÓDIGO ÓRGÃO SUPERIOR
  - NOME ÓRGÃO SUPERIOR
  - CÓDIGO ÓRGÃO
  - NOME ÓRGÃO
  - CÓDIGO UNIDADE GESTORA
  - NOME UNIDADE GESTORA
  - ANO EXTRATO
  - MÊS EXTRATO
  - CPF PORTADOR
  - NOME PORTADOR
  - CNPJ OU CPF FAVORECIDO
  - NOME FAVORECIDO
  - TRANSAÇÃO
  - DATA TRANSAÇÃO
  - VALOR TRANSAÇÃO
\n🎉 Todos os arquivos analisados possuem o mesmo conjunto de colunas da referência 202607.

## 1️⃣2️⃣ Consolidar todos os CSVs em um único arquivo

Esta etapa cria:

`dados_consolidado/CPGF_201301_a_202607.csv`

### 🧩 Estratégia adotada

A consolidação é feita **incrementalmente**, arquivo a arquivo e em blocos de linhas. Isso evita carregar toda a série histórica na memória do Colab.

Os dados mensais são preservados como texto durante a leitura para evitar conversões indesejadas de códigos, CPFs, CNPJs ou valores monetários.

Duas colunas técnicas são acrescentadas **somente ao arquivo consolidado**:

- `COMPETENCIA_ARQUIVO`: período `AAAAMM` correspondente ao arquivo de origem;
- `ARQUIVO_ORIGEM`: nome do CSV mensal de onde a linha foi lida.

> `COMPETENCIA_ARQUIVO` representa o período do arquivo/extrato e não deve ser confundida com `DATA TRANSAÇÃO`.

### 🔄 Diferenças de estrutura

Antes de iniciar a escrita, o notebook identifica a união de todas as colunas existentes. Caso algum arquivo histórico tenha uma coluna extra ou ausente:

- nenhuma coluna é descartada;
- as colunas são alinhadas pelo nome;
- campos inexistentes naquele mês são preenchidos com vazio.

O arquivo final é gravado em **UTF-8-SIG**, separado por `;`.

In [6]:
# ============================================================
# 🧩 CONSOLIDAÇÃO DOS ARQUIVOS MENSAIS DO CPGF
# ============================================================

def obter_colunas_unificadas(
    caminhos_csv: List[Path]
) -> List[str]:
    """
    Cria a ordem final das colunas.

    Começa pela estrutura de referência de 202607 e acrescenta,
    na ordem em que aparecem, quaisquer colunas históricas extras.
    """

    colunas_finais = list(COLUNAS_REFERENCIA_202607)

    for caminho in caminhos_csv:
        cabecalho, _, _ = ler_cabecalho_csv(caminho)

        for coluna in cabecalho:
            if coluna not in colunas_finais:
                colunas_finais.append(coluna)

    # Colunas técnicas ficam sempre no final.
    for tecnica in [
        'COMPETENCIA_ARQUIVO',
        'ARQUIVO_ORIGEM'
    ]:
        if tecnica not in colunas_finais:
            colunas_finais.append(tecnica)

    return colunas_finais


def consolidar_cpgf(
    competencia_inicial: str = COMPETENCIA_INICIAL,
    competencia_final: str = COMPETENCIA_FINAL,
    chunksize: int = CHUNKSIZE_CONSOLIDACAO,
    exigir_todos: bool = EXIGIR_TODAS_COMPETENCIAS_PARA_CONSOLIDAR
) -> Tuple[Path, pd.DataFrame]:
    """
    Consolida os CSVs mensais de forma incremental.

    O método:
    - preserva os CSVs mensais;
    - não remove duplicidades;
    - lê todas as colunas como string;
    - faz união flexível por nome de coluna;
    - acrescenta colunas técnicas de rastreabilidade;
    - grava UTF-8-SIG com separador ';';
    - utiliza quebra real de linha entre os registros;
    - registra quantidade de linhas por arquivo.
    """

    # ========================================================
    # 📆 Lista das competências
    # ========================================================

    competencias = gerar_competencias(
        competencia_inicial,
        competencia_final
    )

    caminhos = []
    ausentes = []

    for comp in competencias:

        caminho = caminho_csv_esperado(comp)

        if caminho.exists() and caminho.stat().st_size > 0:
            caminhos.append((comp, caminho))
        else:
            ausentes.append(comp)

    # ========================================================
    # ⚠️ Verificação de competências ausentes
    # ========================================================

    if ausentes and exigir_todos:
        raise FileNotFoundError(
            'A consolidação foi interrompida porque ainda há '
            f'{len(ausentes)} competência(s) ausente(s): {ausentes}'
        )

    if not caminhos:
        raise FileNotFoundError(
            'Nenhum CSV mensal foi localizado para consolidação.'
        )

    # ========================================================
    # 🧩 Estrutura final das colunas
    # ========================================================

    colunas_finais = obter_colunas_unificadas(
        [caminho for _, caminho in caminhos]
    )

    # ========================================================
    # 📁 Caminho do arquivo consolidado
    # ========================================================

    saida = (
        CONSOLIDADO_DIR
        / f'CPGF_{competencia_inicial}_a_{competencia_final}.csv'
    )

    # Remove uma versão anterior, caso exista.
    if saida.exists():
        saida.unlink()
        log(
            f'🗑️ Consolidado anterior removido: '
            f'{saida.name}'
        )

    # ========================================================
    # 📊 Variáveis de controle
    # ========================================================

    relatorio = []

    total_linhas = 0

    escreveu_cabecalho = False

    log('🧩 Iniciando consolidação incremental.')
    log(
        f'📄 Arquivos mensais considerados: '
        f'{len(caminhos)}'
    )
    log(
        f'📋 Colunas finais: '
        f'{len(colunas_finais)}'
    )
    log(
        f'💾 Destino: '
        f'{saida}'
    )

    # ========================================================
    # 💾 Escrita incremental do consolidado
    # ========================================================

    # O arquivo permanece aberto durante toda a consolidação,
    # evitando múltiplas marcas BOM e reduzindo operações
    # repetidas de abertura e fechamento.
    with open(
        saida,
        'w',
        encoding='utf-8-sig',
        newline=''
    ) as arquivo_saida:

        for i, (comp, caminho) in enumerate(
            caminhos,
            start=1
        ):

            # ------------------------------------------------
            # 🔎 Identifica estrutura do arquivo mensal
            # ------------------------------------------------

            cabecalho, encoding, separador = (
                ler_cabecalho_csv(caminho)
            )

            linhas_arquivo = 0

            inicio = time.time()

            log(
                f'📌 [{i}/{len(caminhos)}] '
                f'Consolidando {caminho.name} | '
                f'encoding={encoding} | '
                f'sep={repr(separador)}'
            )

            # ------------------------------------------------
            # 📖 Leitura incremental
            # ------------------------------------------------

            leitor_chunks = pd.read_csv(
                caminho,
                sep=separador,
                encoding=encoding,
                dtype=str,
                keep_default_na=False,
                na_filter=False,
                chunksize=chunksize,
                on_bad_lines='error',
            )

            for chunk in leitor_chunks:

                # --------------------------------------------
                # 🧹 Remove eventual BOM residual
                # --------------------------------------------

                if len(chunk.columns) > 0:

                    primeiro = chunk.columns[0]

                    if primeiro.startswith('\ufeff'):
                        chunk = chunk.rename(
                            columns={
                                primeiro:
                                primeiro.lstrip('\ufeff')
                            }
                        )

                # --------------------------------------------
                # 🏷️ Colunas técnicas de rastreabilidade
                # --------------------------------------------

                chunk['COMPETENCIA_ARQUIVO'] = comp

                chunk['ARQUIVO_ORIGEM'] = (
                    caminho.name
                )

                # --------------------------------------------
                # 🧩 União flexível por nome de coluna
                # --------------------------------------------

                chunk = chunk.reindex(
                    columns=colunas_finais,
                    fill_value=''
                )

                # --------------------------------------------
                # 💾 Escrita no CSV consolidado
                # --------------------------------------------

                chunk.to_csv(
                    arquivo_saida,
                    sep=';',
                    index=False,
                    header=not escreveu_cabecalho,

                    # ✅ CORREÇÃO:
                    # quebra REAL de linha entre registros
                    lineterminator='\n',

                    quoting=csv.QUOTE_MINIMAL
                )

                escreveu_cabecalho = True

                # --------------------------------------------
                # 📊 Contagem das linhas
                # --------------------------------------------

                n = len(chunk)

                linhas_arquivo += n
                total_linhas += n

            # ------------------------------------------------
            # ⏱️ Estatísticas da competência
            # ------------------------------------------------

            duracao = time.time() - inicio

            relatorio.append({
                'competencia': comp,
                'arquivo': caminho.name,

                'tamanho_mb': round(
                    caminho.stat().st_size
                    / (1024 ** 2),
                    2
                ),

                'encoding_detectado': encoding,

                'separador_detectado':
                    repr(separador),

                'numero_colunas_origem':
                    len(cabecalho),

                'numero_linhas':
                    linhas_arquivo,

                'duracao_segundos':
                    round(duracao, 2),

                'status':
                    'consolidado',
            })

            log(
                f'✅ {comp}: '
                f'{linhas_arquivo:,} linha(s) '
                f'em {duracao:.1f}s.'
            )

    # ========================================================
    # 🧾 Relatório da consolidação
    # ========================================================

    df_relatorio = pd.DataFrame(relatorio)

    df_relatorio.to_csv(
        RELATORIO_CONSOLIDACAO_CSV,
        sep=';',
        index=False,
        encoding='utf-8-sig',

        # Também deixa explícita a quebra de linha correta.
        lineterminator='\n'
    )

    # ========================================================
    # 📦 Estatísticas finais
    # ========================================================

    tamanho_final_gb = (
        saida.stat().st_size
        / (1024 ** 3)
    )

    log('🎉 Consolidação concluída.')

    log(
        f'📊 Total de linhas de dados: '
        f'{total_linhas:,}'
    )

    log(
        f'💾 Tamanho do consolidado: '
        f'{tamanho_final_gb:.2f} GB'
    )

    log(
        f'🧾 Relatório: '
        f'{RELATORIO_CONSOLIDACAO_CSV}'
    )

    return saida, df_relatorio


# ============================================================
# ▶️ EXECUTAR A CONSOLIDAÇÃO
# ============================================================

caminho_consolidado, relatorio_consolidacao = (
    consolidar_cpgf()
)


# ============================================================
# 📄 RESULTADO
# ============================================================

print('\n' + '=' * 80)
print('📄 ARQUIVO CONSOLIDADO')
print('=' * 80)

print(caminho_consolidado)


print('\n' + '=' * 80)
print('📊 RESUMO DAS PRIMEIRAS COMPETÊNCIAS')
print('=' * 80)

display(
    relatorio_consolidacao.head()
)


# ============================================================
# 🔎 TESTE RÁPIDO DAS QUEBRAS DE LINHA
# ============================================================

print('\n' + '=' * 80)
print('🔎 TESTE DAS PRIMEIRAS LINHAS FÍSICAS DO CSV')
print('=' * 80)

with open(
    caminho_consolidado,
    'r',
    encoding='utf-8-sig'
) as f:

    for numero_linha in range(1, 4):

        linha = f.readline()

        print(
            f'\nLinha {numero_linha}:'
        )

        print(
            repr(linha[:300])
        )


print(
    '\n✅ Se foram exibidas três linhas diferentes, '
    'o arquivo possui as quebras de linha corretamente.'
)

[2026-08-09 23:13:38] 🧩 Iniciando consolidação incremental.
[2026-08-09 23:13:38] 📄 Arquivos mensais considerados: 163
[2026-08-09 23:13:38] 📋 Colunas finais: 17
[2026-08-09 23:13:38] 💾 Destino: /content/drive/MyDrive/Suprimentos de Fundos - CPGF/dados_consolidado/CPGF_201301_a_202607.csv
[2026-08-09 23:13:38] 📌 [1/163] Consolidando 201301_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:38] ✅ 201301: 17,550 linha(s) em 0.2s.
[2026-08-09 23:13:38] 📌 [2/163] Consolidando 201302_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:38] ✅ 201302: 3,310 linha(s) em 0.0s.
[2026-08-09 23:13:38] 📌 [3/163] Consolidando 201303_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:39] ✅ 201303: 9,473 linha(s) em 0.1s.
[2026-08-09 23:13:39] 📌 [4/163] Consolidando 201304_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:39] ✅ 201304: 16,190 linha(s) em 0.2s.
[2026-08-09 23:13:39] 📌 [5/163] Consolidando 201305_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:39] ✅ 201305: 19,377 linha(s) em 0.3s.
[2026-08-09 23:13:39] 📌 [6/163] Consolidando 201306_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:39] ✅ 201306: 15,470 linha(s) em 0.2s.
[2026-08-09 23:13:39] 📌 [7/163] Consolidando 201307_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:39] ✅ 201307: 18,587 linha(s) em 0.2s.
[2026-08-09 23:13:39] 📌 [8/163] Consolidando 201308_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:40] ✅ 201308: 18,725 linha(s) em 0.2s.
[2026-08-09 23:13:40] 📌 [9/163] Consolidando 201309_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:40] ✅ 201309: 17,276 linha(s) em 0.2s.
[2026-08-09 23:13:40] 📌 [10/163] Consolidando 201310_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:40] ✅ 201310: 18,057 linha(s) em 0.2s.
[2026-08-09 23:13:40] 📌 [11/163] Consolidando 201311_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:40] ✅ 201311: 18,633 linha(s) em 0.2s.
[2026-08-09 23:13:40] 📌 [12/163] Consolidando 201312_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:41] ✅ 201312: 18,843 linha(s) em 0.2s.
[2026-08-09 23:13:41] 📌 [13/163] Consolidando 201401_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:41] ✅ 201401: 14,542 linha(s) em 0.2s.
[2026-08-09 23:13:41] 📌 [14/163] Consolidando 201402_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:41] ✅ 201402: 2,698 linha(s) em 0.0s.
[2026-08-09 23:13:41] 📌 [15/163] Consolidando 201403_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:41] ✅ 201403: 10,214 linha(s) em 0.1s.
[2026-08-09 23:13:41] 📌 [16/163] Consolidando 201404_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:41] ✅ 201404: 13,807 linha(s) em 0.2s.
[2026-08-09 23:13:41] 📌 [17/163] Consolidando 201405_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:41] ✅ 201405: 15,068 linha(s) em 0.2s.
[2026-08-09 23:13:41] 📌 [18/163] Consolidando 201406_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:41] ✅ 201406: 16,575 linha(s) em 0.2s.
[2026-08-09 23:13:42] 📌 [19/163] Consolidando 201407_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:42] ✅ 201407: 17,044 linha(s) em 0.2s.
[2026-08-09 23:13:42] 📌 [20/163] Consolidando 201408_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:42] ✅ 201408: 14,854 linha(s) em 0.2s.
[2026-08-09 23:13:42] 📌 [21/163] Consolidando 201409_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:42] ✅ 201409: 16,880 linha(s) em 0.2s.
[2026-08-09 23:13:42] 📌 [22/163] Consolidando 201410_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:42] ✅ 201410: 16,389 linha(s) em 0.2s.
[2026-08-09 23:13:42] 📌 [23/163] Consolidando 201411_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:43] ✅ 201411: 18,408 linha(s) em 0.2s.
[2026-08-09 23:13:43] 📌 [24/163] Consolidando 201412_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:43] ✅ 201412: 19,099 linha(s) em 0.2s.
[2026-08-09 23:13:43] 📌 [25/163] Consolidando 201501_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:43] ✅ 201501: 13,908 linha(s) em 0.2s.
[2026-08-09 23:13:43] 📌 [26/163] Consolidando 201502_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:43] ✅ 201502: 1,888 linha(s) em 0.0s.
[2026-08-09 23:13:43] 📌 [27/163] Consolidando 201503_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:43] ✅ 201503: 7,870 linha(s) em 0.1s.
[2026-08-09 23:13:43] 📌 [28/163] Consolidando 201504_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:43] ✅ 201504: 14,484 linha(s) em 0.2s.
[2026-08-09 23:13:43] 📌 [29/163] Consolidando 201505_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:43] ✅ 201505: 12,807 linha(s) em 0.1s.
[2026-08-09 23:13:43] 📌 [30/163] Consolidando 201506_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:44] ✅ 201506: 14,354 linha(s) em 0.2s.
[2026-08-09 23:13:44] 📌 [31/163] Consolidando 201507_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:44] ✅ 201507: 14,387 linha(s) em 0.2s.
[2026-08-09 23:13:44] 📌 [32/163] Consolidando 201508_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:44] ✅ 201508: 13,514 linha(s) em 0.2s.
[2026-08-09 23:13:44] 📌 [33/163] Consolidando 201509_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:44] ✅ 201509: 13,720 linha(s) em 0.2s.
[2026-08-09 23:13:44] 📌 [34/163] Consolidando 201510_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:44] ✅ 201510: 13,166 linha(s) em 0.2s.
[2026-08-09 23:13:44] 📌 [35/163] Consolidando 201511_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:44] ✅ 201511: 14,278 linha(s) em 0.2s.
[2026-08-09 23:13:45] 📌 [36/163] Consolidando 201512_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:45] ✅ 201512: 15,866 linha(s) em 0.2s.
[2026-08-09 23:13:45] 📌 [37/163] Consolidando 201601_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:45] ✅ 201601: 12,115 linha(s) em 0.1s.
[2026-08-09 23:13:45] 📌 [38/163] Consolidando 201602_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:45] ✅ 201602: 1,629 linha(s) em 0.0s.
[2026-08-09 23:13:45] 📌 [39/163] Consolidando 201603_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:45] ✅ 201603: 6,970 linha(s) em 0.1s.
[2026-08-09 23:13:45] 📌 [40/163] Consolidando 201604_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:45] ✅ 201604: 13,019 linha(s) em 0.1s.
[2026-08-09 23:13:45] 📌 [41/163] Consolidando 201605_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:45] ✅ 201605: 12,485 linha(s) em 0.1s.
[2026-08-09 23:13:45] 📌 [42/163] Consolidando 201606_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:45] ✅ 201606: 13,512 linha(s) em 0.2s.
[2026-08-09 23:13:45] 📌 [43/163] Consolidando 201607_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:46] ✅ 201607: 13,159 linha(s) em 0.1s.
[2026-08-09 23:13:46] 📌 [44/163] Consolidando 201608_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:46] ✅ 201608: 13,172 linha(s) em 0.2s.
[2026-08-09 23:13:46] 📌 [45/163] Consolidando 201609_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:46] ✅ 201609: 14,227 linha(s) em 0.2s.
[2026-08-09 23:13:46] 📌 [46/163] Consolidando 201610_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:46] ✅ 201610: 12,316 linha(s) em 0.1s.
[2026-08-09 23:13:46] 📌 [47/163] Consolidando 201611_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:46] ✅ 201611: 12,214 linha(s) em 0.1s.
[2026-08-09 23:13:46] 📌 [48/163] Consolidando 201612_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:46] ✅ 201612: 13,423 linha(s) em 0.2s.
[2026-08-09 23:13:46] 📌 [49/163] Consolidando 201701_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:47] ✅ 201701: 10,927 linha(s) em 0.1s.
[2026-08-09 23:13:47] 📌 [50/163] Consolidando 201702_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:47] ✅ 201702: 1,586 linha(s) em 0.0s.
[2026-08-09 23:13:47] 📌 [51/163] Consolidando 201703_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:47] ✅ 201703: 7,632 linha(s) em 0.1s.
[2026-08-09 23:13:47] 📌 [52/163] Consolidando 201704_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:47] ✅ 201704: 11,769 linha(s) em 0.1s.
[2026-08-09 23:13:47] 📌 [53/163] Consolidando 201705_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:47] ✅ 201705: 10,558 linha(s) em 0.1s.
[2026-08-09 23:13:47] 📌 [54/163] Consolidando 201706_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:47] ✅ 201706: 12,841 linha(s) em 0.2s.
[2026-08-09 23:13:47] 📌 [55/163] Consolidando 201707_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:47] ✅ 201707: 12,585 linha(s) em 0.1s.
[2026-08-09 23:13:47] 📌 [56/163] Consolidando 201708_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:47] ✅ 201708: 11,473 linha(s) em 0.1s.
[2026-08-09 23:13:47] 📌 [57/163] Consolidando 201709_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:48] ✅ 201709: 13,271 linha(s) em 0.2s.
[2026-08-09 23:13:48] 📌 [58/163] Consolidando 201710_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:48] ✅ 201710: 13,231 linha(s) em 0.2s.
[2026-08-09 23:13:48] 📌 [59/163] Consolidando 201711_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:48] ✅ 201711: 16,347 linha(s) em 0.2s.
[2026-08-09 23:13:48] 📌 [60/163] Consolidando 201712_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:48] ✅ 201712: 18,154 linha(s) em 0.2s.
[2026-08-09 23:13:48] 📌 [61/163] Consolidando 201801_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:48] ✅ 201801: 13,931 linha(s) em 0.2s.
[2026-08-09 23:13:48] 📌 [62/163] Consolidando 201802_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:49] ✅ 201802: 5,392 linha(s) em 0.1s.
[2026-08-09 23:13:49] 📌 [63/163] Consolidando 201803_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:49] ✅ 201803: 8,204 linha(s) em 0.1s.
[2026-08-09 23:13:49] 📌 [64/163] Consolidando 201804_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:49] ✅ 201804: 13,872 linha(s) em 0.2s.
[2026-08-09 23:13:49] 📌 [65/163] Consolidando 201805_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:49] ✅ 201805: 14,908 linha(s) em 0.2s.
[2026-08-09 23:13:49] 📌 [66/163] Consolidando 201806_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:49] ✅ 201806: 13,401 linha(s) em 0.2s.
[2026-08-09 23:13:49] 📌 [67/163] Consolidando 201807_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:49] ✅ 201807: 11,260 linha(s) em 0.1s.
[2026-08-09 23:13:49] 📌 [68/163] Consolidando 201808_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:49] ✅ 201808: 10,525 linha(s) em 0.1s.
[2026-08-09 23:13:49] 📌 [69/163] Consolidando 201809_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:50] ✅ 201809: 11,773 linha(s) em 0.2s.
[2026-08-09 23:13:50] 📌 [70/163] Consolidando 201810_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:50] ✅ 201810: 11,578 linha(s) em 0.1s.
[2026-08-09 23:13:50] 📌 [71/163] Consolidando 201811_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:50] ✅ 201811: 13,924 linha(s) em 0.2s.
[2026-08-09 23:13:50] 📌 [72/163] Consolidando 201812_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:50] ✅ 201812: 14,234 linha(s) em 0.2s.
[2026-08-09 23:13:50] 📌 [73/163] Consolidando 201901_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:50] ✅ 201901: 8,988 linha(s) em 0.1s.
[2026-08-09 23:13:50] 📌 [74/163] Consolidando 201902_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:50] ✅ 201902: 1,985 linha(s) em 0.0s.
[2026-08-09 23:13:50] 📌 [75/163] Consolidando 201903_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:50] ✅ 201903: 7,129 linha(s) em 0.1s.
[2026-08-09 23:13:50] 📌 [76/163] Consolidando 201904_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:51] ✅ 201904: 8,361 linha(s) em 0.1s.
[2026-08-09 23:13:51] 📌 [77/163] Consolidando 201905_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:51] ✅ 201905: 10,876 linha(s) em 0.1s.
[2026-08-09 23:13:51] 📌 [78/163] Consolidando 201906_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:51] ✅ 201906: 11,708 linha(s) em 0.2s.
[2026-08-09 23:13:51] 📌 [79/163] Consolidando 201907_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:51] ✅ 201907: 9,942 linha(s) em 0.1s.
[2026-08-09 23:13:51] 📌 [80/163] Consolidando 201908_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:51] ✅ 201908: 10,731 linha(s) em 0.1s.
[2026-08-09 23:13:51] 📌 [81/163] Consolidando 201909_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:51] ✅ 201909: 10,306 linha(s) em 0.1s.
[2026-08-09 23:13:51] 📌 [82/163] Consolidando 201910_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:51] ✅ 201910: 10,585 linha(s) em 0.1s.
[2026-08-09 23:13:51] 📌 [83/163] Consolidando 201911_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:52] ✅ 201911: 12,331 linha(s) em 0.1s.
[2026-08-09 23:13:52] 📌 [84/163] Consolidando 201912_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:52] ✅ 201912: 12,501 linha(s) em 0.1s.
[2026-08-09 23:13:52] 📌 [85/163] Consolidando 202001_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:52] ✅ 202001: 8,177 linha(s) em 0.1s.
[2026-08-09 23:13:52] 📌 [86/163] Consolidando 202002_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:52] ✅ 202002: 1,798 linha(s) em 0.0s.
[2026-08-09 23:13:52] 📌 [87/163] Consolidando 202003_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:52] ✅ 202003: 5,728 linha(s) em 0.1s.
[2026-08-09 23:13:52] 📌 [88/163] Consolidando 202004_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:52] ✅ 202004: 7,800 linha(s) em 0.1s.
[2026-08-09 23:13:52] 📌 [89/163] Consolidando 202005_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:52] ✅ 202005: 4,483 linha(s) em 0.1s.
[2026-08-09 23:13:52] 📌 [90/163] Consolidando 202006_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:52] ✅ 202006: 6,316 linha(s) em 0.1s.
[2026-08-09 23:13:52] 📌 [91/163] Consolidando 202007_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:52] ✅ 202007: 6,003 linha(s) em 0.1s.
[2026-08-09 23:13:52] 📌 [92/163] Consolidando 202008_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:52] ✅ 202008: 6,224 linha(s) em 0.1s.
[2026-08-09 23:13:52] 📌 [93/163] Consolidando 202009_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:52] ✅ 202009: 7,199 linha(s) em 0.1s.
[2026-08-09 23:13:52] 📌 [94/163] Consolidando 202010_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:53] ✅ 202010: 7,663 linha(s) em 0.1s.
[2026-08-09 23:13:53] 📌 [95/163] Consolidando 202011_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:53] ✅ 202011: 8,927 linha(s) em 0.1s.
[2026-08-09 23:13:53] 📌 [96/163] Consolidando 202012_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:53] ✅ 202012: 10,368 linha(s) em 0.1s.
[2026-08-09 23:13:53] 📌 [97/163] Consolidando 202101_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:53] ✅ 202101: 7,057 linha(s) em 0.1s.
[2026-08-09 23:13:53] 📌 [98/163] Consolidando 202102_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:53] ✅ 202102: 1,213 linha(s) em 0.0s.
[2026-08-09 23:13:53] 📌 [99/163] Consolidando 202103_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:53] ✅ 202103: 3,725 linha(s) em 0.0s.
[2026-08-09 23:13:53] 📌 [100/163] Consolidando 202104_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:53] ✅ 202104: 5,937 linha(s) em 0.1s.
[2026-08-09 23:13:53] 📌 [101/163] Consolidando 202105_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:53] ✅ 202105: 5,705 linha(s) em 0.1s.
[2026-08-09 23:13:53] 📌 [102/163] Consolidando 202106_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:53] ✅ 202106: 6,443 linha(s) em 0.1s.
[2026-08-09 23:13:53] 📌 [103/163] Consolidando 202107_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:53] ✅ 202107: 7,477 linha(s) em 0.1s.
[2026-08-09 23:13:53] 📌 [104/163] Consolidando 202108_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:53] ✅ 202108: 7,030 linha(s) em 0.1s.
[2026-08-09 23:13:53] 📌 [105/163] Consolidando 202109_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:53] ✅ 202109: 8,608 linha(s) em 0.1s.
[2026-08-09 23:13:53] 📌 [106/163] Consolidando 202110_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:54] ✅ 202110: 8,620 linha(s) em 0.1s.
[2026-08-09 23:13:54] 📌 [107/163] Consolidando 202111_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:54] ✅ 202111: 9,559 linha(s) em 0.1s.
[2026-08-09 23:13:54] 📌 [108/163] Consolidando 202112_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:54] ✅ 202112: 11,611 linha(s) em 0.1s.
[2026-08-09 23:13:54] 📌 [109/163] Consolidando 202201_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:54] ✅ 202201: 8,628 linha(s) em 0.1s.
[2026-08-09 23:13:54] 📌 [110/163] Consolidando 202202_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:54] ✅ 202202: 1,785 linha(s) em 0.0s.
[2026-08-09 23:13:54] 📌 [111/163] Consolidando 202203_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:54] ✅ 202203: 6,092 linha(s) em 0.1s.
[2026-08-09 23:13:54] 📌 [112/163] Consolidando 202204_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:54] ✅ 202204: 9,516 linha(s) em 0.1s.
[2026-08-09 23:13:54] 📌 [113/163] Consolidando 202205_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:54] ✅ 202205: 9,309 linha(s) em 0.1s.
[2026-08-09 23:13:54] 📌 [114/163] Consolidando 202206_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:54] ✅ 202206: 11,649 linha(s) em 0.1s.
[2026-08-09 23:13:54] 📌 [115/163] Consolidando 202207_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:55] ✅ 202207: 12,572 linha(s) em 0.1s.
[2026-08-09 23:13:55] 📌 [116/163] Consolidando 202208_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:55] ✅ 202208: 14,945 linha(s) em 0.2s.
[2026-08-09 23:13:55] 📌 [117/163] Consolidando 202209_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:55] ✅ 202209: 16,004 linha(s) em 0.2s.
[2026-08-09 23:13:55] 📌 [118/163] Consolidando 202210_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:55] ✅ 202210: 14,860 linha(s) em 0.2s.
[2026-08-09 23:13:55] 📌 [119/163] Consolidando 202211_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:55] ✅ 202211: 15,194 linha(s) em 0.2s.
[2026-08-09 23:13:55] 📌 [120/163] Consolidando 202212_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:56] ✅ 202212: 16,057 linha(s) em 0.2s.
[2026-08-09 23:13:56] 📌 [121/163] Consolidando 202301_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:56] ✅ 202301: 10,438 linha(s) em 0.1s.
[2026-08-09 23:13:56] 📌 [122/163] Consolidando 202302_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:56] ✅ 202302: 1,833 linha(s) em 0.0s.
[2026-08-09 23:13:56] 📌 [123/163] Consolidando 202303_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:56] ✅ 202303: 6,441 linha(s) em 0.1s.
[2026-08-09 23:13:56] 📌 [124/163] Consolidando 202304_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:56] ✅ 202304: 11,184 linha(s) em 0.1s.
[2026-08-09 23:13:56] 📌 [125/163] Consolidando 202305_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:56] ✅ 202305: 9,964 linha(s) em 0.1s.
[2026-08-09 23:13:56] 📌 [126/163] Consolidando 202306_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:56] ✅ 202306: 13,509 linha(s) em 0.2s.
[2026-08-09 23:13:56] 📌 [127/163] Consolidando 202307_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:56] ✅ 202307: 11,669 linha(s) em 0.1s.
[2026-08-09 23:13:56] 📌 [128/163] Consolidando 202308_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:57] ✅ 202308: 12,444 linha(s) em 0.1s.
[2026-08-09 23:13:57] 📌 [129/163] Consolidando 202309_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:57] ✅ 202309: 13,495 linha(s) em 0.2s.
[2026-08-09 23:13:57] 📌 [130/163] Consolidando 202310_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:57] ✅ 202310: 12,035 linha(s) em 0.1s.
[2026-08-09 23:13:57] 📌 [131/163] Consolidando 202311_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:57] ✅ 202311: 14,805 linha(s) em 0.2s.
[2026-08-09 23:13:57] 📌 [132/163] Consolidando 202312_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:57] ✅ 202312: 16,305 linha(s) em 0.2s.
[2026-08-09 23:13:57] 📌 [133/163] Consolidando 202401_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:57] ✅ 202401: 9,739 linha(s) em 0.1s.
[2026-08-09 23:13:57] 📌 [134/163] Consolidando 202402_CPGF.csv | encoding=cp1252 | sep=';'
[2026-08-09 23:13:57] ✅ 202402: 2,666 linha(s) em 0.0s.

,competencia,arquivo,tamanho_mb,encoding_detectado,separador_detectado,numero_colunas_origem,numero_linhas,duracao_segundos,status
0,201301,201301_CPGF.csv,5.03,cp1252,';',15,17550,0.22,consolidado
1,201302,201302_CPGF.csv,0.91,cp1252,';',15,3310,0.04,consolidado
2,201303,201303_CPGF.csv,2.64,cp1252,';',15,9473,0.11,consolidado
3,201304,201304_CPGF.csv,4.52,cp1252,';',15,16190,0.19,consolidado
4,201305,201305_CPGF.csv,5.39,cp1252,';',15,19377,0.25,consolidado

================================================================================
🔎 TESTE DAS PRIMEIRAS LINHAS FÍSICAS DO CSV
================================================================================

Linha 1:
'CÓDIGO ÓRGÃO SUPERIOR;NOME ÓRGÃO SUPERIOR;CÓDIGO ÓRGÃO;NOME ÓRGÃO;CÓDIGO UNIDADE GESTORA;NOME UNIDADE GESTORA;ANO EXTRATO;MÊS EXTRATO;CPF PORTADOR;NOME PORTADOR;CNPJ OU CPF FAVORECIDO;NOME FAVORECIDO;TRANSAÇÃO;DATA TRANSAÇÃO;VALOR TRANSAÇÃO;COMPETENCIA_ARQUIVO;ARQUIVO_ORIGEM\n'

Linha 2:
'63000;Advocacia-Geral da União;63000;Advocacia-Geral da União - Unidades com vínculo direto;110161;SUPERINTENDENCIA REG. DE ADMIN. DA 1ª REGIAO;2013;01;***.341.701-**;RAIMUNDO RODRIGUES DE OLIVEIRA;-2;NAO SE APLICA;SAQUE CASH/ATM BB;26/11/2012;100,00;201301;201301_CPGF.csv\n'

Linha 3:
'63000;Advocacia-Geral da União;63000;Advocacia-Geral da União - Unidades com vínculo direto;110161;SUPERINTENDENCIA REG. DE ADMIN. DA 1ª REGIAO;2013;01;***.402.072-**;JAIME BATISTA DE SOUSA;15282700000193;SELCOM MATERIAIS ELETRICOS LTDA;COMPRA A/V - R$ - APRES;04/12/2012;249,48;201301;201301_CPGF.cs'

✅ Se foram exibidas três linhas diferentes, o arquivo possui as quebras de linha corretamente.

## 1️⃣3️⃣ Validação final do conjunto consolidado

A última célula produz uma checagem de integridade operacional do processo.

Ela verifica:

1. se as **163 competências** estão presentes;
2. quantidade de linhas de cada CSV mensal, conforme registrada durante a consolidação;
3. tamanho de cada arquivo;
4. estrutura dos cabeçalhos;
5. quantidade total de linhas mensais;
6. quantidade de linhas lidas no arquivo consolidado;
7. quantidade de competências distintas presentes na coluna técnica;
8. existência das colunas técnicas;
9. correspondência entre o total mensal e o total consolidado.

A leitura do consolidado é feita em blocos e somente nas colunas necessárias à validação, reduzindo o uso de memória.

O resultado é salvo em:

`logs/validacao_final_cpgf.csv`

In [12]:
def validar_consolidado(
    caminho_consolidado: Path,
    relatorio_consolidacao: pd.DataFrame
) -> pd.DataFrame:
    """Executa as validações finais do projeto."""
    caminho_consolidado = Path(caminho_consolidado)

    if not caminho_consolidado.exists():
        raise FileNotFoundError(
            f'Consolidado não encontrado: {caminho_consolidado}'
        )

    # ------------------------------------------------------
    # 1. Competências mensais
    # ------------------------------------------------------
    ausentes = listar_competencias_ausentes(
        COMPETENCIA_INICIAL,
        COMPETENCIA_FINAL
    )

    total_arquivos_presentes = (
        len(COMPETENCIAS_ESPERADAS) - len(ausentes)
    )

    # ------------------------------------------------------
    # 2. Total de linhas mensais registrado na consolidação
    # ------------------------------------------------------
    total_linhas_mensais = int(
        relatorio_consolidacao['numero_linhas'].sum()
    )

    # ------------------------------------------------------
    # 3. Cabeçalho do consolidado
    # ------------------------------------------------------
    cabecalho_consolidado, encoding_consolidado, sep_consolidado = (
        ler_cabecalho_csv(caminho_consolidado)
    )

    colunas_tecnicas_ok = all(
        c in cabecalho_consolidado
        for c in ['COMPETENCIA_ARQUIVO', 'ARQUIVO_ORIGEM']
    )

    # ------------------------------------------------------
    # 4. Contagem independente do consolidado
    # ------------------------------------------------------
    total_linhas_consolidado = 0
    competencias_no_consolidado = set()
    arquivos_origem_no_consolidado = set()

    leitor = pd.read_csv(
        caminho_consolidado,
        sep=';',
        encoding='utf-8-sig',
        dtype=str,
        keep_default_na=False,
        na_filter=False,
        usecols=['COMPETENCIA_ARQUIVO', 'ARQUIVO_ORIGEM'],
        chunksize=500_000,
        on_bad_lines='error',
    )

    for chunk in leitor:
        total_linhas_consolidado += len(chunk)

        competencias_no_consolidado.update(
            chunk['COMPETENCIA_ARQUIVO'].unique().tolist()
        )

        arquivos_origem_no_consolidado.update(
            chunk['ARQUIVO_ORIGEM'].unique().tolist()
        )

    totais_batem = (
        total_linhas_consolidado == total_linhas_mensais
    )

    competencias_esperadas_set = set(COMPETENCIAS_ESPERADAS)

    competencias_consolidado_corretas = (
        competencias_no_consolidado == competencias_esperadas_set
        if not ausentes
        else competencias_no_consolidado.issubset(competencias_esperadas_set)
    )

    # ------------------------------------------------------
    # 5. Resumo
    # ------------------------------------------------------
    resumo = pd.DataFrame([
        {
            'indicador': 'competencias_esperadas',
            'valor': len(COMPETENCIAS_ESPERADAS),
            'status': 'OK',
        },
        {
            'indicador': 'arquivos_mensais_presentes',
            'valor': total_arquivos_presentes,
            'status': (
                'OK'
                if total_arquivos_presentes == len(COMPETENCIAS_ESPERADAS)
                else 'ATENÇÃO'
            ),
        },
        {
            'indicador': 'competencias_ausentes',
            'valor': len(ausentes),
            'status': 'OK' if not ausentes else 'ATENÇÃO',
        },
        {
            'indicador': 'linhas_somadas_nos_mensais',
            'valor': total_linhas_mensais,
            'status': 'OK',
        },
        {
            'indicador': 'linhas_lidas_no_consolidado',
            'valor': total_linhas_consolidado,
            'status': 'OK' if totais_batem else 'ERRO',
        },
        {
            'indicador': 'totais_de_linhas_coincidem',
            'valor': totais_batem,
            'status': 'OK' if totais_batem else 'ERRO',
        },
        {
            'indicador': 'competencias_distintas_no_consolidado',
            'valor': len(competencias_no_consolidado),
            'status': (
                'OK'
                if competencias_consolidado_corretas
                else 'ERRO'
            ),
        },
        {
            'indicador': 'arquivos_origem_distintos_no_consolidado',
            'valor': len(arquivos_origem_no_consolidado),
            'status': (
                'OK'
                if len(arquivos_origem_no_consolidado)
                == total_arquivos_presentes
                else 'ATENÇÃO'
            ),
        },
        {
            'indicador': 'colunas_tecnicas_presentes',
            'valor': colunas_tecnicas_ok,
            'status': 'OK' if colunas_tecnicas_ok else 'ERRO',
        },
        {
            'indicador': 'encoding_consolidado_detectado',
            'valor': encoding_consolidado,
            'status': 'OK',
        },
        {
            'indicador': 'separador_consolidado_detectado',
            'valor': repr(sep_consolidado),
            'status': 'OK' if sep_consolidado == ';' else 'ATENÇÃO',
        },
        {
            'indicador': 'tamanho_consolidado_gb',
            'valor': round(
                caminho_consolidado.stat().st_size / (1024 ** 3),
                3
            ),
            'status': 'OK',
        },
    ])

    resumo.to_csv(
        VALIDACAO_FINAL_CSV,
        sep=';',
        index=False,
        encoding='utf-8-sig'
    )

    print('=' * 80)
    print('✅ VALIDAÇÃO FINAL — CPGF')
    print('=' * 80)

    for _, linha in resumo.iterrows():
        print(
            f"{linha['status']:>7} | "
            f"{linha['indicador']}: {linha['valor']}"
        )

    if ausentes:
        print('\\n⚠️ Competências ausentes:')
        print(ausentes)

    print(f'\\n🧾 Validação salva em: {VALIDACAO_FINAL_CSV}')

    return resumo


resumo_validacao = validar_consolidado(
    caminho_consolidado,
    relatorio_consolidacao
)

display(resumo_validacao)

print('\\n📊 Quantidade de linhas por arquivo mensal:')
display(
    relatorio_consolidacao[
        [
            'competencia',
            'arquivo',
            'tamanho_mb',
            'numero_linhas',
            'numero_colunas_origem',
            'encoding_detectado',
            'separador_detectado',
        ]
    ]
)

================================================================================
✅ VALIDAÇÃO FINAL — CPGF
================================================================================
     OK | competencias_esperadas: 163
     OK | arquivos_mensais_presentes: 163
     OK | competencias_ausentes: 0
     OK | linhas_somadas_nos_mensais: 1876087
     OK | linhas_lidas_no_consolidado: 1876087
     OK | totais_de_linhas_coincidem: True
     OK | competencias_distintas_no_consolidado: 163
     OK | arquivos_origem_distintos_no_consolidado: 163
     OK | colunas_tecnicas_presentes: True
     OK | encoding_consolidado_detectado: utf-8-sig
     OK | separador_consolidado_detectado: ';'
     OK | tamanho_consolidado_gb: 0.487
\n🧾 Validação salva em: /content/drive/MyDrive/Suprimentos de Fundos - CPGF/logs/validacao_final_cpgf.csv

                                   indicador      valor status
0                     competencias_esperadas        163     OK
1                 arquivos_mensais_presentes        163     OK
2                      competencias_ausentes          0     OK
3                 linhas_somadas_nos_mensais    1876087     OK
4                linhas_lidas_no_consolidado    1876087     OK
5                 totais_de_linhas_coincidem       True     OK
6      competencias_distintas_no_consolidado        163     OK
7   arquivos_origem_distintos_no_consolidado        163     OK
8                 colunas_tecnicas_presentes       True     OK
9             encoding_consolidado_detectado  utf-8-sig     OK
10           separador_consolidado_detectado        ';'     OK
11                    tamanho_consolidado_gb      0.487     OK

\n📊 Quantidade de linhas por arquivo mensal:

,competencia,arquivo,tamanho_mb,numero_linhas,numero_colunas_origem,encoding_detectado,separador_detectado
0,201301,201301_CPGF.csv,5.03,17550,15,cp1252,';'
1,201302,201302_CPGF.csv,0.91,3310,15,cp1252,';'
2,201303,201303_CPGF.csv,2.64,9473,15,cp1252,';'
3,201304,201304_CPGF.csv,4.52,16190,15,cp1252,';'
4,201305,201305_CPGF.csv,5.39,19377,15,cp1252,';'
...,...,...,...,...,...,...,...
158,202603,202603_CPGF.csv,2.05,7729,15,cp1252,';'
159,202604,202604_CPGF.csv,3.89,14741,15,cp1252,';'
160,202605,202605_CPGF.csv,3.51,13437,15,cp1252,';'
161,202606,202606_CPGF.csv,4.95,18793,15,cp1252,';'
162,202607,202607_CPGF.csv,3.98,15025,15,cp1252,';'

## ✅ Resultado esperado

Ao final do notebook, a pasta principal deverá conter os arquivos:

`201301_CPGF.csv`  
`201302_CPGF.csv`  
`...`  
`202607_CPGF.csv`

A subpasta `dados_consolidado` deverá conter:

`CPGF_201301_a_202607.csv`

e a pasta `logs` registrará os controles de:

- downloads;
- competências presentes e ausentes;
- diferenças de estrutura;
- número de linhas por arquivo;
- validação final.

### 🔎 Observação para as próximas etapas da pesquisa

Os arquivos mensais permanecem como **camada bruta e reproduzível**. Recomenda-se que qualquer limpeza, transformação, criação de variáveis, aplicação da Lei de Newcomb-Benford ou execução das trilhas de análise seja realizada posteriormente em outro notebook, preservando esta etapa exclusivamente como pipeline de aquisição e consolidação dos dados públicos.